//! Generating `#[repr(C)]` Rust bindings from a reflected [`AbiModel`].
//!
//! This is the module that makes GPU/CPU ABI drift a compile error instead of
//! a discipline problem. For each reflected uniform struct we emit:
//!
//! * a `#[repr(C, align(N))]` struct whose fields sit at the exact byte
//!   offsets Slang reported, with explicit padding filling every gap;
//! * a `zeroed()` constructor (via the derived `Zeroable`, or an explicit
//!   const initializer when `bytemuck` is disabled);
//! * `const _: () = assert!(..)` guards on the total size and on every field
//!   offset via [`core::mem::offset_of`], so a layout mismatch fails to
//!   compile rather than corrupting a draw.
//!
//! The output is plain text; the consuming crate supplies `bytemuck` (when the
//! derive is enabled). Codegen itself has no GPU or `bytemuck` dependency and
//! is fully unit-tested.

use std::fmt::Write as _;

use crate::reflection::model::{AbiModel, FieldType, Scalar, StructLayout};

/// Options controlling the generated Rust source.
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    /// Emit `#[derive(bytemuck::Pod, bytemuck::Zeroable)]` on each struct.
    pub derive_bytemuck: bool,
    /// Extra derives to attach (for example `serde::Serialize`).
    pub extra_derives: Vec<String>,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            derive_bytemuck: true,
            extra_derives: Vec::new(),
        }
    }
}

/// Generate a complete Rust source string for every struct in `model`.
pub fn generate(model: &AbiModel, options: &CodegenOptions) -> String {
    let mut out = String::new();
    out.push_str("// @generated by prism_render_slang::codegen - do not edit by hand.\n");
    out.push_str("// Source of truth: Slang reflection JSON.\n");
    let _ = writeln!(out, "// Reflection version: {}\n", model.reflection_version);
    let _ = writeln!(
        out,
        "/// Content-derived ABI version; changes when any layout changes.\n\
         pub const MATERIAL_ABI_VERSION: u64 = {};\n",
        model.abi_version()
    );

    for layout in &model.structs {
        out.push_str(&generate_struct(layout, options));
        out.push('\n');
    }
    out
}

/// Generate the Rust source for a single struct layout.
pub fn generate_struct(layout: &StructLayout, options: &CodegenOptions) -> String {
    let mut out = String::new();
    let type_name = to_pascal_case(&layout.name);

    let mut derives = vec![
        "Clone".to_string(),
        "Copy".to_string(),
        "Debug".to_string(),
        "PartialEq".to_string(),
    ];
    if options.derive_bytemuck {
        derives.push("bytemuck::Pod".to_string());
        derives.push("bytemuck::Zeroable".to_string());
    }
    derives.extend(options.extra_derives.iter().cloned());

    let _ = writeln!(out, "#[derive({})]", derives.join(", "));
    if is_pow2_gt1(layout.alignment) {
        let _ = writeln!(out, "#[repr(C, align({}))]", layout.alignment);
    } else {
        out.push_str("#[repr(C)]\n");
    }
    let _ = writeln!(out, "pub struct {type_name} {{");

    let mut cursor: u32 = 0;
    let mut pad_index: u32 = 0;
    for field in &layout.fields {
        if field.offset > cursor {
            let gap = field.offset - cursor;
            let _ = writeln!(out, "    pub _pad{pad_index}: [u8; {gap}],");
            pad_index += 1;
        }
        let rust_ty = rust_type_of(&field.ty, field.size);
        let field_name = to_snake_case_ident(&field.name);
        let _ = writeln!(out, "    pub {field_name}: {rust_ty},");
        cursor = field.offset + field.size;
    }
    if layout.size > cursor {
        let gap = layout.size - cursor;
        let _ = writeln!(out, "    pub _pad{pad_index}: [u8; {gap}],");
    }
    out.push_str("}\n\n");

    out.push_str(&generate_constructor(&type_name, layout, options));
    out.push_str(&generate_asserts(&type_name, layout));
    out
}

fn generate_constructor(type_name: &str, layout: &StructLayout, options: &CodegenOptions) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "impl {type_name} {{");
    out.push_str("    /// An all-zero instance, including padding bytes.\n");

    if options.derive_bytemuck {
        out.push_str("    pub fn zeroed() -> Self {\n");
        out.push_str("        <Self as bytemuck::Zeroable>::zeroed()\n");
        out.push_str("    }\n");
    } else {
        out.push_str("    pub const fn zeroed() -> Self {\n");
        out.push_str("        Self {\n");
        let mut cursor: u32 = 0;
        let mut pad_index: u32 = 0;
        for field in &layout.fields {
            if field.offset > cursor {
                let gap = field.offset - cursor;
                let _ = writeln!(out, "            _pad{pad_index}: [0u8; {gap}],");
                pad_index += 1;
            }
            let field_name = to_snake_case_ident(&field.name);
            let zero = zero_literal(&field.ty, field.size);
            let _ = writeln!(out, "            {field_name}: {zero},");
            cursor = field.offset + field.size;
        }
        if layout.size > cursor {
            let gap = layout.size - cursor;
            let _ = writeln!(out, "            _pad{pad_index}: [0u8; {gap}],");
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
    }
    out.push_str("}\n\n");
    out
}

fn generate_asserts(type_name: &str, layout: &StructLayout) -> String {
    let mut out = String::new();
    out.push_str("// Layout guards: any drift from the reflected ABI fails to compile.\n");
    let _ = writeln!(
        out,
        "const _: () = assert!(core::mem::size_of::<{type_name}>() == {});",
        layout.size
    );
    for field in &layout.fields {
        let field_name = to_snake_case_ident(&field.name);
        let _ = writeln!(
            out,
            "const _: () = assert!(core::mem::offset_of!({type_name}, {field_name}) == {});",
            field.offset
        );
    }
    out.push('\n');
    out
}

/// Map a reflected field type + byte size to a Rust type whose size matches.
fn rust_type_of(ty: &FieldType, size: u32) -> String {
    match ty {
        FieldType::Scalar(scalar) => scalar.rust_primitive().to_string(),
        FieldType::Vector { elem, count } => format!("[{}; {count}]", elem.rust_primitive()),
        FieldType::Matrix { elem, rows, cols } => {
            format!("[{}; {}]", elem.rust_primitive(), rows * cols)
        }
        FieldType::Array { element, count } => {
            let inner = rust_type_of(element, size.checked_div(*count).unwrap_or(0));
            format!("[{inner}; {count}]")
        }
        FieldType::Struct { .. } | FieldType::Opaque { .. } => format!("[u8; {size}]"),
    }
}

/// A zero literal for a field type, mirroring [`rust_type_of`].
fn zero_literal(ty: &FieldType, size: u32) -> String {
    match ty {
        FieldType::Scalar(scalar) => scalar_zero(*scalar).to_string(),
        FieldType::Vector { elem, count } => format!("[{}; {count}]", scalar_zero(*elem)),
        FieldType::Matrix { elem, rows, cols } => {
            format!("[{}; {}]", scalar_zero(*elem), rows * cols)
        }
        FieldType::Array { element, count } => {
            let inner = zero_literal(element, size.checked_div(*count).unwrap_or(0));
            format!("[{inner}; {count}]")
        }
        FieldType::Struct { .. } | FieldType::Opaque { .. } => format!("[0u8; {size}]"),
    }
}

fn scalar_zero(scalar: Scalar) -> &'static str {
    match scalar.rust_primitive() {
        "f32" => "0.0f32",
        "f64" => "0.0f64",
        "u32" => "0u32",
        "i32" => "0i32",
        "u16" => "0u16",
        "i16" => "0i16",
        "u8" => "0u8",
        "i8" => "0i8",
        "u64" => "0u64",
        "i64" => "0i64",
        _ => "0",
    }
}

fn is_pow2_gt1(value: u32) -> bool {
    value > 1 && value.is_power_of_two()
}

/// Convert a Slang identifier to `snake_case`, escaping Rust keywords.
fn to_snake_case_ident(name: &str) -> String {
    let snake = to_snake_case(name);
    if is_rust_keyword(&snake) {
        format!("r#{snake}")
    } else {
        snake
    }
}

fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    let mut prev_lower_or_digit = false;
    for ch in name.chars() {
        if ch.is_ascii_uppercase() {
            if prev_lower_or_digit {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = false;
        } else {
            out.push(ch);
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    out
}

fn to_pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
        None => "Anonymous".to_string(),
    }
}

fn is_rust_keyword(word: &str) -> bool {
    matches!(
        word,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reflection::model::Field;

    fn params_layout() -> StructLayout {
        StructLayout {
            name: "Params".to_string(),
            size: 16,
            alignment: 16,
            fields: vec![
                Field {
                    name: "baseColor".to_string(),
                    ty: FieldType::Vector {
                        elem: Scalar::F32,
                        count: 3,
                    },
                    offset: 0,
                    size: 12,
                },
                Field {
                    name: "roughness".to_string(),
                    ty: FieldType::Scalar(Scalar::F32),
                    offset: 12,
                    size: 4,
                },
            ],
        }
    }

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("baseColor"), "base_color");
        assert_eq!(to_snake_case("roughness"), "roughness");
        assert_eq!(to_snake_case("n"), "n");
        assert_eq!(to_snake_case("clearCoatRoughness"), "clear_coat_roughness");
    }

    #[test]
    fn keyword_fields_are_escaped() {
        assert_eq!(to_snake_case_ident("type"), "r#type");
        assert_eq!(to_snake_case_ident("baseColor"), "base_color");
    }

    #[test]
    fn generated_struct_has_repr_align_and_fields() {
        let src = generate_struct(&params_layout(), &CodegenOptions::default());
        assert!(src.contains("#[repr(C, align(16))]"));
        assert!(src.contains("pub struct Params"));
        assert!(src.contains("pub base_color: [f32; 3]"));
        assert!(src.contains("pub roughness: f32"));
        assert!(src.contains("bytemuck::Pod"));
        assert!(src.contains("size_of::<Params>() == 16"));
        assert!(src.contains("offset_of!(Params, base_color) == 0"));
        assert!(src.contains("offset_of!(Params, roughness) == 12"));
    }

    #[test]
    fn trailing_padding_fills_to_size() {
        let mut layout = params_layout();
        layout.fields.pop();
        let src = generate_struct(&layout, &CodegenOptions::default());
        assert!(src.contains("_pad0: [u8; 4]"));
    }

    #[test]
    fn interior_padding_between_fields() {
        let layout = StructLayout {
            name: "Gapped".to_string(),
            size: 32,
            alignment: 16,
            fields: vec![
                Field {
                    name: "a".to_string(),
                    ty: FieldType::Scalar(Scalar::F32),
                    offset: 0,
                    size: 4,
                },
                Field {
                    name: "b".to_string(),
                    ty: FieldType::Vector {
                        elem: Scalar::F32,
                        count: 3,
                    },
                    offset: 16,
                    size: 12,
                },
            ],
        };
        let src = generate_struct(&layout, &CodegenOptions::default());
        assert!(src.contains("_pad0: [u8; 12]"));
        assert!(src.contains("_pad1: [u8; 4]"));
    }

    #[test]
    fn bytemuck_derive_toggles_constructor_form() {
        let opts = CodegenOptions {
            derive_bytemuck: false,
            extra_derives: vec![],
        };
        let src = generate_struct(&params_layout(), &opts);
        assert!(!src.contains("bytemuck"));
        assert!(src.contains("pub const fn zeroed()"));
        assert!(src.contains("base_color: [0.0f32; 3]"));
    }
}
