//! The kinds of nodes a Patch graph may contain.
//!
//! # Provenance
//! Original work; no Unreal Engine, Unity, Godot, Wwise, FMOD, Steam Audio, or
//! Google Resonance Audio source or derived code; no AI/ML.
//!
//! # Relationship
//! Enumerates the design section 11 node library plus the nested-`SubPatch`
//! reference used for bounded compile-time expansion. Each variant knows its
//! port shape, its exposed parameter and trigger names, and how to instantiate
//! the matching `prism_audio_core::graph::AudioNode`. The compiler flattens
//! every `SubPatch` into leaf nodes before instantiation, so `instantiate` is
//! only ever asked to build leaf primitives.

#[cfg(not(feature = "std"))]
use alloc::boxed::Box;

use prism_audio_core::graph::AudioNode;
use prism_audio_core::Sample;

use super::description::PatchDescription;
use super::library::{
    AdsrAmpNode, ConstantNode, GainNode, NoiseNode, OnePoleLowpassNode, OscillatorNode,
    ProductNode, SumNode,
};
use super::library::oscillator::OscWaveform;
use super::param::ParamCell;
use super::port::PortCount;
use super::trigger::GateCell;
use crate::modulation::envelope::EnvelopeConfig;

/// A single primitive (or nested patch) that can appear in a Patch graph.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
pub enum NodeKind {
    /// A smoothed constant/DC source with one exposed `value` parameter.
    Constant,
    /// A deterministic oscillator with exposed `frequency` and `amplitude`.
    Oscillator {
        /// Waveform generated by the oscillator.
        waveform: OscWaveform,
    },
    /// A seeded white-noise source with an exposed `amplitude`.
    Noise {
        /// Seed for the deterministic generator.
        seed: u64,
    },
    /// A smoothed gain stage with one exposed `gain` parameter.
    Gain,
    /// A summing mixer with a configurable number of mono inputs.
    Sum {
        /// Number of input ports to sum.
        inputs: usize,
    },
    /// A two-input multiplier (ring modulation / amplitude control).
    Product,
    /// A first-order low-pass filter with an exposed `cutoff_hz` parameter.
    OnePoleLowpass,
    /// A gate-driven amplitude envelope with a `gate` trigger input.
    AdsrAmp {
        /// Envelope timing and shape configuration.
        config: EnvelopeConfig,
    },
    /// A nested patch, expanded in place by the compiler.
    SubPatch(Box<PatchDescription>),
}

impl NodeKind {
    /// Returns the input/output port shape of this node.
    #[must_use]
    pub fn port_count(&self) -> PortCount {
        match self {
            NodeKind::Constant | NodeKind::Oscillator { .. } | NodeKind::Noise { .. } => {
                PortCount::new(0, 1)
            }
            NodeKind::Gain | NodeKind::OnePoleLowpass | NodeKind::AdsrAmp { .. } => {
                PortCount::new(1, 1)
            }
            NodeKind::Product => PortCount::new(2, 1),
            NodeKind::Sum { inputs } => PortCount::new((*inputs).max(1), 1),
            NodeKind::SubPatch(desc) => PortCount::new(0, desc.output_count()),
        }
    }

    /// Returns the ordered names of the exposed scalar parameters.
    #[must_use]
    pub fn param_names(&self) -> &'static [&'static str] {
        match self {
            NodeKind::Constant => &["value"],
            NodeKind::Oscillator { .. } => &["frequency", "amplitude"],
            NodeKind::Noise { .. } => &["amplitude"],
            NodeKind::Gain => &["gain"],
            NodeKind::OnePoleLowpass => &["cutoff_hz"],
            NodeKind::Sum { .. }
            | NodeKind::Product
            | NodeKind::AdsrAmp { .. }
            | NodeKind::SubPatch(_) => &[],
        }
    }

    /// Returns the default value for each parameter, matching
    /// [`NodeKind::param_names`] order.
    #[must_use]
    pub fn param_defaults(&self) -> &'static [Sample] {
        match self {
            NodeKind::Constant => &[0.0],
            NodeKind::Oscillator { .. } => &[440.0, 1.0],
            NodeKind::Noise { .. } | NodeKind::Gain => &[1.0],
            NodeKind::OnePoleLowpass => &[1_000.0],
            NodeKind::Sum { .. }
            | NodeKind::Product
            | NodeKind::AdsrAmp { .. }
            | NodeKind::SubPatch(_) => &[],
        }
    }

    /// Returns the ordered names of the exposed trigger/gate inputs.
    #[must_use]
    pub fn gate_names(&self) -> &'static [&'static str] {
        match self {
            NodeKind::AdsrAmp { .. } => &["gate"],
            NodeKind::Constant
            | NodeKind::Oscillator { .. }
            | NodeKind::Noise { .. }
            | NodeKind::Gain
            | NodeKind::OnePoleLowpass
            | NodeKind::Sum { .. }
            | NodeKind::Product
            | NodeKind::SubPatch(_) => &[],
        }
    }

    /// Builds the runtime node for a leaf kind.
    ///
    /// `param_cells` and `gate_cells` must match [`NodeKind::param_names`] and
    /// [`NodeKind::gate_names`] in length and order. Returns `None` for a
    /// [`NodeKind::SubPatch`], which the compiler flattens before reaching this
    /// point.
    #[must_use]
    pub fn instantiate(
        &self,
        sample_rate: u32,
        param_cells: &[ParamCell],
        gate_cells: &[GateCell],
    ) -> Option<Box<dyn AudioNode>> {
        match self {
            NodeKind::Constant => {
                Some(Box::new(ConstantNode::new(param_cells[0].clone())))
            }
            NodeKind::Oscillator { waveform } => Some(Box::new(OscillatorNode::new(
                sample_rate,
                *waveform,
                param_cells[0].clone(),
                param_cells[1].clone(),
            ))),
            NodeKind::Noise { seed } => {
                Some(Box::new(NoiseNode::new(*seed, param_cells[0].clone())))
            }
            NodeKind::Gain => Some(Box::new(GainNode::new(param_cells[0].clone()))),
            NodeKind::Sum { inputs } => Some(Box::new(SumNode::new(*inputs))),
            NodeKind::Product => Some(Box::new(ProductNode::new())),
            NodeKind::OnePoleLowpass => Some(Box::new(OnePoleLowpassNode::new(
                sample_rate,
                param_cells[0].clone(),
            ))),
            NodeKind::AdsrAmp { config } => Some(Box::new(AdsrAmpNode::new(
                sample_rate,
                config.clone(),
                gate_cells[0].clone(),
            ))),
            NodeKind::SubPatch(_) => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn leaf_port_counts() {
        assert_eq!(NodeKind::Constant.port_count(), PortCount::new(0, 1));
        assert_eq!(NodeKind::Gain.port_count(), PortCount::new(1, 1));
        assert_eq!(NodeKind::Product.port_count(), PortCount::new(2, 1));
        assert_eq!(NodeKind::Sum { inputs: 3 }.port_count(), PortCount::new(3, 1));
    }

    #[test]
    fn param_and_gate_names_align_with_defaults() {
        let osc = NodeKind::Oscillator {
            waveform: OscWaveform::Sine,
        };
        assert_eq!(osc.param_names().len(), osc.param_defaults().len());
        assert!(osc.gate_names().is_empty());
        let env = NodeKind::AdsrAmp {
            config: EnvelopeConfig::default(),
        };
        assert_eq!(env.gate_names(), &["gate"]);
    }

    #[test]
    fn leaf_instantiates_and_subpatch_does_not() {
        let cell = ParamCell::new(1.0);
        let node = NodeKind::Gain.instantiate(48_000, core::slice::from_ref(&cell), &[]);
        assert!(node.is_some());
    }
}
