//! Rotary-speaker (Leslie-style) cabinet simulation.
//!
//! A [`LeslieNode`] emulates the sound of a rotating-speaker cabinet, in which
//! a treble horn and a bass rotor spin inside a fixed enclosure in front of a
//! pair of microphones. The physical rotation imposes three coupled, periodic
//! effects on the sound that together create the instantly recognisable
//! swirling, three-dimensional character:
//!
//! - a **Doppler** pitch wobble, because each rotor alternately moves toward
//!   and away from the microphones (modelled as a modulated fractional delay);
//! - an **amplitude** tremolo, because each rotor's horn alternately faces and
//!   turns away from the microphones (modelled as a periodic gain);
//! - a **stereo** pan, because the two virtual microphones hear the rotation in
//!   opposite phase.
//!
//! The input is first split by a Linkwitz-Riley crossover into a low band that
//! drives the slow, heavy bass rotor and a high band that drives the light,
//! fast treble horn. The two rotors spin at different nominal rates and in
//! opposite directions, and each has its own mechanical inertia so that
//! switching between the slow ("chorale") and fast ("tremolo") speeds ramps up
//! or coasts down over a realistic spin-up / spin-down time rather than
//! changing instantly.
//!
//! # Provenance
//!
//! Implemented from first principles from the public, well-documented physics
//! of a rotating-speaker cabinet (Doppler shift from a moving source, a
//! directional horn, and two stationary microphones). No source code or
//! derivative code from UE, Unity, Godot, Wwise, FMOD, Steam Audio, Google
//! Resonance Audio, or Web Audio was consulted or copied, and no brand name is
//! used to designate anything other than the generic acoustic phenomenon. There
//! is no AI or machine learning of any kind: every modulator is a deterministic
//! sinusoid driven by an explicit rotor phase accumulator.
//!
//! # Relationship
//!
//! The band split reuses the shared
//! [`LinkwitzRileyCrossover`](crate::nodes::crossover::LinkwitzRileyCrossover)
//! rather than carrying a private filter bank. The per-rotor Doppler uses the
//! same modulated fractional-delay idea as
//! [`chorus`](crate::nodes::effects::chorus) and
//! [`flanger`](crate::nodes::effects::flanger), but couples the delay with a
//! phase-locked amplitude tremolo and antiphase stereo imaging driven by a
//! single rotor angle, which neither of those effects does. Unlike the purely
//! amplitude-domain [`tremolo`](crate::nodes::effects::tremolo) it also moves
//! the pitch and the stereo image, and unlike a static panner the motion is
//! generated by the simulated mechanical rotation with inertia.
//!
//! # Real-time contract
//!
//! The crossover, the mono downmix scratch, the per-band buffers, and both
//! rotor delay lines are sized and allocated in [`LeslieNode::new`]. `process`
//! only reads inputs, advances the rotor phase accumulators, and writes
//! outputs; it flushes denormals on every stored and emitted sample, performs
//! no allocation or locking, and is panic-free.

use alloc::{vec, vec::Vec};

use bevy_math::ops;

use core::f32::consts::TAU;

use crate::buffer::{AudioBuffer, ChannelLayout};
use crate::graph::{AudioNode, ProcessIo, RenderContext};
use crate::math::{Sample, flush_denormal, lerp};
use crate::nodes::crossover::LinkwitzRileyCrossover;
use crate::param::{Ramp, Smoothed};

/// Default horn/drum crossover frequency in Hz.
pub const DEFAULT_CROSSOVER_HZ: Sample = 800.0;

/// Nominal slow ("chorale") rotation rate of the treble horn, in Hz.
pub const HORN_SLOW_HZ: Sample = 0.8;

/// Nominal fast ("tremolo") rotation rate of the treble horn, in Hz.
pub const HORN_FAST_HZ: Sample = 6.9;

/// Nominal slow ("chorale") rotation rate of the bass rotor, in Hz.
pub const DRUM_SLOW_HZ: Sample = 0.7;

/// Nominal fast ("tremolo") rotation rate of the bass rotor, in Hz.
pub const DRUM_FAST_HZ: Sample = 6.5;

/// Time constant for the light treble horn to speed up, in seconds.
pub const HORN_ACCEL_SECONDS: Sample = 1.0;

/// Time constant for the light treble horn to coast down, in seconds.
pub const HORN_DECEL_SECONDS: Sample = 0.6;

/// Time constant for the heavy bass rotor to speed up, in seconds.
pub const DRUM_ACCEL_SECONDS: Sample = 3.2;

/// Time constant for the heavy bass rotor to coast down, in seconds.
pub const DRUM_DECEL_SECONDS: Sample = 4.0;

/// Largest accepted amplitude-tremolo depth.
pub const MAX_AM_DEPTH: Sample = 1.0;

/// Largest accepted (normalised) Doppler modulation depth.
pub const MAX_DOPPLER_DEPTH: Sample = 1.0;

/// Mean read-back delay of each rotor line, in milliseconds.
const BASE_DELAY_MS: Sample = 5.0;

/// Peak Doppler delay swing of the treble horn, in milliseconds.
const HORN_DOPPLER_MS: Sample = 4.0;

/// Peak Doppler delay swing of the bass rotor, in milliseconds.
const DRUM_DOPPLER_MS: Sample = 2.8;

/// Amplitude-tremolo scaling applied to the (strongly directional) horn.
const HORN_AM_SCALE: Sample = 1.0;

/// Amplitude-tremolo scaling applied to the (weakly directional) bass rotor.
const DRUM_AM_SCALE: Sample = 0.4;

/// Smallest usable delay read-back, in samples (keeps interpolation in range).
const MIN_DELAY_SAMPLES: Sample = 1.0;

/// Rotor spin speed selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
pub enum LeslieSpeed {
    /// Rotors braked to a standstill.
    Brake,
    /// Slow "chorale" rotation (the default).
    #[default]
    Chorale,
    /// Fast "tremolo" rotation.
    Tremolo,
}

/// Construction and automation parameters for a [`LeslieNode`].
#[derive(Debug, Clone, Copy, PartialEq)]
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
pub struct LeslieParams {
    /// Target rotor speed.
    pub speed: LeslieSpeed,
    /// Horn/drum split frequency in Hz (fixed at construction).
    pub crossover_hz: Sample,
    /// Doppler modulation depth in `[0, MAX_DOPPLER_DEPTH]`.
    pub doppler_depth: Sample,
    /// Amplitude-tremolo depth in `[0, MAX_AM_DEPTH]`.
    pub am_depth: Sample,
    /// Stereo spread in `[0, 1]` (0 collapses to mono, 1 is the widest image).
    pub stereo_spread: Sample,
    /// Wet (processed) output gain.
    pub wet: Sample,
    /// Dry (unprocessed) output gain.
    pub dry: Sample,
}

impl Default for LeslieParams {
    fn default() -> Self {
        Self {
            speed: LeslieSpeed::Chorale,
            crossover_hz: DEFAULT_CROSSOVER_HZ,
            doppler_depth: 0.5,
            am_depth: 0.5,
            stereo_spread: 1.0,
            wet: 1.0,
            dry: 0.0,
        }
    }
}

impl LeslieParams {
    /// Returns a copy with every field clamped to its valid range and any
    /// non-finite value replaced by the default.
    #[must_use]
    pub fn sanitised(self) -> Self {
        let d = Self::default();
        Self {
            speed: self.speed,
            crossover_hz: if self.crossover_hz.is_finite() {
                self.crossover_hz.clamp(20.0, 16_000.0)
            } else {
                d.crossover_hz
            },
            doppler_depth: clamp_unit_or(self.doppler_depth, d.doppler_depth, MAX_DOPPLER_DEPTH),
            am_depth: clamp_unit_or(self.am_depth, d.am_depth, MAX_AM_DEPTH),
            stereo_spread: clamp_unit_or(self.stereo_spread, d.stereo_spread, 1.0),
            wet: if self.wet.is_finite() {
                self.wet.clamp(0.0, 4.0)
            } else {
                d.wet
            },
            dry: if self.dry.is_finite() {
                self.dry.clamp(0.0, 4.0)
            } else {
                d.dry
            },
        }
    }
}

/// Clamps `value` to `[0, hi]`, substituting `fallback` when non-finite.
fn clamp_unit_or(value: Sample, fallback: Sample, hi: Sample) -> Sample {
    if value.is_finite() {
        value.clamp(0.0, hi)
    } else {
        fallback
    }
}

/// Nominal target rate in Hz for `speed` given a rotor's slow/fast rates.
fn target_rate(speed: LeslieSpeed, slow_hz: Sample, fast_hz: Sample) -> Sample {
    match speed {
        LeslieSpeed::Brake => 0.0,
        LeslieSpeed::Chorale => slow_hz,
        LeslieSpeed::Tremolo => fast_hz,
    }
}

/// One rotating element (horn or drum): a modulated delay line plus a phase
/// accumulator with mechanical inertia.
#[derive(Debug, Clone)]
struct Rotor {
    phase: Sample,
    rate: Sample,
    direction: Sample,
    accel_coeff: Sample,
    decel_coeff: Sample,
    base_delay: Sample,
    max_depth: Sample,
    am_scale: Sample,
    line: Vec<Sample>,
    write_idx: usize,
}

impl Rotor {
    /// Builds a rotor from its geometry and inertia at a starting rate.
    fn new(
        sample_rate: Sample,
        direction: Sample,
        accel_seconds: Sample,
        decel_seconds: Sample,
        doppler_ms: Sample,
        am_scale: Sample,
        start_rate: Sample,
    ) -> Self {
        let base_delay = BASE_DELAY_MS * sample_rate * 0.001;
        let max_depth = doppler_ms * sample_rate * 0.001;
        let line_len = (ops::round(base_delay + max_depth) as usize) + 2;
        Self {
            phase: 0.0,
            rate: start_rate,
            direction,
            accel_coeff: inertia_coeff(accel_seconds, sample_rate),
            decel_coeff: inertia_coeff(decel_seconds, sample_rate),
            base_delay,
            max_depth,
            am_scale,
            line: vec![0.0; line_len],
            write_idx: 0,
        }
    }

    /// Reads the line `delay` fractional samples behind the write head.
    fn read_frac(&self, delay: Sample) -> Sample {
        let len_i = self.line.len() as isize;
        let read_pos = self.write_idx as Sample - delay;
        let base = ops::floor(read_pos);
        let frac = read_pos - base;
        let base_i = base as isize;
        let i0 = base_i.rem_euclid(len_i) as usize;
        let i1 = (base_i + 1).rem_euclid(len_i) as usize;
        lerp(self.line[i0], self.line[i1], frac)
    }

    /// Processes one input sample and returns its stereo (left, right) image.
    fn tick(
        &mut self,
        x: Sample,
        am_depth: Sample,
        doppler_depth: Sample,
        sample_rate: Sample,
        target: Sample,
    ) -> (Sample, Sample) {
        let len_max = (self.line.len() - 1) as Sample;
        let depth = self.max_depth * doppler_depth;
        let (sin_p, cos_p) = ops::sin_cos(self.phase);

        // The left and right microphones hear the rotation in opposite phase.
        let delay_l = (self.base_delay + depth * sin_p).clamp(MIN_DELAY_SAMPLES, len_max);
        let delay_r = (self.base_delay - depth * sin_p).clamp(MIN_DELAY_SAMPLES, len_max);
        let am = am_depth * self.am_scale;
        let left = self.read_frac(delay_l) * (1.0 + am * cos_p);
        let right = self.read_frac(delay_r) * (1.0 - am * cos_p);

        // Store the current input, then advance the rotor.
        let w = self.write_idx;
        self.line[w] = flush_denormal(x);
        self.write_idx = if w + 1 == self.line.len() { 0 } else { w + 1 };

        let coeff = if target > self.rate {
            self.accel_coeff
        } else {
            self.decel_coeff
        };
        self.rate += coeff * (target - self.rate);
        let increment = self.direction * TAU * self.rate / sample_rate;
        // Wrap the phase into [0, TAU) without the std-only f32::rem_euclid.
        let next = self.phase + increment;
        self.phase = next - TAU * ops::floor(next / TAU);

        (left, right)
    }

    /// Clears the delay line and parks the rotor at `target` with zero phase.
    fn reset(&mut self, target: Sample) {
        for value in &mut self.line {
            *value = 0.0;
        }
        self.write_idx = 0;
        self.phase = 0.0;
        self.rate = target;
    }
}

/// One-pole smoothing coefficient for a `seconds` time constant at `sr`.
fn inertia_coeff(seconds: Sample, sample_rate: Sample) -> Sample {
    let tau = seconds.max(1.0e-4);
    1.0 - ops::exp(-1.0 / (tau * sample_rate))
}

/// A rotary-speaker cabinet (input port 0 -> stereo output port 0).
///
/// The dry path is latency-free; the wet path adds the short, modulated rotor
/// delay as part of the effect rather than as reported latency.
#[derive(Debug, Clone)]
pub struct LeslieNode {
    sample_rate: u32,
    crossover: LinkwitzRileyCrossover,
    mono: AudioBuffer,
    bands: Vec<AudioBuffer>,
    horn: Rotor,
    drum: Rotor,
    speed: LeslieSpeed,
    doppler_depth: Sample,
    am_depth: Sample,
    stereo_spread: Sample,
    wet: Smoothed,
    dry: Smoothed,
    max_block_frames: usize,
}

impl LeslieNode {
    /// Builds a rotary-speaker cabinet for blocks of up to `max_block_frames`.
    ///
    /// The horn/drum crossover frequency is fixed at construction; parameters
    /// are sanitized before use.
    ///
    /// # Example
    ///
    /// ```
    /// use prism_audio_core::nodes::effects::leslie::{LeslieNode, LeslieParams};
    /// use prism_audio_core::graph::AudioNode;
    ///
    /// let node = LeslieNode::new(48_000, 512, LeslieParams::default());
    /// assert_eq!(node.latency_frames(), 0);
    /// ```
    #[must_use]
    pub fn new(sample_rate: u32, max_block_frames: usize, params: LeslieParams) -> Self {
        let p = params.sanitised();
        let sr = sample_rate.max(1);
        let srf = sr as Sample;
        let frames = max_block_frames.max(1);

        let crossover = LinkwitzRileyCrossover::new(
            sr,
            ChannelLayout::Mono,
            &[p.crossover_hz],
            frames,
        );
        let mono = AudioBuffer::new(ChannelLayout::Mono, frames);
        let bands = vec![
            AudioBuffer::new(ChannelLayout::Mono, frames),
            AudioBuffer::new(ChannelLayout::Mono, frames),
        ];

        let horn = Rotor::new(
            srf,
            1.0,
            HORN_ACCEL_SECONDS,
            HORN_DECEL_SECONDS,
            HORN_DOPPLER_MS,
            HORN_AM_SCALE,
            target_rate(p.speed, HORN_SLOW_HZ, HORN_FAST_HZ),
        );
        let drum = Rotor::new(
            srf,
            -1.0,
            DRUM_ACCEL_SECONDS,
            DRUM_DECEL_SECONDS,
            DRUM_DOPPLER_MS,
            DRUM_AM_SCALE,
            target_rate(p.speed, DRUM_SLOW_HZ, DRUM_FAST_HZ),
        );

        Self {
            sample_rate: sr,
            crossover,
            mono,
            bands,
            horn,
            drum,
            speed: p.speed,
            doppler_depth: p.doppler_depth,
            am_depth: p.am_depth,
            stereo_spread: p.stereo_spread,
            wet: Smoothed::new(p.wet),
            dry: Smoothed::new(p.dry),
            max_block_frames: frames,
        }
    }

    /// Largest block size, in frames, the node was built for.
    #[must_use]
    pub fn max_block_frames(&self) -> usize {
        self.max_block_frames
    }

    /// Current target rotor speed.
    #[must_use]
    pub fn speed(&self) -> LeslieSpeed {
        self.speed
    }

    /// Current Doppler modulation depth.
    #[must_use]
    pub fn doppler_depth(&self) -> Sample {
        self.doppler_depth
    }

    /// Current amplitude-tremolo depth.
    #[must_use]
    pub fn am_depth(&self) -> Sample {
        self.am_depth
    }

    /// Current stereo spread.
    #[must_use]
    pub fn stereo_spread(&self) -> Sample {
        self.stereo_spread
    }

    /// Current (smoothed, inertial) treble-horn rotation rate in Hz.
    #[must_use]
    pub fn horn_rate_hz(&self) -> Sample {
        self.horn.rate
    }

    /// Current (smoothed, inertial) bass-rotor rotation rate in Hz.
    #[must_use]
    pub fn drum_rate_hz(&self) -> Sample {
        self.drum.rate
    }

    /// Selects the target rotor speed; the rotors ramp to it with inertia.
    pub fn set_speed(&mut self, speed: LeslieSpeed) {
        self.speed = speed;
    }

    /// Sets the Doppler depth (clamped to `[0, MAX_DOPPLER_DEPTH]`).
    pub fn set_doppler_depth(&mut self, depth: Sample) {
        self.doppler_depth = clamp_unit_or(depth, 0.0, MAX_DOPPLER_DEPTH);
    }

    /// Sets the amplitude-tremolo depth (clamped to `[0, MAX_AM_DEPTH]`).
    pub fn set_am_depth(&mut self, depth: Sample) {
        self.am_depth = clamp_unit_or(depth, 0.0, MAX_AM_DEPTH);
    }

    /// Sets the stereo spread (clamped to `[0, 1]`).
    pub fn set_stereo_spread(&mut self, spread: Sample) {
        self.stereo_spread = clamp_unit_or(spread, 0.0, 1.0);
    }

    /// Sets the wet (processed) output gain.
    pub fn set_wet(&mut self, wet: Sample, ramp: Ramp) {
        if wet.is_finite() {
            self.wet.set_target(wet.clamp(0.0, 4.0), ramp);
        }
    }

    /// Sets the dry (unprocessed) output gain.
    pub fn set_dry(&mut self, dry: Sample, ramp: Ramp) {
        if dry.is_finite() {
            self.dry.set_target(dry.clamp(0.0, 4.0), ramp);
        }
    }
}

/// Returns `x` if finite, otherwise `0`.
fn finite(x: Sample) -> Sample {
    if x.is_finite() { x } else { 0.0 }
}

impl AudioNode for LeslieNode {
    fn process(&mut self, _ctx: &RenderContext, io: &mut ProcessIo<'_>) {
        let (input, output) = io.io(0, 0);
        let in_ch = input.channels();
        let out_ch = output.channels();
        let frames = output
            .active_frames()
            .min(input.active_frames())
            .min(self.max_block_frames);

        if in_ch == 0 || out_ch == 0 || frames == 0 {
            let available = in_ch.min(out_ch);
            for ch in 0..available {
                let src = input.channel(ch);
                let dst = output.channel_mut(ch);
                let n = frames.min(src.len()).min(dst.len());
                dst[..n].copy_from_slice(&src[..n]);
            }
            return;
        }

        // Downmix the input to the mono rotor feed.
        self.mono.set_active_frames(frames);
        {
            let inv = 1.0 / in_ch as Sample;
            let feed = self.mono.channel_mut(0);
            for (i, slot) in feed.iter_mut().enumerate().take(frames) {
                let mut sum = 0.0;
                for ch in 0..in_ch {
                    sum += finite(input.channel(ch)[i]);
                }
                *slot = sum * inv;
            }
        }

        // Split into the drum (low) and horn (high) bands.
        {
            let Self {
                crossover,
                mono,
                bands,
                ..
            } = self;
            crossover.process_block(mono, bands);
        }

        let sr = self.sample_rate as Sample;
        let horn_target = target_rate(self.speed, HORN_SLOW_HZ, HORN_FAST_HZ);
        let drum_target = target_rate(self.speed, DRUM_SLOW_HZ, DRUM_FAST_HZ);
        let spread = self.stereo_spread;
        let right_src = if in_ch >= 2 { 1 } else { 0 };
        let stereo_out = out_ch >= 2;

        for i in 0..frames {
            let low = self.bands[0].channel(0)[i];
            let high = self.bands[1].channel(0)[i];

            let (hl, hr) = self
                .horn
                .tick(high, self.am_depth, self.doppler_depth, sr, horn_target);
            let (dl, dr) = self
                .drum
                .tick(low, self.am_depth, self.doppler_depth, sr, drum_target);

            let wl = hl + dl;
            let wr = hr + dr;
            let mid = 0.5 * (wl + wr);
            let wet_l = mid + spread * (wl - mid);
            let wet_r = mid + spread * (wr - mid);

            let wet = self.wet.next_sample();
            let dry = self.dry.next_sample();
            let x0 = finite(input.channel(0)[i]);

            if stereo_out {
                let x1 = finite(input.channel(right_src)[i]);
                output.channel_mut(0)[i] = flush_denormal(dry * x0 + wet * wet_l);
                output.channel_mut(1)[i] = flush_denormal(dry * x1 + wet * wet_r);
            } else {
                output.channel_mut(0)[i] = flush_denormal(dry * x0 + wet * 0.5 * (wet_l + wet_r));
            }
        }

        // Pass any channels beyond the stereo pair through untouched.
        let passthrough = in_ch.min(out_ch);
        for ch in 2..passthrough {
            let src = input.channel(ch);
            let dst = output.channel_mut(ch);
            dst[..frames].copy_from_slice(&src[..frames]);
        }
    }

    fn reset(&mut self) {
        self.crossover.reset();
        self.mono.clear();
        for band in &mut self.bands {
            band.clear();
        }
        self.horn
            .reset(target_rate(self.speed, HORN_SLOW_HZ, HORN_FAST_HZ));
        self.drum
            .reset(target_rate(self.speed, DRUM_SLOW_HZ, DRUM_FAST_HZ));
        self.wet = Smoothed::new(self.wet.target());
        self.dry = Smoothed::new(self.dry.target());
    }

    fn latency_frames(&self) -> u32 {
        0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::buffer::{AudioBuffer, ChannelLayout};

    const SR: u32 = 48_000;

    fn ctx(frames: usize) -> RenderContext {
        RenderContext {
            sample_rate: SR,
            frames,
            playhead: 0,
        }
    }

    fn mono(frames: usize) -> AudioBuffer {
        AudioBuffer::new(ChannelLayout::Mono, frames)
    }

    fn stereo(frames: usize) -> AudioBuffer {
        AudioBuffer::new(ChannelLayout::Stereo, frames)
    }

    /// Fills a mono buffer with a unit-amplitude sine at `hz`.
    fn tone(frames: usize, hz: Sample) -> AudioBuffer {
        let mut buf = mono(frames);
        let dst = buf.channel_mut(0);
        for (i, s) in dst.iter_mut().enumerate() {
            *s = ops::sin(TAU * hz * i as Sample / SR as Sample);
        }
        buf
    }

    /// Runs `seconds` of silence through the node to let the rotors spin up.
    fn spin(node: &mut LeslieNode, seconds: Sample) {
        let block = node.max_block_frames();
        let total = (seconds * SR as Sample) as usize;
        let input = [mono(block)];
        let mut output = [mono(block)];
        let mut done = 0;
        while done < total {
            let mut io = ProcessIo::new(&input, &mut output);
            node.process(&ctx(block), &mut io);
            done += block;
        }
    }

    #[test]
    fn latency_is_zero() {
        let node = LeslieNode::new(SR, 256, LeslieParams::default());
        assert_eq!(node.latency_frames(), 0);
    }

    #[test]
    fn max_block_frames_getter_reports_build_size() {
        let node = LeslieNode::new(SR, 384, LeslieParams::default());
        assert_eq!(node.max_block_frames(), 384);
    }

    #[test]
    fn zero_max_block_is_clamped_up() {
        let node = LeslieNode::new(SR, 0, LeslieParams::default());
        assert_eq!(node.max_block_frames(), 1);
    }

    #[test]
    fn default_speed_is_chorale() {
        let node = LeslieNode::new(SR, 64, LeslieParams::default());
        assert_eq!(node.speed(), LeslieSpeed::Chorale);
        assert_eq!(LeslieSpeed::default(), LeslieSpeed::Chorale);
    }

    #[test]
    fn default_rates_start_near_slow() {
        let node = LeslieNode::new(SR, 64, LeslieParams::default());
        assert!((node.horn_rate_hz() - HORN_SLOW_HZ).abs() < 1.0e-4);
        assert!((node.drum_rate_hz() - DRUM_SLOW_HZ).abs() < 1.0e-4);
    }

    #[test]
    fn params_sanitised_clamps_and_defaults() {
        let p = LeslieParams {
            speed: LeslieSpeed::Tremolo,
            crossover_hz: Sample::NAN,
            doppler_depth: 5.0,
            am_depth: -1.0,
            stereo_spread: 2.0,
            wet: Sample::INFINITY,
            dry: -3.0,
        }
        .sanitised();
        assert_eq!(p.speed, LeslieSpeed::Tremolo);
        assert_eq!(p.crossover_hz, DEFAULT_CROSSOVER_HZ);
        assert_eq!(p.doppler_depth, MAX_DOPPLER_DEPTH);
        assert_eq!(p.am_depth, 0.0);
        assert_eq!(p.stereo_spread, 1.0);
        assert_eq!(p.wet, 1.0);
        assert_eq!(p.dry, 0.0);
    }

    #[test]
    fn setters_clamp_and_reject_non_finite() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());

        node.set_doppler_depth(9.0);
        assert_eq!(node.doppler_depth(), MAX_DOPPLER_DEPTH);
        node.set_doppler_depth(Sample::NAN);
        assert_eq!(node.doppler_depth(), 0.0);

        node.set_am_depth(9.0);
        assert_eq!(node.am_depth(), MAX_AM_DEPTH);
        node.set_am_depth(Sample::NEG_INFINITY);
        assert_eq!(node.am_depth(), 0.0);

        node.set_stereo_spread(9.0);
        assert_eq!(node.stereo_spread(), 1.0);
        node.set_stereo_spread(-9.0);
        assert_eq!(node.stereo_spread(), 0.0);
    }

    #[test]
    fn set_speed_updates_state() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());
        node.set_speed(LeslieSpeed::Tremolo);
        assert_eq!(node.speed(), LeslieSpeed::Tremolo);
        node.set_speed(LeslieSpeed::Brake);
        assert_eq!(node.speed(), LeslieSpeed::Brake);
    }

    #[test]
    fn silence_in_silence_out() {
        let mut node = LeslieNode::new(SR, 256, LeslieParams::default());
        let input = [stereo(256)];
        let mut output = [stereo(256)];
        let mut io = ProcessIo::new(&input, &mut output);
        node.process(&ctx(256), &mut io);
        for ch in 0..2 {
            for &y in output[0].channel(ch) {
                assert!(y.abs() < 1.0e-12, "silence produced {y}");
            }
        }
    }

    #[test]
    fn non_finite_input_stays_finite() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());
        let mut input = stereo(64);
        input.channel_mut(0)[0] = Sample::NAN;
        input.channel_mut(1)[1] = Sample::INFINITY;
        input.channel_mut(0)[2] = Sample::NEG_INFINITY;
        let inputs = [input];
        let mut output = [stereo(64)];
        let mut io = ProcessIo::new(&inputs, &mut output);
        node.process(&ctx(64), &mut io);
        for ch in 0..2 {
            for &y in output[0].channel(ch) {
                assert!(y.is_finite(), "non-finite output {y}");
            }
        }
    }

    #[test]
    fn zero_frames_is_safe() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());
        let mut input = stereo(64);
        input.set_active_frames(0);
        let mut out = stereo(64);
        out.set_active_frames(0);
        let inputs = [input];
        let mut output = [out];
        let mut io = ProcessIo::new(&inputs, &mut output);
        node.process(&ctx(0), &mut io);
    }

    #[test]
    fn dry_only_is_passthrough() {
        let params = LeslieParams {
            wet: 0.0,
            dry: 1.0,
            ..LeslieParams::default()
        };
        let mut node = LeslieNode::new(SR, 128, params);
        let mut input = stereo(128);
        for ch in 0..2 {
            for (i, s) in input.channel_mut(ch).iter_mut().enumerate() {
                *s = 0.01 * (i as Sample) * (1.0 + ch as Sample);
            }
        }
        let inputs = [input.clone()];
        let mut output = [stereo(128)];
        let mut io = ProcessIo::new(&inputs, &mut output);
        node.process(&ctx(128), &mut io);
        for ch in 0..2 {
            assert_eq!(output[0].channel(ch), inputs[0].channel(ch));
        }
    }

    #[test]
    fn wet_only_produces_energy() {
        let mut node = LeslieNode::new(SR, 4096, LeslieParams::default());
        let input = [tone(4096, 220.0)];
        let mut output = [stereo(4096)];
        let mut io = ProcessIo::new(&input, &mut output);
        node.process(&ctx(4096), &mut io);
        let energy: Sample = output[0]
            .channel(0)
            .iter()
            .skip(1024)
            .map(|v| v.abs())
            .sum();
        assert!(energy > 1.0, "wet rotation should have energy: {energy}");
    }

    #[test]
    fn tremolo_rate_exceeds_chorale_rate() {
        let params = LeslieParams {
            speed: LeslieSpeed::Tremolo,
            ..LeslieParams::default()
        };
        let mut node = LeslieNode::new(SR, 512, params);
        node.reset();
        spin(&mut node, 6.0);
        assert!(
            node.horn_rate_hz() > 6.0,
            "horn should reach tremolo rate: {}",
            node.horn_rate_hz()
        );
        assert!(
            node.drum_rate_hz() > 4.0,
            "drum should reach tremolo rate: {}",
            node.drum_rate_hz()
        );
        assert!(node.horn_rate_hz() > HORN_SLOW_HZ);
        assert!(node.drum_rate_hz() > DRUM_SLOW_HZ);
    }

    #[test]
    fn spin_up_is_gradual_and_drum_lags_horn() {
        let params = LeslieParams {
            speed: LeslieSpeed::Brake,
            ..LeslieParams::default()
        };
        let mut node = LeslieNode::new(SR, 512, params);
        assert!(node.horn_rate_hz().abs() < 1.0e-4);
        node.set_speed(LeslieSpeed::Tremolo);
        spin(&mut node, 0.3);
        let horn = node.horn_rate_hz();
        let drum = node.drum_rate_hz();
        // Both are spinning up but neither has reached full speed yet.
        assert!(horn > 0.0 && horn < HORN_FAST_HZ, "horn mid-ramp: {horn}");
        assert!(drum > 0.0 && drum < DRUM_FAST_HZ, "drum mid-ramp: {drum}");
        // The heavy drum accelerates more slowly than the light horn.
        assert!(horn > drum, "horn {horn} should lead drum {drum}");
    }

    #[test]
    fn stereo_spread_zero_collapses_to_identical_channels() {
        let params = LeslieParams {
            speed: LeslieSpeed::Tremolo,
            stereo_spread: 0.0,
            ..LeslieParams::default()
        };
        let mut node = LeslieNode::new(SR, 4096, params);
        let input = [tone(4096, 330.0)];
        let mut output = [stereo(4096)];
        let mut io = ProcessIo::new(&input, &mut output);
        node.process(&ctx(4096), &mut io);
        for i in 0..4096 {
            let l = output[0].channel(0)[i];
            let r = output[0].channel(1)[i];
            assert!((l - r).abs() < 1.0e-6, "spread 0 keeps L==R: {l} vs {r}");
        }
    }

    #[test]
    fn stereo_spread_one_decorrelates_channels() {
        let params = LeslieParams {
            speed: LeslieSpeed::Tremolo,
            stereo_spread: 1.0,
            ..LeslieParams::default()
        };
        let mut node = LeslieNode::new(SR, 4096, params);
        let input = [tone(4096, 330.0)];
        let mut output = [stereo(4096)];
        let mut io = ProcessIo::new(&input, &mut output);
        node.process(&ctx(4096), &mut io);
        let diff: Sample = (1024..4096)
            .map(|i| (output[0].channel(0)[i] - output[0].channel(1)[i]).abs())
            .sum();
        assert!(diff > 1.0, "spread 1 should decorrelate L/R: {diff}");
    }

    #[test]
    fn mono_output_sums_the_two_legs() {
        let params = LeslieParams {
            speed: LeslieSpeed::Tremolo,
            dry: 0.0,
            wet: 1.0,
            ..LeslieParams::default()
        };
        let mut stereo_node = LeslieNode::new(SR, 2048, params);
        let mut mono_node = LeslieNode::new(SR, 2048, params);

        let input = [tone(2048, 440.0)];
        let mut stereo_out = [stereo(2048)];
        let mut mono_out = [mono(2048)];
        {
            let mut io = ProcessIo::new(&input, &mut stereo_out);
            stereo_node.process(&ctx(2048), &mut io);
        }
        {
            let mut io = ProcessIo::new(&input, &mut mono_out);
            mono_node.process(&ctx(2048), &mut io);
        }
        for i in 0..2048 {
            let expected = 0.5 * (stereo_out[0].channel(0)[i] + stereo_out[0].channel(1)[i]);
            let got = mono_out[0].channel(0)[i];
            assert!((got - expected).abs() < 1.0e-5, "frame {i}: {got} vs {expected}");
        }
    }

    #[test]
    fn surplus_channels_pass_through() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());
        let mut input = AudioBuffer::new(ChannelLayout::Quad, 64);
        for (i, s) in input.channel_mut(2).iter_mut().enumerate() {
            *s = 0.1 * i as Sample;
        }
        for (i, s) in input.channel_mut(3).iter_mut().enumerate() {
            *s = -0.2 * i as Sample;
        }
        let inputs = [input.clone()];
        let mut output = [AudioBuffer::new(ChannelLayout::Quad, 64)];
        let mut io = ProcessIo::new(&inputs, &mut output);
        node.process(&ctx(64), &mut io);
        assert_eq!(output[0].channel(2), inputs[0].channel(2));
        assert_eq!(output[0].channel(3), inputs[0].channel(3));
    }

    #[test]
    fn reset_clears_tail() {
        let mut node = LeslieNode::new(SR, 512, LeslieParams::default());
        let input = [tone(512, 500.0)];
        let mut output = [stereo(512)];
        {
            let mut io = ProcessIo::new(&input, &mut output);
            node.process(&ctx(512), &mut io);
        }
        node.reset();
        let silence = [stereo(512)];
        let mut output2 = [stereo(512)];
        let mut io2 = ProcessIo::new(&silence, &mut output2);
        node.process(&ctx(512), &mut io2);
        for ch in 0..2 {
            for &y in output2[0].channel(ch) {
                assert!(y.abs() < 1.0e-9, "tail not cleared: {y}");
            }
        }
    }

    #[test]
    fn wet_and_dry_setters_ramp_within_bounds() {
        let mut node = LeslieNode::new(SR, 64, LeslieParams::default());
        node.set_wet(2.0, Ramp::Immediate);
        node.set_dry(0.5, Ramp::Immediate);
        node.set_wet(Sample::NAN, Ramp::Immediate);
        node.set_dry(Sample::INFINITY, Ramp::Immediate);
        // A block should still render finite output after the setters.
        let input = [tone(64, 300.0)];
        let mut output = [stereo(64)];
        let mut io = ProcessIo::new(&input, &mut output);
        node.process(&ctx(64), &mut io);
        for ch in 0..2 {
            for &y in output[0].channel(ch) {
                assert!(y.is_finite(), "non-finite after setters: {y}");
            }
        }
    }
}
