//! Deterministic code generation from the surface schema (design doc §17.5, S2).
//!
//! Stage S1 only *parity-checked* the hand-written layout against this schema.
//! Stage S2 flips the dependency: the schema becomes the generator. The two
//! emitters here turn the validated [`SurfaceSchema`] into the exact source text
//! of two previously hand-maintained twins:
//!
//! * [`emit_wesl_unpack`] — the GPU word-heap decoder
//!   (`prism_render_scene/src/shaders/material_unpack.wesl`): the lobe-bit
//!   constants, the neutral surface, `prism_packed_word_count` and
//!   `prism_unpack_surface`.
//! * [`emit_rust_layout`] — the CPU layout constants and lobe table consumed by
//!   `prism_render_material::surface` (`SURFACE_CORE_WORDS`, `SURFACE_MAX_WORDS`,
//!   the canonical [`SURFACE_LOBES`](crate) table, …).
//!
//! Both emitters are pure functions of the schema, so the generated files are
//! committed and a freshness test (`regenerate == committed`) turns any drift
//! into a red build. Byte parity of the hand-written `surface.rs` struct image
//! is still guarded by the S1 gate in `prism_render_material`, so the schema →
//! Rust layout → WESL chain is transitively byte-exact.
//!
//! The emitters are intentionally *textual*: they never shell out to `rustfmt`
//! or a WESL formatter, so output is reproducible on any host with no toolchain
//! beyond this crate. The layout they encode is small and regular (a 4-word
//! lobe quantum, low-bit-first), which keeps the generated text review-friendly.

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::fmt::Write as _;

use crate::{FieldType, SurfaceSchema};

/// A machine-readable banner marking a file as generated. Both emitters start
/// with it so humans and tooling can detect a hand edit at a glance.
const GENERATED_BANNER_LINE: &str =
    "DO NOT EDIT — generated by `prism-material-codegen` from schema/surface.toml.";

/// The exact command that regenerates every product; embedded in each banner.
const REGEN_COMMAND: &str =
    "cargo run -p prism_material_schema --bin prism-material-codegen -- write";

/// Format an `f32` default as a source float literal with a mandatory decimal
/// point, identical for both WESL and Rust (`1 -> 1.0`, `0.1 -> 0.1`). A plain
/// `{}` can drop the point (`1`), which is a type error in WESL `f32` context,
/// so this guarantees one.
fn float_literal(v: f32) -> String {
    let s = format!("{v:?}");
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{s}.0")
    }
}

/// Assert the schema uses a single uniform lobe word count. Both twins encode
/// the stride as one constant (`PRISM_SURFACE_LOBE_WORDS` / `SURFACE_LOBE_WORDS`)
/// and advance a cursor by it per present lobe; a non-uniform schema would make
/// that constant a lie. The schema validator already fixes 4-word lobes, so this
/// is a defensive guard for a future schema change, surfaced as a clear panic in
/// the generator rather than silently wrong code.
fn uniform_lobe_words(schema: &SurfaceSchema) -> u32 {
    let mut words: Option<u32> = None;
    for lobe in &schema.lobes {
        match words {
            None => words = Some(lobe.words),
            Some(w) => assert_eq!(
                w, lobe.words,
                "codegen requires a uniform lobe word count; lobe `{}` has {} (expected {})",
                lobe.id, lobe.words, w
            ),
        }
    }
    words.unwrap_or(0)
}

/// All defined lobe bits OR-ed together (`(1 << count) - 1` for contiguous
/// slots, computed from the actual slots so a sparse registry still works).
fn all_lobe_bits(schema: &SurfaceSchema) -> u32 {
    schema
        .lobes
        .iter()
        .fold(0u32, |acc, l| acc | (1u32 << l.registry_slot))
}

// ---------------------------------------------------------------------------
// WESL emitter
// ---------------------------------------------------------------------------

/// Emit the full `material_unpack.wesl` module from the schema.
///
/// The output is byte-stable and ends with a trailing newline. It defines the
/// per-lobe bit constants, the core/lobe word counts and worst-case word count,
/// `prism_packed_word_count`, `prism_neutral_surface`, and `prism_unpack_surface`
/// — the exact public surface the five scene consumers import.
#[must_use]
pub fn emit_wesl_unpack(schema: &SurfaceSchema) -> String {
    let core_words = schema.core.words;
    let lobe_words = uniform_lobe_words(schema);
    let count = schema.lobe_count();
    let max_words = schema.packed_len_words(all_lobe_bits(schema));
    let lobes = schema.canonical_lobes();

    let mut o = String::with_capacity(4096);

    // --- header -----------------------------------------------------------
    let _ = writeln!(o, "//! {GENERATED_BANNER_LINE}");
    let _ = writeln!(o, "//! Regenerate: {REGEN_COMMAND}");
    o.push_str("//!\n");
    o.push_str(
        "//! Variable-length material parameter word-heap decode (design doc §3.3 / §17.5).\n",
    );
    o.push_str("//!\n");
    o.push_str("//! Byte-exact WESL twin of\n");
    o.push_str(
        "//! `prism_render_material::SurfaceParameterBlock::unpack(mask, words).to_full()`:\n",
    );
    let _ = writeln!(
        o,
        "//! the scene packs each surface as an über-BSDF core ({core_words} words) followed by"
    );
    o.push_str(
        "//! only the lobes named in `lobe_mask`, written low bit first. Readers gather the\n",
    );
    o.push_str(
        "//! material's `parameter_size / 4` words out of the shared `array<u32>` heap into a\n",
    );
    let _ = writeln!(
        o,
        "//! fixed `array<u32, {max_words}>` (the fully-loaded worst case) and expand them back to"
    );
    o.push_str(
        "//! a full `PrismSurfaceParameters`, filling absent lobes with neutral defaults.\n",
    );
    o.push_str("//!\n");
    o.push_str(
        "//! Kept as a single generated source so all five consumers (opaque, transparent,\n",
    );
    o.push_str("//! visibility, shading_resolve, ssr_repack) decode identically.\n");
    o.push('\n');
    o.push_str("import prism_render_scene::shaders::material::PrismSurfaceParameters;\n");
    o.push('\n');

    // --- lobe bit constants ----------------------------------------------
    // Build every declaration first, then pad to the widest so the trailing
    // `// 1 << n` comments align into one column.
    let all_bits = all_lobe_bits(schema);
    let mut decls: Vec<(String, String)> = Vec::new();
    for lobe in &lobes {
        let bit = 1u32 << lobe.registry_slot;
        decls.push((
            format!("const PRISM_LOBE_{}: u32 = {bit}u;", lobe.mask_const),
            format!("// 1 << {}", lobe.registry_slot),
        ));
    }
    decls.push((
        format!("const PRISM_LOBE_ALL: u32 = {all_bits}u;"),
        format!("// (1 << {count}) - 1"),
    ));
    let decl_width = decls.iter().map(|(d, _)| d.len()).max().unwrap_or(0) + 1;
    for (decl, comment) in &decls {
        let _ = writeln!(o, "{decl:<decl_width$}{comment}");
    }
    o.push('\n');

    // --- word counts ------------------------------------------------------
    let _ = writeln!(o, "const PRISM_SURFACE_CORE_WORDS: u32 = {core_words}u;");
    let _ = writeln!(o, "const PRISM_SURFACE_LOBE_WORDS: u32 = {lobe_words}u;");
    let _ = writeln!(
        o,
        "/// Fully-loaded worst case: core + every lobe ({core_words} + {count}*{lobe_words})."
    );
    let _ = writeln!(o, "const PRISM_SURFACE_MAX_WORDS: u32 = {max_words}u;");
    o.push('\n');

    // --- prism_packed_word_count -----------------------------------------
    o.push_str("/// Packed word count for a mask: core plus the uniform lobe stride per present\n");
    o.push_str("/// lobe. Mirrors `SurfaceParameterBlock::packed_len_words`.\n");
    o.push_str("fn prism_packed_word_count(lobe_mask: u32) -> u32 {\n");
    o.push_str("    return PRISM_SURFACE_CORE_WORDS\n");
    o.push_str("        + countOneBits(lobe_mask & PRISM_LOBE_ALL) * PRISM_SURFACE_LOBE_WORDS;\n");
    o.push_str("}\n\n");

    // --- prism_neutral_surface -------------------------------------------
    o.push_str(
        "/// The canonical neutral surface (`GpuSurfaceParameters::default`): the base an\n",
    );
    o.push_str(
        "/// absent lobe decodes back to, and the value returned when a material's declared\n",
    );
    o.push_str("/// range does not fit the bound heap.\n");
    o.push_str("fn prism_neutral_surface() -> PrismSurfaceParameters {\n");
    o.push_str("    var s: PrismSurfaceParameters;\n");
    for field in &schema.core.fields {
        emit_wesl_default(&mut o, field);
    }
    for lobe in &lobes {
        for field in &lobe.fields {
            emit_wesl_default(&mut o, field);
        }
    }
    o.push_str("    return s;\n");
    o.push_str("}\n\n");

    // --- prism_unpack_surface --------------------------------------------
    o.push_str(
        "/// Expand `words` (a material's packed block, low words first) into a full surface\n",
    );
    o.push_str(
        "/// using `lobe_mask`. Words beyond the packed length are ignored; absent lobes keep\n",
    );
    o.push_str("/// their neutral default. Byte-exact twin of\n");
    o.push_str("/// `SurfaceParameterBlock::unpack(mask, words).to_full()`.\n");
    let _ = writeln!(
        o,
        "fn prism_unpack_surface(words: array<u32, {max_words}>, lobe_mask: u32) -> PrismSurfaceParameters {{"
    );
    o.push_str("    var w = words;\n");
    o.push_str("    var s = prism_neutral_surface();\n");
    o.push('\n');
    let pad_slots: Vec<u32> = schema
        .core
        .fields
        .iter()
        .filter(|f| f.ty == FieldType::Pad)
        .map(|f| f.pack_slot)
        .collect();
    if pad_slots.is_empty() {
        let _ = writeln!(o, "    // Core ({core_words} words).");
    } else {
        let words: Vec<String> = pad_slots.iter().map(|n| format!("w[{n}]")).collect();
        let _ = writeln!(
            o,
            "    // Core ({core_words} words); {} are padding.",
            words.join(" and ")
        );
    }
    for field in &schema.core.fields {
        emit_wesl_core_read(&mut o, field);
    }
    o.push('\n');
    o.push_str("    // Present lobes, canonical low-bit-first order, uniform stride each.\n");
    o.push_str("    var cursor: u32 = PRISM_SURFACE_CORE_WORDS;\n");
    for lobe in &lobes {
        let _ = writeln!(
            o,
            "    if (lobe_mask & PRISM_LOBE_{}) != 0u {{",
            lobe.mask_const
        );
        for field in &lobe.fields {
            emit_wesl_lobe_read(&mut o, field);
        }
        o.push_str("        cursor += PRISM_SURFACE_LOBE_WORDS;\n");
        o.push_str("    }\n");
    }
    o.push_str("    return s;\n");
    o.push_str("}\n");

    o
}

/// `w[<n>]` for a core read or `w[cursor + <n>u]` / `w[cursor]` for a lobe read.
fn word_index(base_is_cursor: bool, offset: u32) -> String {
    if base_is_cursor {
        if offset == 0 {
            "w[cursor]".to_string()
        } else {
            format!("w[cursor + {offset}u]")
        }
    } else {
        format!("w[{offset}]")
    }
}

/// Emit one neutral-default assignment, skipping pads.
fn emit_wesl_default(o: &mut String, field: &crate::Field) {
    if field.ty == FieldType::Pad {
        return;
    }
    let target = field.surface_field();
    let comps = field.default.components();
    match field.ty {
        FieldType::Vec4f => {
            let v: Vec<String> = comps.iter().map(|c| float_literal(*c)).collect();
            let _ = writeln!(
                o,
                "    s.{target} = vec4<f32>({}, {}, {}, {});",
                v[0], v[1], v[2], v[3]
            );
        }
        FieldType::F32 | FieldType::F16 => {
            let _ = writeln!(o, "    s.{target} = {};", float_literal(comps[0]));
        }
        FieldType::Pad => unreachable!(),
    }
}

/// Emit one core-field decode (`base = schema pack_slot`, no cursor), skipping pads.
fn emit_wesl_core_read(o: &mut String, field: &crate::Field) {
    emit_wesl_read(o, field, false, field.pack_slot);
}

/// Emit one lobe-field decode relative to `cursor`, skipping pads.
fn emit_wesl_lobe_read(o: &mut String, field: &crate::Field) {
    // Lobe reads are indented one extra level (inside the `if` block).
    let mut tmp = String::new();
    emit_wesl_read(&mut tmp, field, true, field.pack_slot);
    for line in tmp.lines() {
        let _ = writeln!(o, "    {line}");
    }
}

fn emit_wesl_read(o: &mut String, field: &crate::Field, base_is_cursor: bool, slot: u32) {
    if field.ty == FieldType::Pad {
        return;
    }
    let target = field.surface_field();
    match field.ty {
        FieldType::Vec4f => {
            let c0 = word_index(base_is_cursor, slot);
            let c1 = word_index(base_is_cursor, slot + 1);
            let c2 = word_index(base_is_cursor, slot + 2);
            let c3 = word_index(base_is_cursor, slot + 3);
            let _ = writeln!(o, "    s.{target} = vec4<f32>(");
            let _ = writeln!(o, "        bitcast<f32>({c0}),");
            let _ = writeln!(o, "        bitcast<f32>({c1}),");
            let _ = writeln!(o, "        bitcast<f32>({c2}),");
            let _ = writeln!(o, "        bitcast<f32>({c3}),");
            let _ = writeln!(o, "    );");
        }
        FieldType::F32 | FieldType::F16 => {
            let idx = word_index(base_is_cursor, slot);
            let _ = writeln!(o, "    s.{target} = bitcast<f32>({idx});");
        }
        FieldType::Pad => {}
    }
}

// ---------------------------------------------------------------------------
// Rust layout emitter
// ---------------------------------------------------------------------------

/// Emit the generated Rust layout module consumed by
/// `prism_render_material::surface` (constants + the canonical lobe table).
///
/// The output is byte-stable and ends with a trailing newline. It deliberately
/// contains *no behaviour*, only the layout facts the hand-written typed structs
/// are checked against: word counts, the lobe count, the worst-case word count,
/// and the canonical `(id, mask_const, registry_slot, words)` table in pack
/// order.
#[must_use]
pub fn emit_rust_layout(schema: &SurfaceSchema) -> String {
    let core_words = schema.core.words;
    let lobe_words = uniform_lobe_words(schema);
    let count = schema.lobe_count();
    let max_words = schema.packed_len_words(all_lobe_bits(schema));
    let lobes = schema.canonical_lobes();

    let mut o = String::with_capacity(2048);
    let _ = writeln!(o, "// {GENERATED_BANNER_LINE}");
    let _ = writeln!(o, "// Regenerate: {REGEN_COMMAND}");
    o.push_str("//! Generated über-BSDF surface layout facts (design doc §17.5, stage S2).\n");
    o.push_str("//!\n");
    o.push_str("//! The single declarative source of truth is `schema/surface.toml` in\n");
    o.push_str("//! `prism_material_schema`. This module exports the layout constants and the\n");
    o.push_str(
        "//! canonical lobe table so the hand-written typed structs in `surface.rs` can be\n",
    );
    o.push_str(
        "//! checked against — never diverge from — the schema. Edit the schema, not this.\n",
    );
    o.push('\n');
    o.push_str("/// Number of `u32` words in the always-present surface core.\n");
    let _ = writeln!(o, "pub const SURFACE_CORE_WORDS: usize = {core_words};");
    o.push_str("/// Number of `u32` words in every uniform per-lobe quantum.\n");
    let _ = writeln!(o, "pub const SURFACE_LOBE_WORDS: usize = {lobe_words};");
    o.push_str("/// Number of defined optional lobes (equals `LobeMask::COUNT`).\n");
    let _ = writeln!(o, "pub const SURFACE_LOBE_COUNT: u32 = {count};");
    o.push_str(
        "/// Fully-loaded worst case: core plus every lobe. The WESL decoder gathers into\n",
    );
    o.push_str("/// an `array<u32, SURFACE_MAX_WORDS>`.\n");
    let _ = writeln!(o, "pub const SURFACE_MAX_WORDS: usize = {max_words};");
    o.push('\n');
    o.push_str("/// One optional lobe's generated identity, in canonical pack order.\n");
    o.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    o.push_str("pub struct LobeLayout {\n");
    o.push_str("    /// Human-facing lobe id (schema `id`).\n");
    o.push_str("    pub id: &'static str,\n");
    o.push_str("    /// Matching `LobeMask` associated-constant name.\n");
    o.push_str("    pub mask_const: &'static str,\n");
    o.push_str("    /// Immutable `LobeMask` bit index and low-bit-first pack order.\n");
    o.push_str("    pub registry_slot: u32,\n");
    o.push_str("    /// `u32` word footprint of the lobe.\n");
    o.push_str("    pub words: usize,\n");
    o.push_str("}\n\n");
    o.push_str("/// The defined lobes in canonical low-bit-first pack order.\n");
    let _ = writeln!(o, "pub const SURFACE_LOBES: [LobeLayout; {count}] = [");
    // Emit the rustfmt-canonical multi-line struct literal (rustfmt's default
    // `struct_lit_width = 18` expands these named-field literals), so the
    // committed file is simultaneously codegen output *and* `cargo fmt`-stable
    // and the freshness byte-compare never fights the formatter.
    for lobe in &lobes {
        o.push_str("    LobeLayout {\n");
        let _ = writeln!(o, "        id: {:?},", lobe.id);
        let _ = writeln!(o, "        mask_const: {:?},", lobe.mask_const);
        let _ = writeln!(o, "        registry_slot: {},", lobe.registry_slot);
        let _ = writeln!(o, "        words: {},", lobe.words);
        o.push_str("    },\n");
    }
    o.push_str("];\n");
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::surface_schema;

    #[test]
    fn float_literal_always_has_a_point() {
        assert_eq!(float_literal(1.0), "1.0");
        assert_eq!(float_literal(0.0), "0.0");
        assert_eq!(float_literal(0.5), "0.5");
        assert_eq!(float_literal(1.5), "1.5");
        assert_eq!(float_literal(0.1), "0.1");
    }

    #[test]
    fn wesl_emitter_is_deterministic() {
        let schema = surface_schema();
        assert_eq!(emit_wesl_unpack(&schema), emit_wesl_unpack(&schema));
    }

    #[test]
    fn rust_emitter_is_deterministic() {
        let schema = surface_schema();
        assert_eq!(emit_rust_layout(&schema), emit_rust_layout(&schema));
    }

    #[test]
    fn wesl_exposes_the_consumer_api() {
        let wesl = emit_wesl_unpack(&surface_schema());
        for needle in [
            "fn prism_unpack_surface(words: array<u32, 40>, lobe_mask: u32)",
            "fn prism_packed_word_count(lobe_mask: u32) -> u32",
            "fn prism_neutral_surface() -> PrismSurfaceParameters",
            "const PRISM_SURFACE_MAX_WORDS: u32 = 40u;",
            "import prism_render_scene::shaders::material::PrismSurfaceParameters;",
        ] {
            assert!(wesl.contains(needle), "generated WESL missing `{needle}`");
        }
        // The face lobe uses the namespaced fat-struct field.
        assert!(wesl.contains("s.face_softness = bitcast<f32>(w[cursor]);"));
        // Both twins end with a trailing newline.
        assert!(wesl.ends_with('\n'));
    }

    #[test]
    fn wesl_neutral_matches_schema_defaults() {
        let wesl = emit_wesl_unpack(&surface_schema());
        // Spot-check a few defaults the hand-written file is known to carry.
        assert!(wesl.contains("s.base_color = vec4<f32>(1.0, 1.0, 1.0, 1.0);"));
        assert!(wesl.contains("s.index_of_refraction = 1.5;"));
        assert!(wesl.contains("s.face_softness = 0.1;"));
        assert!(wesl.contains("s.perceptual_roughness = 0.5;"));
    }

    #[test]
    fn rust_layout_exposes_constants_and_table() {
        let rust = emit_rust_layout(&surface_schema());
        for needle in [
            "pub const SURFACE_CORE_WORDS: usize = 12;",
            "pub const SURFACE_LOBE_WORDS: usize = 4;",
            "pub const SURFACE_LOBE_COUNT: u32 = 7;",
            "pub const SURFACE_MAX_WORDS: usize = 40;",
            "pub const SURFACE_LOBES: [LobeLayout; 7] = [",
            "    LobeLayout {\n        id: \"emission\",\n        mask_const: \"EMISSION\",\n        registry_slot: 0,\n        words: 4,\n    },",
            "    LobeLayout {\n        id: \"face\",\n        mask_const: \"FACE\",\n        registry_slot: 6,\n        words: 4,\n    },",
        ] {
            assert!(rust.contains(needle), "generated Rust missing `{needle}`");
        }
        assert!(rust.ends_with('\n'));
    }
}
