//! Temporal reconstruction feature-boundary contract (`DLSS`/`FSR`/`XeSS`-class).
//!
//! Temporal upsampling is the AAA technique that renders the scene at a
//! fraction of the display resolution and reconstructs a full-resolution image
//! by accumulating jittered history across frames. This module owns the
//! `CPU`-verifiable *contract* for that subsystem: the settings the host feeds
//! a reconstructor, the deterministic sub-pixel jitter schedule, the
//! render/display resolution derivation and pixel mapping, and the rule that
//! decides when accumulated history must be thrown away.
//!
//! The pieces are split across sibling modules:
//!
//! 1. **Settings** ([`TemporalUpscaleSettings`]) — the render scale, sharpening
//!    amount, and the set of scene changes that invalidate history. Validation
//!    clamps every field into a safe range and resolves `NaN` deterministically.
//! 2. **Jitter** ([`jitter`]) — the Halton `(2, 3)` sub-pixel camera-jitter
//!    schedule, generated by integer radical inversion (no transcendental
//!    functions) so the `CPU` reference and a future `GPU` kernel agree exactly.
//! 3. **Resolution** ([`resolution`]) — integer render-dimension derivation and
//!    the render <-> display pixel / clip-space mapping.
//!
//! The `GPU` reconstruction kernel and its `WESL` shader codegen are out of
//! scope for this contract layer and are pending the `GPU` backend; the types
//! here fix the exact numeric behavior those kernels must reproduce.

use crate::history::InvalidationMask;

pub mod jitter;
pub mod resolution;

pub use jitter::{radical_inverse, JitterSequence};
pub use resolution::UpscaleResolution;

/// Minimum render scale the contract will clamp to.
///
/// A scale of `0` would render nothing; this floor (roughly "ultra
/// performance" territory) keeps a non-degenerate render target while still
/// allowing aggressive upsampling.
pub const MIN_RENDER_SCALE: f32 = 0.25;

/// Maximum render scale the contract will clamp to.
///
/// The reconstructor's domain is `(0, 1]`: at `1.0` it renders natively, and
/// supersampling (`> 1.0`) is a different feature, so requests above native are
/// clamped back to `1.0`.
pub const MAX_RENDER_SCALE: f32 = 1.0;

/// The safe render scale substituted for a `NaN` request: full native
/// resolution, which never introduces reconstruction artifacts.
pub const SAFE_RENDER_SCALE: f32 = 1.0;

/// Validates and clamps a requested render scale into `[MIN_RENDER_SCALE, 1.0]`.
///
/// A `NaN` request cannot be ordered against the bounds, so it is resolved to
/// [`SAFE_RENDER_SCALE`] (native) first; finite requests are then clamped into
/// the closed `(0, 1]` working range. The `NaN` branch is written explicitly to
/// avoid the `manual_clamp` lint and to keep the fallback deterministic.
#[must_use]
pub fn validate_render_scale(scale: f32) -> f32 {
    if scale.is_nan() {
        // Resolve the un-orderable case explicitly first, then clamp the now
        // finite value; `clamp` is safe here because the input is finite and
        // the bounds are ordered compile-time constants.
        SAFE_RENDER_SCALE
    } else {
        scale.clamp(MIN_RENDER_SCALE, MAX_RENDER_SCALE)
    }
}

/// Clamps a sharpening amount into `[0, 1]`, resolving `NaN` to `0` (off).
///
/// Post-reconstruction sharpening is a normalized `[0, 1]` knob; a `NaN`
/// disables it rather than propagating. The `NaN` check precedes the range
/// checks so the lint-safe form also gives a deterministic fallback.
#[must_use]
pub fn clamp_sharpness(sharpness: f32) -> f32 {
    if sharpness.is_nan() || sharpness < 0.0 {
        0.0
    } else if sharpness > 1.0 {
        1.0
    } else {
        sharpness
    }
}

/// Host-supplied configuration for one temporal-reconstruction view.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TemporalUpscaleSettings {
    /// Fraction of the display resolution the scene is rendered at, in
    /// `(0, 1]`. Values are only trustworthy after [`Self::validated`].
    pub render_scale: f32,
    /// Post-reconstruction sharpening amount in `[0, 1]`.
    pub sharpness: f32,
    /// The set of scene changes that invalidate accumulated history for this
    /// view. When the frame's actual invalidation mask intersects this set the
    /// history must be discarded.
    pub invalidation_dependencies: InvalidationMask,
}

impl TemporalUpscaleSettings {
    /// Returns a copy with every field validated and clamped into range.
    ///
    /// `render_scale` goes through [`validate_render_scale`] and `sharpness`
    /// through [`clamp_sharpness`]; the invalidation set is copied unchanged.
    #[must_use]
    pub fn validated(self) -> Self {
        Self {
            render_scale: validate_render_scale(self.render_scale),
            sharpness: clamp_sharpness(self.sharpness),
            invalidation_dependencies: self.invalidation_dependencies,
        }
    }

    /// Derives the render/display resolution pair for a display size.
    ///
    /// The render scale is validated as part of the derivation, so callers may
    /// pass an unvalidated settings value here directly.
    #[must_use]
    pub fn resolution(self, display_width: u32, display_height: u32) -> UpscaleResolution {
        UpscaleResolution::from_display(display_width, display_height, self.render_scale)
    }

    /// Returns `true` when a frame's actual invalidation `mask` requires this
    /// view's history to be discarded.
    ///
    /// History is invalidated when the frame's changes intersect the set this
    /// view declared it depends on.
    #[must_use]
    pub fn history_invalidated(self, mask: InvalidationMask) -> bool {
        self.invalidation_dependencies.intersects(mask)
    }
}

impl Default for TemporalUpscaleSettings {
    fn default() -> Self {
        Self {
            render_scale: 1.0,
            sharpness: 0.0,
            invalidation_dependencies: InvalidationMask(u32::MAX),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn approx(a: f32, b: f32) -> bool {
        (a - b).abs() <= 1e-6
    }

    #[test]
    fn render_scale_clamps_into_range() {
        assert!(approx(validate_render_scale(0.5), 0.5));
        assert!(approx(validate_render_scale(2.0), MAX_RENDER_SCALE));
        assert!(approx(validate_render_scale(0.0), MIN_RENDER_SCALE));
        assert!(approx(validate_render_scale(-1.0), MIN_RENDER_SCALE));
    }

    #[test]
    fn render_scale_nan_falls_back_to_native() {
        assert!(approx(validate_render_scale(f32::NAN), SAFE_RENDER_SCALE));
    }

    #[test]
    fn sharpness_clamps_and_resolves_nan() {
        assert!(approx(clamp_sharpness(0.3), 0.3));
        assert!(approx(clamp_sharpness(-0.5), 0.0));
        assert!(approx(clamp_sharpness(5.0), 1.0));
        assert!(approx(clamp_sharpness(f32::NAN), 0.0));
    }

    #[test]
    fn validated_settings_are_in_range() {
        let s = TemporalUpscaleSettings {
            render_scale: f32::NAN,
            sharpness: 9.0,
            invalidation_dependencies: InvalidationMask::CAMERA_CUT,
        }
        .validated();
        assert!(approx(s.render_scale, SAFE_RENDER_SCALE));
        assert!(approx(s.sharpness, 1.0));
        assert_eq!(s.invalidation_dependencies, InvalidationMask::CAMERA_CUT);
    }

    #[test]
    fn history_invalidation_respects_dependencies() {
        let s = TemporalUpscaleSettings {
            render_scale: 0.5,
            sharpness: 0.0,
            invalidation_dependencies: InvalidationMask::CAMERA_CUT,
        };
        // A camera cut intersects the declared dependency -> invalidate.
        assert!(s.history_invalidated(InvalidationMask::CAMERA_CUT));
        // An unrelated change does not.
        assert!(!s.history_invalidated(InvalidationMask::EXPOSURE));
    }

    #[test]
    fn default_view_depends_on_everything() {
        let s = TemporalUpscaleSettings::default();
        assert!(s.history_invalidated(InvalidationMask::SCENE));
        assert!(s.history_invalidated(InvalidationMask::LIGHTING));
    }

    #[test]
    fn resolution_uses_validated_scale() {
        let s = TemporalUpscaleSettings {
            render_scale: 0.5,
            sharpness: 0.0,
            invalidation_dependencies: InvalidationMask::default(),
        };
        let r = s.resolution(1920, 1080);
        assert_eq!(r.render_width(), 960);
        assert_eq!(r.render_height(), 540);
    }
}
