//! Multiple-scattering energy data for the rough dielectric interface.
//!
//! A single-scatter microfacet dielectric (frosted glass, see
//! [`crate::reference_pt::rough_dielectric`]) only transports light that
//! reflects or refracts off exactly one micro-facet. At high roughness a large
//! fraction of the energy instead bounces several times between facets before
//! escaping, and the single-scatter Smith masking term `G2` silently discards
//! all of it, so rough glass and water render visibly too dark. This module
//! supplies the directional-albedo data needed to add that energy back with a
//! Turquin-style multiplicative compensation
//! (E. Turquin, "Practical multiple scattering compensation for microfacet
//! models", 2019).
//!
//! Two quantities drive the compensation:
//!
//! - the *single-scatter directional albedo* `E(eta, alpha, mu)`, i.e. the
//!   total reflected-plus-transmitted energy a lossless
//!   (`reflectance = transmittance = 1`) rough dielectric sends out for a view
//!   cosine `mu` at relative index `eta` and `GGX` width `alpha`. This is baked
//!   into the trilinear [`ALBEDO`] table and regenerated/validated against a
//!   fresh `Monte Carlo` furnace integral by [`tests::lut_matches_monte_carlo`];
//! - the *smooth ceiling* `E_smooth(eta, mu)`, the alpha to zero limit of the
//!   same albedo. Because `PBRT` v4's radiance-mode transmitted lobe carries the
//!   `1 / eta^2` solid-angle compression, a lossless smooth interface does not
//!   integrate to one but to `R + (1 - R) / eta^2`, where `R` is the smooth
//!   `Fresnel` reflectance. The compensation restores the masking loss up to
//!   this physically correct ceiling rather than to one, so it never injects
//!   the energy the radiance measure legitimately removes.
//!
//! The base rough dielectric orients its shading frame toward the viewer and
//! applies the relative index as-is, so its directional albedo is identical for
//! exterior and interior incidence; a single table therefore covers both sides
//! of the interface. Lookups use only multiplies, adds, a clamp and a `sqrt`,
//! honouring the crate's determinism policy (no `sin`/`cos`/`exp`/`pow`).

use super::dielectric::fresnel_dielectric;

/// Number of relative-index nodes along the `eta` axis of [`ALBEDO`].
pub const ETA_SIZE: usize = 6;
/// Number of `GGX` width nodes along the `alpha` axis of [`ALBEDO`].
pub const ALPHA_SIZE: usize = 8;
/// Number of view-cosine nodes along the `mu` axis of [`ALBEDO`].
pub const MU_SIZE: usize = 8;

/// Smallest relative index covered by the baked table.
pub const ETA_MIN: f32 = 1.1;
/// Largest relative index covered by the baked table.
pub const ETA_MAX: f32 = 2.5;

/// Baked lossless single-scatter directional albedo `E(eta, alpha, mu)`.
///
/// The outer index selects the `eta` node, the middle index the `alpha` node,
/// the inner index the `mu` (view cosine) node. The `alpha` and `mu` nodes are
/// cell centres at `(i + 0.5) / N`; the `eta` nodes are cell centres mapped
/// into `[ETA_MIN, ETA_MAX]` at `ETA_MIN + (ETA_MAX - ETA_MIN) * (i + 0.5) /
/// ETA_SIZE`. Generated by
/// [`tests::lut_matches_monte_carlo`].
const ALBEDO: [[[f32; MU_SIZE]; ALPHA_SIZE]; ETA_SIZE] = ALBEDO_DATA;

/// Returns `x` squared, spelled out so the banned `powi`/`powf` are avoided.
fn sqr(x: f32) -> f32 {
    x * x
}

/// Maps a relative index `eta` to the normalized table coordinate in `[0, 1]`,
/// clamped so out-of-range indices resolve to the nearest baked node.
fn eta_unit(eta: f32) -> f32 {
    ((eta - ETA_MIN) / (ETA_MAX - ETA_MIN)).clamp(0.0, 1.0)
}

/// Linearly interpolates one axis of a cell-centred table of length `n` given a
/// continuous coordinate `x` in `[0, 1]`, clamping to the first/last cell.
///
/// Returns the fractional node position `(index_lo, index_hi, frac)` so the
/// trilinear lookup can share the clamping logic across all three axes.
fn axis_weights(x: f32, n: usize) -> (usize, usize, f32) {
    let t = (x * n as f32 - 0.5).clamp(0.0, (n - 1) as f32);
    let lo = t as usize;
    let hi = (lo + 1).min(n - 1);
    (lo, hi, t - lo as f32)
}

/// Linearly interpolates between `a` and `b` by `t`.
fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t
}

/// The lossless single-scatter directional albedo `E(eta, alpha, mu)`,
/// trilinearly interpolated from the baked [`ALBEDO`] table and clamped to
/// `[0, 1]`.
///
/// `mu` is the absolute view cosine `|n·wo|`, `alpha` the `GGX` width, and
/// `eta` the relative index `eta_t / eta_i`.
#[must_use]
pub fn single_scatter_albedo(eta: f32, alpha: f32, mu: f32) -> f32 {
    let (e_lo, e_hi, e_f) = axis_weights(eta_unit(eta), ETA_SIZE);
    let (a_lo, a_hi, a_f) = axis_weights(alpha, ALPHA_SIZE);
    let (m_lo, m_hi, m_f) = axis_weights(mu, MU_SIZE);
    // Inner `mu` lerp at a fixed `(eta, alpha)` node.
    let along_mu = |e: usize, a: usize| lerp(ALBEDO[e][a][m_lo], ALBEDO[e][a][m_hi], m_f);
    // Middle `alpha` lerp at a fixed `eta` node.
    let along_alpha = |e: usize| lerp(along_mu(e, a_lo), along_mu(e, a_hi), a_f);
    // Outer `eta` lerp.
    lerp(along_alpha(e_lo), along_alpha(e_hi), e_f).clamp(0.0, 1.0)
}

/// The smooth-interface ceiling `E_smooth(eta, mu) = R + (1 - R) / eta^2`, the
/// alpha to zero limit of the directional albedo in `PBRT` radiance mode.
///
/// `R` is the smooth unpolarized `Fresnel` reflectance at view cosine `mu`
/// (exterior incidence, `eta_i = 1`), so the reflected share `R` stays in the
/// incident medium while the transmitted share `1 - R` is compressed by the
/// radiance-mode `1 / eta^2` solid-angle factor. Multiple scattering recovers
/// the masking loss up to this value, never past it.
#[must_use]
pub fn smooth_albedo(eta: f32, mu: f32) -> f32 {
    let r = fresnel_dielectric(mu, 1.0, eta);
    r + (1.0 - r) / sqr(eta)
}

/// The multiplicative multiple-scattering compensation factor for a rough
/// dielectric viewed at cosine `mu`.
///
/// Dividing the single-scatter lobe by its directional albedo and multiplying
/// by the smooth ceiling restores exactly the energy Smith masking drops, so a
/// lossless furnace integrates back to `E_smooth` instead of the darkened
/// single-scatter value. The factor is clamped to `[1, MAX_FACTOR]`: it can
/// never remove energy (`>= 1`), and the ceiling guards the near-grazing /
/// near-critical regime where the baked albedo is small.
#[must_use]
pub fn compensation_factor(eta: f32, alpha: f32, mu: f32) -> f32 {
    /// Upper bound on the boost, so a tiny baked albedo cannot explode the lobe.
    const MAX_FACTOR: f32 = 3.0;
    /// Floor on the denominator, matching the smallest trustworthy baked albedo.
    const MIN_ALBEDO: f32 = 0.05;
    let e = single_scatter_albedo(eta, alpha, mu).max(MIN_ALBEDO);
    let ceiling = smooth_albedo(eta, mu);
    (ceiling / e).clamp(1.0, MAX_FACTOR)
}

/// Generated single-scatter directional albedo table (see
/// [`tests::lut_matches_monte_carlo`]).
const ALBEDO_DATA: [[[f32; MU_SIZE]; ALPHA_SIZE]; ETA_SIZE] = [
    [
        [
            0.73804, 0.72718, 0.70504, 0.68996, 0.68273, 0.67986, 0.67868, 0.67847,
        ],
        [
            0.67819, 0.66063, 0.66459, 0.66876, 0.67154, 0.67329, 0.67530, 0.67679,
        ],
        [
            0.63255, 0.61704, 0.62857, 0.64182, 0.65290, 0.66077, 0.66771, 0.67289,
        ],
        [
            0.59579, 0.57771, 0.59305, 0.61321, 0.63071, 0.64638, 0.65782, 0.66684,
        ],
        [
            0.56644, 0.54256, 0.55957, 0.58326, 0.60728, 0.62816, 0.64613, 0.66011,
        ],
        [
            0.54392, 0.51456, 0.52964, 0.55602, 0.58240, 0.60942, 0.63210, 0.65129,
        ],
        [
            0.52451, 0.49156, 0.50505, 0.53054, 0.55992, 0.58877, 0.61684, 0.64212,
        ],
        [
            0.50854, 0.47271, 0.48259, 0.50765, 0.53701, 0.56815, 0.60143, 0.63192,
        ],
    ],
    [
        [
            0.65676, 0.61244, 0.56193, 0.52658, 0.50977, 0.49948, 0.49490, 0.49385,
        ],
        [
            0.56366, 0.52537, 0.51175, 0.50315, 0.49764, 0.49274, 0.49068, 0.49045,
        ],
        [
            0.51299, 0.48429, 0.47761, 0.47600, 0.47959, 0.48099, 0.48336, 0.48538,
        ],
        [
            0.48170, 0.45173, 0.44853, 0.45234, 0.45825, 0.46646, 0.47150, 0.47668,
        ],
        [
            0.45567, 0.42350, 0.42177, 0.42938, 0.43955, 0.44983, 0.45865, 0.46663,
        ],
        [
            0.43544, 0.39949, 0.39830, 0.40775, 0.41927, 0.43207, 0.44479, 0.45655,
        ],
        [
            0.42032, 0.37967, 0.37747, 0.38592, 0.39928, 0.41472, 0.43049, 0.44473,
        ],
        [
            0.40553, 0.36254, 0.35795, 0.36687, 0.38155, 0.39722, 0.41595, 0.43329,
        ],
    ],
    [
        [
            0.61221, 0.54882, 0.48601, 0.44044, 0.41705, 0.40343, 0.39550, 0.39446,
        ],
        [
            0.49421, 0.45177, 0.42977, 0.41477, 0.40395, 0.39652, 0.39374, 0.39068,
        ],
        [
            0.44484, 0.40854, 0.39311, 0.38873, 0.38425, 0.38276, 0.38200, 0.38405,
        ],
        [
            0.41196, 0.37761, 0.36762, 0.36440, 0.36465, 0.36773, 0.36937, 0.37303,
        ],
        [
            0.38917, 0.35355, 0.34401, 0.34386, 0.34599, 0.34974, 0.35515, 0.36001,
        ],
        [
            0.37090, 0.33117, 0.32275, 0.32257, 0.32640, 0.33309, 0.34144, 0.34728,
        ],
        [
            0.35506, 0.31381, 0.30300, 0.30334, 0.30772, 0.31619, 0.32520, 0.33350,
        ],
        [
            0.34288, 0.29831, 0.28736, 0.28733, 0.29234, 0.30100, 0.31042, 0.31970,
        ],
    ],
    [
        [
            0.58283, 0.50853, 0.43915, 0.39572, 0.36744, 0.35531, 0.34514, 0.34416,
        ],
        [
            0.45867, 0.40587, 0.38242, 0.36633, 0.35174, 0.34327, 0.34277, 0.33954,
        ],
        [
            0.40501, 0.36791, 0.34772, 0.33678, 0.33301, 0.33093, 0.32962, 0.32888,
        ],
        [
            0.37290, 0.33664, 0.32120, 0.31619, 0.31420, 0.31193, 0.31446, 0.31496,
        ],
        [
            0.35083, 0.31323, 0.29959, 0.29401, 0.29288, 0.29462, 0.29643, 0.29883,
        ],
        [
            0.33221, 0.29429, 0.27987, 0.27513, 0.27477, 0.27660, 0.27941, 0.28281,
        ],
        [
            0.31869, 0.27848, 0.26265, 0.25585, 0.25778, 0.25940, 0.26442, 0.26758,
        ],
        [
            0.30774, 0.26178, 0.24686, 0.24017, 0.24037, 0.24277, 0.24788, 0.25407,
        ],
    ],
    [
        [
            0.55666, 0.48340, 0.41282, 0.37065, 0.34581, 0.33026, 0.32248, 0.32003,
        ],
        [
            0.43423, 0.38121, 0.35683, 0.33696, 0.32854, 0.32124, 0.31570, 0.31621,
        ],
        [
            0.38391, 0.34101, 0.32143, 0.31175, 0.30541, 0.30074, 0.29998, 0.30066,
        ],
        [
            0.35112, 0.31141, 0.29669, 0.28986, 0.28259, 0.28219, 0.28211, 0.28364,
        ],
        [
            0.33069, 0.29226, 0.27481, 0.26652, 0.26231, 0.26330, 0.26436, 0.26385,
        ],
        [
            0.31504, 0.27339, 0.25533, 0.24895, 0.24314, 0.24430, 0.24539, 0.24630,
        ],
        [
            0.30163, 0.25786, 0.23929, 0.22966, 0.22741, 0.22502, 0.22693, 0.22752,
        ],
        [
            0.29161, 0.24463, 0.22560, 0.21425, 0.21105, 0.20930, 0.21211, 0.21282,
        ],
    ],
    [
        [
            0.54112, 0.46424, 0.39925, 0.35671, 0.33521, 0.32270, 0.31595, 0.31149,
        ],
        [
            0.41664, 0.36889, 0.33929, 0.32711, 0.31922, 0.31135, 0.30705, 0.30905,
        ],
        [
            0.36914, 0.32728, 0.30835, 0.29885, 0.29197, 0.28901, 0.28941, 0.29049,
        ],
        [
            0.33972, 0.30283, 0.28532, 0.27335, 0.26925, 0.26807, 0.26803, 0.26827,
        ],
        [
            0.32112, 0.28204, 0.26536, 0.25333, 0.25027, 0.24650, 0.24578, 0.24785,
        ],
        [
            0.30642, 0.26503, 0.24605, 0.23421, 0.22988, 0.22622, 0.22448, 0.22564,
        ],
        [
            0.29376, 0.24856, 0.22814, 0.21577, 0.21107, 0.20771, 0.20649, 0.20585,
        ],
        [
            0.28420, 0.23535, 0.21348, 0.19920, 0.19338, 0.18936, 0.18748, 0.18784,
        ],
    ],
];

#[cfg(test)]
mod tests {
    use super::super::rough_dielectric::RoughDielectric;
    use super::super::sampler::Rng;
    use super::super::Vec3;
    use super::*;

    /// The macroscopic surface normal used by the furnace integral (`+y`).
    const N: Vec3 = Vec3 {
        x: 0.0,
        y: 1.0,
        z: 0.0,
    };

    /// Maps an `alpha`/`mu` node index to its cell-centre coordinate
    /// `(i + 0.5) / n`.
    fn node_center(i: usize, n: usize) -> f32 {
        (i as f32 + 0.5) / n as f32
    }

    /// Maps a relative-index node index `i` to its sampling value in
    /// `[ETA_MIN, ETA_MAX]`, the cell centre `ETA_MIN + (ETA_MAX - ETA_MIN) *
    /// (i + 0.5) / ETA_SIZE`.
    fn eta_node(i: usize) -> f32 {
        ETA_MIN + (ETA_MAX - ETA_MIN) * (i as f32 + 0.5) / ETA_SIZE as f32
    }

    /// Monte Carlo estimate of the lossless single-scatter directional albedo
    /// `E(eta, alpha, mu)` (reflected plus transmitted) for a rough dielectric
    /// viewed at cosine `mu`, by importance-sampling the base lobe.
    fn mc_albedo(eta: f32, alpha: f32, mu: f32, rng: &mut Rng, samples: u32) -> f32 {
        let roughness = alpha.sqrt();
        let rd = RoughDielectric::new(eta, Vec3::ONE, Vec3::ONE, roughness);
        let sin_o = (1.0 - mu * mu).max(0.0).sqrt();
        let wo = Vec3::new(sin_o, mu, 0.0).normalize_or_zero();
        let mut sum = 0.0f64;
        for _ in 0..samples {
            if let Some(s) = rd.sample(wo, N, rng) {
                // Reflected samples stay above `N`, transmitted ones cross
                // below it; the albedo integral weights both by `|cos_i|`.
                let cos_i = N.dot(s.direction).abs();
                sum += f64::from(s.value.x * cos_i / s.pdf);
            }
        }
        (sum / f64::from(samples)) as f32
    }

    /// Regenerates the baked table from a fresh furnace integral and checks it
    /// matches the committed constants. Run with `--nocapture` to print a fresh
    /// literal when the sampler changes.
    #[test]
    fn lut_matches_monte_carlo() {
        let mut rng = Rng::seed(0x0d1e_1ec7);
        let samples = 1u32 << 16;
        let mut table = [[[0.0f32; MU_SIZE]; ALPHA_SIZE]; ETA_SIZE];
        for ei in 0..ETA_SIZE {
            let eta = eta_node(ei);
            for ai in 0..ALPHA_SIZE {
                let alpha = node_center(ai, ALPHA_SIZE);
                for mi in 0..MU_SIZE {
                    let mu = node_center(mi, MU_SIZE);
                    table[ei][ai][mi] = mc_albedo(eta, alpha, mu, &mut rng, samples);
                }
            }
        }

        // Emit a ready-to-paste literal (visible only under --nocapture).
        println!("const ALBEDO_DATA: [[[f32; MU_SIZE]; ALPHA_SIZE]; ETA_SIZE] = [");
        for eta_block in &table {
            println!("    [");
            for row in eta_block {
                print!("        [");
                for v in row {
                    print!("{v:.5}, ");
                }
                println!("],");
            }
            println!("    ],");
        }
        println!("];");

        // Verify the committed table reproduces the integral within MC noise.
        for ei in 0..ETA_SIZE {
            let eta = eta_node(ei);
            for ai in 0..ALPHA_SIZE {
                let alpha = node_center(ai, ALPHA_SIZE);
                for mi in 0..MU_SIZE {
                    let mu = node_center(mi, MU_SIZE);
                    let baked = single_scatter_albedo(eta, alpha, mu);
                    assert!(
                        (baked - table[ei][ai][mi]).abs() < 2.0e-2,
                        "albedo drift at eta={eta} alpha={alpha} mu={mu}: baked {baked} vs mc {}",
                        table[ei][ai][mi]
                    );
                }
            }
        }
    }

    /// The smooth ceiling must bracket the baked rough albedo and match the
    /// `alpha` to zero limit: a lossless smooth interface integrates to
    /// `R + (1 - R) / eta^2`, strictly below one for `eta > 1`.
    #[test]
    fn smooth_ceiling_is_consistent() {
        let mut rng = Rng::seed(0xbeef_cafe);
        for &eta in &[1.33f32, 1.5, 2.0] {
            for &mu in &[0.2f32, 0.6, 0.95] {
                let ceiling = smooth_albedo(eta, mu);
                assert!(ceiling < 1.0, "radiance-mode ceiling must stay below one");
                // A near-smooth furnace should land close to the analytic ceiling.
                let near_smooth = mc_albedo(eta, 0.02, mu, &mut rng, 1u32 << 16);
                assert!(
                    (near_smooth - ceiling).abs() < 3.0e-2,
                    "near-smooth albedo {near_smooth} should match ceiling {ceiling}",
                );
            }
        }
    }

    /// The compensation factor is unity for smooth surfaces (no masking loss)
    /// and strictly greater than one for rough ones (energy to recover).
    #[test]
    fn compensation_factor_recovers_energy() {
        assert!((compensation_factor(1.5, 0.02, 0.6) - 1.0).abs() < 5.0e-2);
        assert!(compensation_factor(1.5, 0.9, 0.6) > 1.05);
        assert!(compensation_factor(2.0, 0.9, 0.4) > 1.05);
    }
}
