//! Multiple-scattering energy compensation for the isotropic `GGX` conductor.
//!
//! A single-scatter microfacet `BRDF` only accounts for light that leaves the
//! surface after exactly one bounce off a micro-facet. At high roughness a
//! large fraction of the energy instead bounces several times between facets
//! before escaping, and the single-scatter Smith masking term `G2` silently
//! discards all of it. The visible symptom is the classic one: rough metals
//! (and rough dielectrics) turn noticeably too dark and desaturated as
//! roughness rises, violating white-furnace energy conservation.
//!
//! Kulla and Conty ("Revisiting Physically Based Shading at Imageworks", 2017)
//! restore the missing energy with an added, nearly diffuse multiple-scattering
//! lobe whose magnitude is driven by the *directional albedo* of the
//! single-scatter lobe:
//!
//! ```text
//!   E(mu, alpha)  = white-Fresnel single-scatter directional albedo
//!   E_avg(alpha)  = 2 * integral_0^1 E(mu, alpha) * mu  d mu
//!   f_ms(mu_o, mu_i) = (1 - E(mu_o)) * (1 - E(mu_i)) / (pi * (1 - E_avg))
//! ```
//!
//! The lobe exactly makes up the energy deficit `1 - E` so a white furnace
//! integrates back to one. For a coloured conductor the multiple bounces are
//! each attenuated by the average `Fresnel` reflectance `F_avg`, giving the
//! per-channel multiple-scatter tint
//! `F_ms = F_avg^2 * E_avg / (1 - F_avg * (1 - E_avg))`, which also reproduces
//! the subtle saturation increase real rough metals show.
//!
//! `E` and `E_avg` are smooth functions, so they are baked into a small
//! [`LUT_SIZE`]`x`[`LUT_SIZE`] table (`alpha` by `cos_theta`) and bilinearly
//! interpolated at run time. The table is regenerated and checked against a
//! fresh `Monte Carlo` furnace integral by [`tests::lut_matches_monte_carlo`],
//! so the baked constants can never silently drift from the sampler they
//! describe. Lookups use only multiplies, adds, and a clamp — no transcendental
//! call — honouring the crate's determinism policy.

use super::Vec3;

/// Resolution of the directional-albedo lookup table along each axis
/// (`alpha` rows by `cos_theta` columns).
pub const LUT_SIZE: usize = 16;

/// Baked single-scatter directional albedo `E(mu, alpha)` under a white
/// (`F = 1`) `Fresnel` term. The outer index selects the `alpha` node, the
/// inner index the `cos_theta` node; both are cell centres at
/// `(i + 0.5) / LUT_SIZE`. Generated by [`tests::lut_matches_monte_carlo`].
const ALBEDO: [[f32; LUT_SIZE]; LUT_SIZE] = ALBEDO_DATA;

/// Baked cosine-weighted average albedo `E_avg(alpha)` for each `alpha` node,
/// `E_avg = 2 * integral E(mu) mu d mu`. Generated alongside [`ALBEDO`].
const AVG_ALBEDO: [f32; LUT_SIZE] = AVG_ALBEDO_DATA;

/// Linearly interpolates a value from one axis of the table given a continuous
/// coordinate `x` in `[0, 1]`, clamping to the first/last cell centre.
///
/// Returns the fractional node position `(index_lo, index_hi, frac)` so both
/// 1-D and 2-D lookups can share the clamping logic.
fn axis_weights(x: f32) -> (usize, usize, f32) {
    // Continuous node coordinate: node `i` sits at `(i + 0.5) / LUT_SIZE`.
    let t = (x * LUT_SIZE as f32 - 0.5).clamp(0.0, (LUT_SIZE - 1) as f32);
    let lo = t as usize;
    let hi = (lo + 1).min(LUT_SIZE - 1);
    (lo, hi, t - lo as f32)
}

/// The single-scatter directional albedo `E(cos_theta, alpha)` with white
/// `Fresnel`, bilinearly interpolated from the baked table and clamped to
/// `[0, 1]`.
#[must_use]
pub fn directional_albedo(cos_theta: f32, alpha: f32) -> f32 {
    let (a_lo, a_hi, a_f) = axis_weights(alpha);
    let (c_lo, c_hi, c_f) = axis_weights(cos_theta);
    let row_lo = ALBEDO[a_lo][c_lo] + (ALBEDO[a_lo][c_hi] - ALBEDO[a_lo][c_lo]) * c_f;
    let row_hi = ALBEDO[a_hi][c_lo] + (ALBEDO[a_hi][c_hi] - ALBEDO[a_hi][c_lo]) * c_f;
    (row_lo + (row_hi - row_lo) * a_f).clamp(0.0, 1.0)
}

/// The cosine-weighted average albedo `E_avg(alpha)`, linearly interpolated from
/// the baked table and clamped to `[0, 1]`.
#[must_use]
pub fn average_albedo(alpha: f32) -> f32 {
    let (lo, hi, f) = axis_weights(alpha);
    (AVG_ALBEDO[lo] + (AVG_ALBEDO[hi] - AVG_ALBEDO[lo]) * f).clamp(0.0, 1.0)
}

/// The scalar Kulla-Conty multiple-scattering lobe
/// `f_ms = (1 - E(mu_o)) * (1 - E(mu_i)) / (pi * (1 - E_avg))`.
///
/// Returns zero once `E_avg` reaches one (the smooth limit, where there is no
/// energy to recover), avoiding a divide-by-zero.
#[must_use]
pub fn multiscatter_lobe(cos_o: f32, cos_i: f32, alpha: f32) -> f32 {
    let e_avg = average_albedo(alpha);
    let denom = 1.0 - e_avg;
    if denom <= 1.0e-4 {
        return 0.0;
    }
    let e_o = directional_albedo(cos_o, alpha);
    let e_i = directional_albedo(cos_i, alpha);
    (1.0 - e_o) * (1.0 - e_i) / (super::PI * denom)
}

/// The per-channel multiple-scatter `Fresnel` tint
/// `F_ms = F_avg^2 * E_avg / (1 - F_avg * (1 - E_avg))`.
///
/// `f_avg` is the hemispherical-average `Fresnel` reflectance of the interface;
/// each additional bounce multiplies by `F_avg`, so the closed-form geometric
/// series gives the colour of the recovered energy.
#[must_use]
pub fn multiscatter_fresnel(f_avg: Vec3, alpha: f32) -> Vec3 {
    let e_avg = average_albedo(alpha);
    let one_minus = 1.0 - e_avg;
    let channel = |f: f32| -> f32 {
        let denom = 1.0 - f * one_minus;
        if denom <= 1.0e-4 {
            f
        } else {
            f * f * e_avg / denom
        }
    };
    Vec3::new(channel(f_avg.x), channel(f_avg.y), channel(f_avg.z))
}

/// Generated single-scatter albedo table (see [`tests::lut_matches_monte_carlo`]).
const ALBEDO_DATA: [[f32; LUT_SIZE]; LUT_SIZE] = [
    [
        0.89053, 0.94328, 0.97589, 0.98818, 0.99206, 0.99439, 0.99607, 0.99685, 0.99744, 0.99806,
        0.99817, 0.99817, 0.99858, 0.99886, 0.99885, 0.99904,
    ],
    [
        0.93451, 0.88498, 0.89344, 0.91887, 0.93761, 0.95195, 0.96259, 0.96975, 0.97565, 0.97898,
        0.98269, 0.98372, 0.98662, 0.98678, 0.98818, 0.98973,
    ],
    [
        0.94954, 0.88988, 0.87099, 0.87141, 0.88501, 0.89715, 0.91246, 0.92474, 0.93381, 0.94122,
        0.94994, 0.95394, 0.95931, 0.96293, 0.96593, 0.96903,
    ],
    [
        0.95385, 0.89693, 0.86369, 0.85375, 0.85025, 0.85593, 0.86688, 0.87682, 0.88543, 0.89518,
        0.90309, 0.91140, 0.91951, 0.92397, 0.93080, 0.93376,
    ],
    [
        0.95163, 0.89433, 0.86047, 0.83623, 0.82537, 0.82326, 0.82529, 0.83233, 0.83790, 0.84373,
        0.85562, 0.86116, 0.87050, 0.87715, 0.88401, 0.88939,
    ],
    [
        0.94932, 0.88946, 0.84891, 0.82225, 0.80592, 0.79468, 0.79105, 0.79034, 0.79559, 0.80038,
        0.80365, 0.80971, 0.81667, 0.82446, 0.82961, 0.83616,
    ],
    [
        0.94567, 0.88040, 0.83628, 0.80512, 0.78428, 0.76896, 0.76043, 0.75496, 0.75359, 0.75547,
        0.75319, 0.75845, 0.76217, 0.76699, 0.77263, 0.77446,
    ],
    [
        0.94142, 0.87175, 0.82330, 0.79018, 0.76237, 0.74273, 0.73166, 0.72252, 0.71253, 0.70897,
        0.70770, 0.70686, 0.70679, 0.70787, 0.71245, 0.71734,
    ],
    [
        0.93671, 0.86121, 0.80691, 0.76759, 0.73937, 0.72034, 0.69780, 0.68750, 0.67520, 0.66904,
        0.66345, 0.66195, 0.65407, 0.65477, 0.65289, 0.65404,
    ],
    [
        0.92915, 0.84826, 0.79412, 0.75430, 0.71678, 0.69452, 0.66872, 0.65459, 0.64058, 0.62912,
        0.62176, 0.61331, 0.60612, 0.60542, 0.60027, 0.59651,
    ],
    [
        0.92425, 0.83505, 0.77650, 0.73150, 0.69712, 0.66509, 0.64125, 0.61974, 0.60482, 0.59115,
        0.57870, 0.56560, 0.56079, 0.55360, 0.54713, 0.54434,
    ],
    [
        0.91756, 0.82414, 0.75863, 0.71164, 0.67160, 0.63993, 0.61433, 0.59389, 0.57071, 0.55353,
        0.53875, 0.52792, 0.51651, 0.50474, 0.50088, 0.49233,
    ],
    [
        0.91143, 0.81112, 0.74357, 0.68803, 0.65290, 0.61420, 0.58876, 0.55983, 0.53882, 0.51787,
        0.50314, 0.48608, 0.47485, 0.46401, 0.45315, 0.44662,
    ],
    [
        0.90468, 0.79955, 0.73071, 0.67325, 0.62805, 0.59150, 0.55480, 0.52925, 0.50862, 0.48782,
        0.46760, 0.45411, 0.43806, 0.42644, 0.41378, 0.40239,
    ],
    [
        0.89889, 0.78596, 0.71155, 0.65008, 0.60615, 0.56783, 0.53284, 0.50402, 0.47753, 0.45741,
        0.43591, 0.41926, 0.39868, 0.38978, 0.37722, 0.36418,
    ],
    [
        0.89346, 0.77409, 0.69544, 0.63218, 0.58563, 0.54142, 0.50747, 0.47595, 0.44834, 0.42990,
        0.40566, 0.38615, 0.36961, 0.35676, 0.34430, 0.32918,
    ],
];
/// Generated average-albedo table (see [`tests::lut_matches_monte_carlo`]).
const AVG_ALBEDO_DATA: [f32; LUT_SIZE] = [
    0.99608, 0.97482, 0.94267, 0.90348, 0.86012, 0.81500, 0.76850, 0.72253, 0.67764, 0.63568,
    0.59390, 0.55526, 0.51834, 0.48476, 0.45266, 0.42318,
];

#[cfg(test)]
mod tests {
    use super::super::microfacet::GgxIsotropic;
    use super::super::sampler::Rng;
    use super::super::Vec3;
    use super::*;

    /// Maps a table node index `i` to its cell-centre coordinate
    /// `(i + 0.5) / LUT_SIZE` in the open interval `(0, 1)`.
    fn node_center(i: usize) -> f32 {
        (i as f32 + 0.5) / LUT_SIZE as f32
    }

    /// Monte Carlo estimate of the white-Fresnel single-scatter directional
    /// albedo `E(cos_o, alpha)` via visible-normal sampling, whose throughput
    /// weight collapses to `G2(wo, wi) / G1(wo)`.
    fn mc_albedo(alpha: f32, cos_o: f32, rng: &mut Rng, samples: u32) -> f32 {
        let dist = GgxIsotropic { alpha };
        let normal = Vec3::new(0.0, 0.0, 1.0);
        let sin_o = (1.0 - cos_o * cos_o).max(0.0).sqrt();
        let wo = Vec3::new(sin_o, 0.0, cos_o);
        let g1o = dist.g1(cos_o);
        if g1o <= 0.0 {
            return 0.0;
        }
        let mut sum = 0.0f64;
        for _ in 0..samples {
            if let Some(h) = dist.sample_half_vector(wo, normal, rng) {
                let woh = wo.dot(h);
                if woh <= 0.0 {
                    continue;
                }
                let wi = wo.negate().reflect(h).normalize_or_zero();
                let cos_i = wi.z;
                if cos_i <= 0.0 {
                    continue;
                }
                sum += f64::from(dist.g2(cos_o, cos_i) / g1o);
            }
        }
        (sum / f64::from(samples)) as f32
    }

    /// Regenerates the baked table from a fresh furnace integral and checks it
    /// matches the committed constants. Run with `--nocapture` to print a fresh
    /// literal when the sampler changes.
    #[expect(
        clippy::print_stdout,
        clippy::needless_range_loop,
        reason = "test regenerates and prints a paste-ready baked LUT literal under --nocapture; the LUT is indexed on two axes"
    )]
    #[test]
    fn lut_matches_monte_carlo() {
        let mut rng = Rng::seed(0x5eed_1234);
        let samples = 1u32 << 16;
        let mut albedo = [[0.0f32; LUT_SIZE]; LUT_SIZE];
        let mut avg = [0.0f32; LUT_SIZE];
        for ai in 0..LUT_SIZE {
            let alpha = node_center(ai);
            let mut acc = 0.0f64;
            for ci in 0..LUT_SIZE {
                let cos_o = node_center(ci);
                let e = mc_albedo(alpha, cos_o, &mut rng, samples);
                albedo[ai][ci] = e;
                // Midpoint rule for 2 * integral E(mu) mu d mu over the row.
                acc += 2.0 * f64::from(e) * f64::from(cos_o) / f64::from(LUT_SIZE as u32);
            }
            avg[ai] = acc as f32;
        }

        // Emit a ready-to-paste literal (visible only under --nocapture).
        println!("const ALBEDO_DATA: [[f32; LUT_SIZE]; LUT_SIZE] = [");
        for row in &albedo {
            print!("    [");
            for v in row {
                print!("{v:.5}, ");
            }
            println!("],");
        }
        println!("];");
        print!("const AVG_ALBEDO_DATA: [f32; LUT_SIZE] = [");
        for v in &avg {
            print!("{v:.5}, ");
        }
        println!("];");

        // Verify the committed table reproduces the integral within MC noise.
        for ai in 0..LUT_SIZE {
            let alpha = node_center(ai);
            for ci in 0..LUT_SIZE {
                let cos_o = node_center(ci);
                let baked = directional_albedo(cos_o, alpha);
                assert!(
                    (baked - albedo[ai][ci]).abs() < 2.0e-2,
                    "albedo drift at alpha={alpha} cos={cos_o}: baked {baked} vs mc {}",
                    albedo[ai][ci]
                );
            }
            let baked_avg = average_albedo(alpha);
            assert!(
                (baked_avg - avg[ai]).abs() < 2.0e-2,
                "avg drift at alpha={alpha}: baked {baked_avg} vs mc {}",
                avg[ai]
            );
        }
    }

    /// Smooth surfaces lose no energy, so the compensation lobe must vanish.
    #[test]
    fn smooth_surface_needs_no_compensation() {
        assert!(average_albedo(0.0) > 0.98);
        assert!(multiscatter_lobe(0.6, 0.6, 0.0) < 1.0e-2);
    }

    /// Rough surfaces lose energy, so both the albedo deficit and the
    /// compensation lobe must be strictly positive.
    #[test]
    fn rough_surface_recovers_energy() {
        assert!(average_albedo(0.9) < 0.95);
        assert!(multiscatter_lobe(0.5, 0.5, 0.9) > 0.0);
    }
}
