//! Reconstructing concrete values from any `&dyn Reflect` ([`FromReflect`]).
//!
//! [`FromReflect`] is the inverse of reflection: given any reflected value
//! (a concrete type, a [`Dynamic*`](crate::dynamic), or the output of
//! [`reflect_clone`](crate::Reflect::reflect_clone)) it rebuilds a concrete
//! `T`. Leaf values downcast-and-clone; container types read their kind view
//! and `from_reflect` each element; derived structs/enums are generated by
//! `#[derive(Reflect)]`.

use crate::reflect::{Reflect, Typed};
use crate::ReflectRef;
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::vec::Vec;

/// Reconstruct a concrete `Self` from an arbitrary reflected value.
///
/// Implemented for every leaf type, the std collections, the `math` value
/// types, `Option`/`Result`, and (via `#[derive(Reflect)]`) user structs,
/// tuple structs, and enums.
pub trait FromReflect: Reflect + Sized {
    /// Attempt to build `Self` from `reflect`, returning `None` on a shape or
    /// type mismatch.
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self>;
}

impl<T: FromReflect + Typed> FromReflect for Vec<T> {
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::List(list) = reflect.reflect_ref() else {
            return None;
        };
        let mut out = Vec::with_capacity(list.len());
        for index in 0..list.len() {
            out.push(T::from_reflect(list.get(index)?)?);
        }
        Some(out)
    }
}

impl<T: FromReflect + Typed, const N: usize> FromReflect for [T; N] {
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Array(array) = reflect.reflect_ref() else {
            return None;
        };
        if array.len() != N {
            return None;
        }
        let mut out = Vec::with_capacity(N);
        for index in 0..N {
            out.push(T::from_reflect(array.get(index)?)?);
        }
        out.try_into().ok()
    }
}

impl<K, V> FromReflect for HashMap<K, V>
where
    K: FromReflect + Typed + ::core::hash::Hash + ::core::cmp::Eq,
    V: FromReflect + Typed,
{
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Map(map) = reflect.reflect_ref() else {
            return None;
        };
        let mut out = HashMap::with_capacity(map.len());
        for (key, value) in map.iter_reflect() {
            out.insert(K::from_reflect(key)?, V::from_reflect(value)?);
        }
        Some(out)
    }
}

impl<K, V> FromReflect for BTreeMap<K, V>
where
    K: FromReflect + Typed + ::core::cmp::Ord,
    V: FromReflect + Typed,
{
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Map(map) = reflect.reflect_ref() else {
            return None;
        };
        let mut out = BTreeMap::new();
        for (key, value) in map.iter_reflect() {
            out.insert(K::from_reflect(key)?, V::from_reflect(value)?);
        }
        Some(out)
    }
}

impl<T> FromReflect for HashSet<T>
where
    T: FromReflect + Typed + ::core::hash::Hash + ::core::cmp::Eq + ::core::clone::Clone,
{
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Set(set) = reflect.reflect_ref() else {
            return None;
        };
        let mut out = HashSet::with_capacity(set.len());
        for value in set.iter_reflect() {
            out.insert(T::from_reflect(value)?);
        }
        Some(out)
    }
}

impl<T> FromReflect for BTreeSet<T>
where
    T: FromReflect + Typed + ::core::cmp::Ord + ::core::clone::Clone,
{
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Set(set) = reflect.reflect_ref() else {
            return None;
        };
        let mut out = BTreeSet::new();
        for value in set.iter_reflect() {
            out.insert(T::from_reflect(value)?);
        }
        Some(out)
    }
}

impl<T: FromReflect + Typed> FromReflect for Option<T> {
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Enum(value) = reflect.reflect_ref() else {
            return None;
        };
        match value.variant_name() {
            "None" => Some(None),
            "Some" => Some(Some(T::from_reflect(value.field_at(0)?)?)),
            _ => None,
        }
    }
}

impl<T: FromReflect + Typed, E: FromReflect + Typed> FromReflect for Result<T, E> {
    fn from_reflect(reflect: &dyn Reflect) -> Option<Self> {
        let ReflectRef::Enum(value) = reflect.reflect_ref() else {
            return None;
        };
        match value.variant_name() {
            "Ok" => Some(Ok(T::from_reflect(value.field_at(0)?)?)),
            "Err" => Some(Err(E::from_reflect(value.field_at(0)?)?)),
            _ => None,
        }
    }
}

/// Compile-time check that `Box<dyn Reflect>` is accepted by [`FromReflect`]
/// bounds exactly where the derive relies on them.
const _: fn() = || {
    fn _assert<T: FromReflect>() {}
    _assert::<Vec<i32>>();
    _assert::<Option<i32>>();
};
