//! The [`TypeRegistry`]: a runtime catalogue of reflected types.
//!
//! The registry maps a type's [`TypeId`] to a [`TypeRegistration`] that bundles
//! the static [`TypeInfo`] with a set of [`TypeData`] payloads. Types opt in by
//! implementing [`GetTypeRegistration`] (generated by `#[derive(Reflect)]` and
//! the leaf/container impls), then calling [`TypeRegistry::register`]. Lookups
//! are available by `TypeId` and by fully-qualified type name.

use crate::reflect::{Reflect, Typed};
use crate::type_data::TypeData;
use crate::type_info::TypeInfo;
use core::any::TypeId;
use std::boxed::Box;
use std::collections::HashMap;

/// A type that can produce its own [`TypeRegistration`] without an instance.
pub trait GetTypeRegistration {
    /// Build the registration describing this type.
    fn get_type_registration() -> TypeRegistration;
}

/// The registry entry for a single reflected type.
pub struct TypeRegistration {
    type_id: TypeId,
    type_name: &'static str,
    type_info: &'static TypeInfo,
    data: HashMap<TypeId, Box<dyn TypeData>>,
}

impl TypeRegistration {
    /// Build a bare registration for `T` with no attached type data.
    #[must_use]
    pub fn of<T: Reflect + Typed>() -> Self {
        Self {
            type_id: TypeId::of::<T>(),
            type_name: ::core::any::type_name::<T>(),
            type_info: <T as Typed>::type_info(),
            data: HashMap::new(),
        }
    }

    /// The registered type's `TypeId`.
    #[must_use]
    pub fn type_id(&self) -> TypeId {
        self.type_id
    }

    /// The registered type's fully-qualified name.
    #[must_use]
    pub fn type_name(&self) -> &'static str {
        self.type_name
    }

    /// The registered type's static descriptor.
    #[must_use]
    pub fn type_info(&self) -> &'static TypeInfo {
        self.type_info
    }

    /// Attach (or replace) a type-data payload of type `D`.
    pub fn insert<D: TypeData>(&mut self, data: D) {
        self.data.insert(TypeId::of::<D>(), Box::new(data));
    }

    /// Borrow the attached type-data payload of type `D`, if present.
    #[must_use]
    pub fn data<D: TypeData>(&self) -> Option<&D> {
        self.data
            .get(&TypeId::of::<D>())
            .and_then(|d| d.as_any().downcast_ref::<D>())
    }

    /// Whether a type-data payload of type `D` is attached.
    #[must_use]
    pub fn contains_data<D: TypeData>(&self) -> bool {
        self.data.contains_key(&TypeId::of::<D>())
    }
}

impl Clone for TypeRegistration {
    fn clone(&self) -> Self {
        let mut data = HashMap::with_capacity(self.data.len());
        for (key, value) in &self.data {
            data.insert(*key, value.clone_type_data());
        }
        Self {
            type_id: self.type_id,
            type_name: self.type_name,
            type_info: self.type_info,
            data,
        }
    }
}

/// A runtime catalogue mapping `TypeId` (and type name) to [`TypeRegistration`].
#[derive(Default)]
pub struct TypeRegistry {
    registrations: HashMap<TypeId, TypeRegistration>,
    name_to_id: HashMap<&'static str, TypeId>,
}

impl TypeRegistry {
    /// Build an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Register `T` using its [`GetTypeRegistration`] implementation.
    pub fn register<T: GetTypeRegistration>(&mut self) {
        self.add_registration(T::get_type_registration());
    }

    /// Insert a pre-built registration, indexing it by `TypeId` and name.
    pub fn add_registration(&mut self, registration: TypeRegistration) {
        self.name_to_id
            .insert(registration.type_name(), registration.type_id());
        self.registrations
            .insert(registration.type_id(), registration);
    }

    /// Look up a registration by `TypeId`.
    #[must_use]
    pub fn get(&self, type_id: TypeId) -> Option<&TypeRegistration> {
        self.registrations.get(&type_id)
    }

    /// Mutably look up a registration by `TypeId`.
    pub fn get_mut(&mut self, type_id: TypeId) -> Option<&mut TypeRegistration> {
        self.registrations.get_mut(&type_id)
    }

    /// Look up a registration by fully-qualified type name.
    #[must_use]
    pub fn get_with_name(&self, type_name: &str) -> Option<&TypeRegistration> {
        let type_id = self.name_to_id.get(type_name)?;
        self.registrations.get(type_id)
    }

    /// Mutably look up a registration by fully-qualified type name.
    pub fn get_with_name_mut(&mut self, type_name: &str) -> Option<&mut TypeRegistration> {
        let type_id = *self.name_to_id.get(type_name)?;
        self.registrations.get_mut(&type_id)
    }

    /// Attach a type-data payload to the already-registered type `T`.
    ///
    /// Returns `true` on success, or `false` when `T` is not registered.
    pub fn register_type_data<T: 'static, D: TypeData>(&mut self, data: D) -> bool {
        match self.registrations.get_mut(&TypeId::of::<T>()) {
            Some(registration) => {
                registration.insert(data);
                true
            }
            None => false,
        }
    }

    /// Whether a type with the given `TypeId` is registered.
    #[must_use]
    pub fn contains(&self, type_id: TypeId) -> bool {
        self.registrations.contains_key(&type_id)
    }

    /// Number of registered types.
    #[must_use]
    pub fn len(&self) -> usize {
        self.registrations.len()
    }

    /// Whether no types are registered.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.registrations.is_empty()
    }

    /// Iterate over all registrations.
    pub fn iter(&self) -> impl Iterator<Item = &TypeRegistration> {
        self.registrations.values()
    }
}
