// DO NOT EDIT — generated by `prism-material-codegen` from schema/surface.toml.
// Regenerate: cargo run -p prism_material_schema --bin prism-material-codegen -- write
//! Generated über-BSDF surface layout facts (design doc §17.5, stage S2).
//!
//! The single declarative source of truth is `schema/surface.toml` in
//! `prism_material_schema`. This module exports the layout constants and the
//! canonical lobe table so the hand-written typed structs in `surface.rs` can be
//! checked against — never diverge from — the schema. Edit the schema, not this.

/// Number of `u32` words in the always-present surface core.
pub const SURFACE_CORE_WORDS: usize = 12;
/// Number of `u32` words in every uniform per-lobe quantum.
pub const SURFACE_LOBE_WORDS: usize = 4;
/// Number of defined optional lobes (equals `LobeMask::COUNT`).
pub const SURFACE_LOBE_COUNT: u32 = 7;
/// Fully-loaded worst case: core plus every lobe. The WESL decoder gathers into
/// an `array<u32, SURFACE_MAX_WORDS>`.
pub const SURFACE_MAX_WORDS: usize = 40;

/// One optional lobe's generated identity, in canonical pack order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LobeLayout {
    /// Human-facing lobe id (schema `id`).
    pub id: &'static str,
    /// Matching `LobeMask` associated-constant name.
    pub mask_const: &'static str,
    /// Immutable `LobeMask` bit index and low-bit-first pack order.
    pub registry_slot: u32,
    /// `u32` word footprint of the lobe.
    pub words: usize,
}

/// The defined lobes in canonical low-bit-first pack order.
pub const SURFACE_LOBES: [LobeLayout; 7] = [
    LobeLayout {
        id: "emission",
        mask_const: "EMISSION",
        registry_slot: 0,
        words: 4,
    },
    LobeLayout {
        id: "clearcoat",
        mask_const: "CLEARCOAT",
        registry_slot: 1,
        words: 4,
    },
    LobeLayout {
        id: "anisotropy",
        mask_const: "ANISOTROPY",
        registry_slot: 2,
        words: 4,
    },
    LobeLayout {
        id: "sheen",
        mask_const: "SHEEN",
        registry_slot: 3,
        words: 4,
    },
    LobeLayout {
        id: "subsurface",
        mask_const: "SUBSURFACE",
        registry_slot: 4,
        words: 4,
    },
    LobeLayout {
        id: "transmission",
        mask_const: "TRANSMISSION",
        registry_slot: 5,
        words: 4,
    },
    LobeLayout {
        id: "face",
        mask_const: "FACE",
        registry_slot: 6,
        words: 4,
    },
];
