//! Ordered-dither debanding — CPU golden reference.
//!
//! Smooth gradients quantized to a low bit depth (8-bit output, or the coarse
//! intermediate steps a tone-map / colour-grade chain produces) show visible
//! **banding**: wide flat plateaus separated by hard contour lines. Dithering
//! hides this by adding a tiny, structured perturbation *before* quantization,
//! so the quantizer rounds different pixels within a plateau to different
//! levels. Averaged over a small area the perturbation integrates back to the
//! original value, trading a stark contour for imperceptible high-frequency
//! texture.
//!
//! This module is the backend-neutral reference for an **ordered** (texture-
//! and-RNG-free) debander. The ordering pattern comes from two deterministic
//! sources the WESL/GPU twin can reproduce exactly:
//!
//! * [`bayer8`] — the classic recursive 8x8 Bayer threshold matrix, normalised
//!   to `[0, 1)`. Its 64 distinct levels average to exactly `0.5` over a tile,
//!   which is what makes the debander's mean bias zero.
//! * [`ign`] — Jorge Jimenez's Interleaved Gradient Noise, a cheap screen-space
//!   hash in `[0, 1)` with pleasant blue-noise-like spectral properties.
//!
//! [`deband`] forms a **triangular-PDF (TPDF)** dither — the sum of two
//! independent ordered uniforms, shifted to be zero-mean — scaled so its
//! amplitude never exceeds one quantization step `1 / levels`. TPDF dither is
//! the standard choice because it fully decorrelates the quantization error
//! from the signal (unlike a single rectangular-PDF sample).
//!
//! # Conventions
//! * Deterministic pure functions: no RNG, IO, GPU, global state, or `unsafe`.
//! * Transcendental-free; the only non-trivial op is `floor` via
//!   [`bevy_math::ops`] inside [`ign`]'s fractional part.
//! * Colours are linear-RGB [`Vec3`], sanitized to be finite and non-negative.
//! * `strength` is clamped to `[0, 1]`; `strength = 0` is a strict identity.
//! * `levels` is floored to `1`; the per-channel dither magnitude is bounded by
//!   `strength / levels <= 1 / levels`.

use bevy_math::{ops, IVec2, Vec3};

/// Side length of the Bayer tile.
pub const BAYER_SIZE: i32 = 8;

/// Number of distinct Bayer levels (`BAYER_SIZE * BAYER_SIZE`).
pub const BAYER_LEVELS: f32 = 64.0;

/// The 8x8 recursive Bayer ordered-dither matrix, values `0..=63`.
///
/// Row `y`, column `x` holds the dither rank of that cell. Generated by the
/// standard recurrence `M_{2n} = [[4·M_n, 4·M_n + 2], [4·M_n + 3, 4·M_n + 1]]`.
pub const BAYER_8X8: [[u8; 8]; 8] = [
    [0, 32, 8, 40, 2, 34, 10, 42],
    [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38],
    [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41],
    [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37],
    [63, 31, 55, 23, 61, 29, 53, 21],
];

/// Replaces a non-finite scalar with `fallback`.
#[inline]
fn finite_or(x: f32, fallback: f32) -> f32 {
    if x.is_finite() { x } else { fallback }
}

/// Fractional part `x - floor(x)` in `[0, 1)` for finite `x`.
#[inline]
fn fract(x: f32) -> f32 {
    x - ops::floor(x)
}

/// Clamps a colour to be finite and non-negative component-wise.
#[inline]
fn sanitize(color: Vec3) -> Vec3 {
    Vec3::new(
        finite_or(color.x, 0.0).max(0.0),
        finite_or(color.y, 0.0).max(0.0),
        finite_or(color.z, 0.0).max(0.0),
    )
}

/// Wraps an integer coordinate into `0..BAYER_SIZE`, correctly for negatives.
#[inline]
fn wrap8(v: i32) -> usize {
    (v & (BAYER_SIZE - 1)) as usize
}

/// Normalised Bayer threshold in `[0, 1)` for integer pixel `(x, y)`.
///
/// Returns `(rank + 0.5) / 64`, i.e. the cell's rank biased to its bin center,
/// so the 64 values are symmetric about `0.5` and average to exactly `0.5`
/// over any full tile. The coordinate wraps with period 8 on each axis.
#[must_use]
pub fn bayer8(x: i32, y: i32) -> f32 {
    let rank = BAYER_8X8[wrap8(y)][wrap8(x)] as f32;
    (rank + 0.5) / BAYER_LEVELS
}

/// Interleaved Gradient Noise in `[0, 1)` for pixel coordinate `(x, y)`.
///
/// Jorge Jimenez's screen-space hash
/// `fract(52.9829189 · fract(0.06711056·x + 0.00583715·y))`. Deterministic and
/// cheap, with a blue-noise-like spectrum well suited to dithering. Non-finite
/// inputs fall back to `0`.
#[must_use]
pub fn ign(x: f32, y: f32) -> f32 {
    let xf = finite_or(x, 0.0);
    let yf = finite_or(y, 0.0);
    let inner = fract(0.067_110_56 * xf + 0.005_837_15 * yf);
    fract(52.982_918_9 * inner).clamp(0.0, 1.0)
}

/// Zero-mean triangular-PDF dither in `(-1, 1)` for pixel `(x, y)` and channel
/// `ch`. Built from two Bayer samples at channel-dependent offsets so the three
/// channels decorrelate while each still averages to zero over a tile.
fn tri_dither(x: i32, y: i32, ch: i32) -> f32 {
    let u1 = bayer8(x + 2 * ch, y + ch);
    let u2 = bayer8(x + ch, y + 2 * ch + 4);
    // Sum of two independent uniforms, recentred: triangular on (-1, 1).
    u1 + u2 - 1.0
}

/// Debands one pixel by adding bounded, zero-mean ordered dither before an
/// (external) quantization to `levels` steps.
///
/// The per-channel offset is `strength · tri · (1 / levels)` with
/// `tri ∈ (-1, 1)`, so its magnitude is strictly below `1 / levels`. With
/// `strength = 0` the function is the identity. The result is kept finite and
/// non-negative; it is intentionally *not* clamped to `[0, 1]`, since the
/// caller owns the output range and quantization.
#[must_use]
pub fn deband(color: Vec3, coord: IVec2, levels: u32, strength: f32) -> Vec3 {
    let base = sanitize(color);
    let s = finite_or(strength, 0.0).clamp(0.0, 1.0);
    if s <= 0.0 {
        return base;
    }

    let step = 1.0 / levels.max(1) as f32;
    let scale = s * step;
    let (x, y) = (coord.x, coord.y);

    let offset = Vec3::new(
        tri_dither(x, y, 0) * scale,
        tri_dither(x, y, 1) * scale,
        tri_dither(x, y, 2) * scale,
    );
    sanitize(base + offset)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every Bayer rank appears exactly once and lies in `0..=63`.
    #[test]
    fn bayer_matrix_is_a_permutation() {
        let mut seen = [false; 64];
        for row in &BAYER_8X8 {
            for &v in row {
                assert!(v < 64, "value {v} out of range");
                assert!(!seen[v as usize], "duplicate value {v}");
                seen[v as usize] = true;
            }
        }
        assert!(seen.iter().all(|&b| b), "not all ranks present");
    }

    /// Normalised Bayer values stay in `[0, 1)` and average to `0.5` over a
    /// tile.
    #[test]
    fn bayer8_range_and_mean() {
        let mut sum = 0.0_f64;
        for y in 0..8 {
            for x in 0..8 {
                let v = bayer8(x, y);
                assert!((0.0..1.0).contains(&v), "v={v}");
                sum += v as f64;
            }
        }
        let mean = (sum / 64.0) as f32;
        assert!((mean - 0.5).abs() < 1.0e-6, "mean={mean}");
    }

    /// Bayer addressing wraps with period 8 and handles negative coordinates.
    #[test]
    fn bayer8_wraps() {
        assert_eq!(bayer8(0, 0), bayer8(8, 8));
        assert_eq!(bayer8(1, 2), bayer8(-7, -6));
    }

    /// IGN stays within `[0, 1)` across a grid and is deterministic.
    #[test]
    fn ign_range_and_determinism() {
        for y in 0..32 {
            for x in 0..32 {
                let v = ign(x as f32, y as f32);
                assert!((0.0..1.0).contains(&v), "x={x} y={y} v={v}");
            }
        }
        assert_eq!(ign(12.0, 7.0), ign(12.0, 7.0));
        assert_eq!(ign(f32::NAN, 3.0), ign(0.0, 3.0));
    }

    /// `strength = 0` is a strict identity.
    #[test]
    fn zero_strength_is_identity() {
        let color = Vec3::new(0.25, 0.5, 0.75);
        for &(x, y) in &[(0, 0), (3, 5), (-2, 9), (17, 42)] {
            let out = deband(color, IVec2::new(x, y), 16, 0.0);
            assert_eq!(out, color, "coord=({x},{y})");
        }
    }

    /// Dither magnitude never exceeds one quantization step `1 / levels`.
    #[test]
    fn dither_amplitude_is_bounded() {
        let color = Vec3::splat(0.5);
        for &levels in &[8_u32, 16, 64, 256] {
            let step = 1.0 / levels as f32;
            for y in 0..16 {
                for x in 0..16 {
                    let out = deband(color, IVec2::new(x, y), levels, 1.0);
                    let d = out - color;
                    assert!(d.x.abs() <= step + 1.0e-6, "levels={levels} dx={}", d.x);
                    assert!(d.y.abs() <= step + 1.0e-6, "levels={levels} dy={}", d.y);
                    assert!(d.z.abs() <= step + 1.0e-6, "levels={levels} dz={}", d.z);
                }
            }
        }
    }

    /// Averaged over a tile the dither has (near) zero DC bias, so the mean
    /// colour is preserved — the whole point of TPDF debanding.
    #[test]
    fn mean_is_preserved_over_a_tile() {
        let color = Vec3::splat(0.5);
        let mut acc = Vec3::ZERO;
        let mut count = 0.0_f32;
        for y in 0..8 {
            for x in 0..8 {
                acc += deband(color, IVec2::new(x, y), 16, 1.0);
                count += 1.0;
            }
        }
        let mean = acc / count;
        assert!((mean.x - color.x).abs() < 1.0e-5, "mean={mean:?}");
        assert!((mean.y - color.y).abs() < 1.0e-5, "mean={mean:?}");
        assert!((mean.z - color.z).abs() < 1.0e-5, "mean={mean:?}");
    }

    /// Determinism: identical arguments give bit-identical output; neighbouring
    /// pixels generally differ (the dither is spatially varying).
    #[test]
    fn deband_determinism_and_variation() {
        let color = Vec3::splat(0.4);
        let a = deband(color, IVec2::new(5, 9), 32, 0.8);
        let b = deband(color, IVec2::new(5, 9), 32, 0.8);
        assert_eq!(a, b);

        let c = deband(color, IVec2::new(6, 9), 32, 0.8);
        assert!(a != c, "expected spatial variation, a={a:?} c={c:?}");
    }

    /// Degenerate input stays finite and non-negative; `levels = 0` is treated
    /// as `1` rather than dividing by zero.
    #[test]
    fn degenerate_input_is_sanitized() {
        let color = Vec3::new(f32::NAN, 0.5, f32::INFINITY);
        let out = deband(color, IVec2::new(3, 4), 0, f32::NAN);
        assert!(out.x.is_finite() && out.y.is_finite() && out.z.is_finite(), "out={out:?}");
        assert!(out.x >= 0.0 && out.y >= 0.0 && out.z >= 0.0, "out={out:?}");

        let big = deband(Vec3::splat(0.5), IVec2::new(1, 1), 4, 5.0);
        let step = 1.0 / 4.0;
        assert!((big - Vec3::splat(0.5)).x.abs() <= step + 1.0e-6, "big={big:?}");
    }
}
