//! `Bloom` progressive-upsample composite: the wide-halo second half of the
//! bloom pyramid (design §16-§21).
//!
//! Once the bright-pass prefilter has isolated the emissive pixels and a
//! downsample chain has built a pyramid of ever-coarser `mip` levels, the glow
//! is synthesized by walking that pyramid back up. Every production stack
//! (Unreal's bloom, `Frostbite`'s FX post, Call-of-Duty's dual-filter bloom)
//! upsamples each coarse `mip` with a small `tent` kernel and *adds* it onto the
//! next-finer level with a per-`mip` weight. Summing progressively wider blurs
//! is what turns a handful of cheap blurs into the smooth, wide-domain halo the
//! eye reads as "this surface is emitting more light than the display can show".
//!
//! This module owns the `CPU`-verifiable maths of that upsample-and-composite
//! contract and packs its parameters into the `std430` block a future `GPU`
//! upsample kernel binds. Images are linear `HDR` `RGB` triples (the alpha of an
//! `RGBA` target is irrelevant to additive glow and is not modelled here).
//!
//! # Strict scope
//!
//! This file is *only* the upsample + `tent` composite chain:
//!
//! * It does **not** run the bright-pass prefilter, the soft `knee`, or the
//!   `Karis` anti-firefly downsample average — those belong to
//!   [`super::bloom_threshold`], and this module never touches a `threshold`,
//!   `knee`, or `Karis` weight. It assumes the pyramid it is handed is already
//!   the thresholded, downsampled bloom source.
//! * It does **not** tone-map (that is [`super::tonemap`]'s `Reinhard`/`ACES`
//!   curves) and it does **not** build a `luminance` histogram or drive exposure
//!   (that is [`super::luminance_hist`]).
//!
//! Its whole job is: coarse `mip` -> `tent` upsample -> weighted add -> repeat.
//!
//! # Determinism
//!
//! The determinism-locked contract layer forbids transcendental functions
//! (`sin`/`cos`/`exp`/`ln`/`powf`). The per-`mip` weight chain is a geometric
//! series generated by *repeated rational multiplication* rather than `powf`,
//! the soft glow-width control is a `smoothstep`, and the `tent` convolution is
//! a fixed `[1, 2, 1] / 16` separable kernel. Evaluation touches only
//! `+ - * /`, `f32::floor` is never needed, and there is no `LUT`, so a future
//! `GPU` kernel reproduces the `CPU` result bit for bit.

use crate::particle::gpu_layout::{storage_bytes, U32_STRIDE, VEC2_STRIDE, VEC4_STRIDE};
use alloc::vec::Vec;

/// The separable 1D `tent` weights `[1, 2, 1]`; the 3x3 `tent` kernel is their
/// outer product and its entries sum to `16`.
const TENT_1D: [f32; 3] = [1.0, 2.0, 1.0];

/// Normalization divisor for the 3x3 `tent` kernel: the outer product of
/// [`TENT_1D`] sums to `(1 + 2 + 1)^2 = 16`, so dividing by this makes the
/// kernel weights sum to exactly `1`.
const TENT_NORM: f32 = 16.0;

/// Denominators with magnitude below this are treated as (near) zero so the
/// `smoothstep` normalization falls back to a defined result instead of
/// dividing by zero or propagating `NaN`.
const MIN_DENOM: f32 = 1e-6;

/// Number of scalar fields packed into the [`BloomUpsampleParams`] `std430`
/// block: `radius`, `intensity`, and `mip_count`.
const BLOOM_UPSAMPLE_FIELD_COUNT: usize = 3;

/// Byte size of the `std430` packing of [`BloomUpsampleParams`]: the three
/// scalars rounded up to whole `vec4` slots so the block honors the 16-byte
/// `std430` base alignment. Three scalars occupy a single `vec4` slot (16
/// bytes) with a one-scalar padding tail.
pub const BLOOM_UPSAMPLE_STD430_SIZE: usize = BLOOM_UPSAMPLE_FIELD_COUNT.div_ceil(4) * VEC4_STRIDE;

/// Absolute tolerance for the `f32` equality comparisons used by the tests;
/// direct `==` on floating point is intentionally avoided.
#[cfg(test)]
const CMP_EPS: f32 = 1e-6;

/// The classic `smoothstep` Hermite interpolant, clamped to `[0, 1]`.
///
/// Used to turn the raw `radius` scatter control into a soft `[0, 1]` blend
/// between a crisp (nearest) upsample and the full `tent` spread, so the glow
/// width grows smoothly instead of snapping. The denominator is guarded by
/// [`MIN_DENOM`] so a degenerate `edge0 == edge1` band cannot divide by zero.
#[must_use]
fn smoothstep(edge0: f32, edge1: f32, x: f32) -> f32 {
    let denom = edge1 - edge0;
    let safe = if denom.abs() < MIN_DENOM {
        MIN_DENOM
    } else {
        denom
    };
    let t = ((x - edge0) / safe).clamp(0.0, 1.0);
    t * t * (3.0 - 2.0 * t)
}

/// The `[0, 1]` scatter blend for a given upsample `radius`: `0` keeps the
/// upsample crisp (nearest sample), `1` uses the full 3x3 `tent`, and values in
/// between blend the two so `radius` reads as glow width.
#[must_use]
fn scatter(radius: f32) -> f32 {
    smoothstep(0.0, 1.0, radius)
}

/// Linear interpolation of two `RGB` triples: `a + (b - a) * t`.
#[must_use]
fn lerp3(a: [f32; 3], b: [f32; 3], t: f32) -> [f32; 3] {
    [
        a[0] + (b[0] - a[0]) * t,
        a[1] + (b[1] - a[1]) * t,
        a[2] + (b[2] - a[2]) * t,
    ]
}

/// Clamps a `tent` tap coordinate to the valid `[0, extent - 1]` range.
///
/// `tap` is the tap index `0 -> -1`, `1 -> 0`, `2 -> +1`; the arithmetic uses
/// saturating operations so the clamp-to-edge boundary rule never underflows or
/// runs past the last texel. `extent` is assumed non-zero (callers guard empty
/// images before calling).
#[must_use]
fn clamp_tap(center: usize, tap: usize, extent: usize) -> usize {
    match tap {
        0 => center.saturating_sub(1),
        2 => (center + 1).min(extent - 1),
        _ => center.min(extent - 1),
    }
}

/// A single linear `HDR` `RGB` `mip` level: a row-major grid of pixels.
///
/// The composite chain is handed a slice of these, finest first and coarsest
/// last, and returns a new level at the finest resolution.
#[derive(Clone, Debug, PartialEq)]
pub struct MipImage {
    /// Width in texels.
    pub width: usize,
    /// Height in texels.
    pub height: usize,
    /// Row-major `width * height` linear `HDR` `RGB` pixels.
    pub pixels: Vec<[f32; 3]>,
}

impl MipImage {
    /// Builds a `mip` level from its dimensions and row-major pixels.
    ///
    /// The pixel count must equal `width * height`; a mismatch is a programming
    /// error and panics with a clear message rather than silently truncating.
    #[must_use]
    pub fn new(width: usize, height: usize, pixels: Vec<[f32; 3]>) -> Self {
        assert_eq!(
            pixels.len(),
            width.saturating_mul(height),
            "pixel count must equal width * height"
        );
        Self {
            width,
            height,
            pixels,
        }
    }

    /// A black `mip` level of the given dimensions (all pixels zero).
    #[must_use]
    pub fn black(width: usize, height: usize) -> Self {
        let pixels = alloc::vec![[0.0f32; 3]; width.saturating_mul(height)];
        Self {
            width,
            height,
            pixels,
        }
    }

    /// Whether the level holds no texels.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.width == 0 || self.height == 0
    }

    /// Reads the pixel at `(x, y)`, returning black for out-of-range
    /// coordinates so no caller can index past the grid.
    #[must_use]
    pub fn pixel(&self, x: usize, y: usize) -> [f32; 3] {
        if x >= self.width || y >= self.height {
            return [0.0; 3];
        }
        self.pixels[y * self.width + x]
    }
}

/// Samples a `mip` level with the 3x3 `tent` kernel centered on `(cx, cy)`.
///
/// The nine taps carry the separable `[1, 2, 1]` weights (outer product summing
/// to `16`) and are divided by [`TENT_NORM`] so the kernel weights sum to
/// exactly `1` and a constant image is reproduced unchanged. Taps that fall off
/// the edge are clamped to the nearest texel (clamp-to-edge), matching the
/// `GPU` sampler's addressing mode. An empty image samples to black.
#[must_use]
pub fn tent_filter_9tap(img: &MipImage, cx: usize, cy: usize) -> [f32; 3] {
    if img.is_empty() {
        return [0.0; 3];
    }
    let mut acc = [0.0f32; 3];
    for (ty, &wy) in TENT_1D.iter().enumerate() {
        let sy = clamp_tap(cy, ty, img.height);
        for (tx, &wx) in TENT_1D.iter().enumerate() {
            let sx = clamp_tap(cx, tx, img.width);
            let w = wx * wy;
            let p = img.pixel(sx, sy);
            acc[0] += p[0] * w;
            acc[1] += p[1] * w;
            acc[2] += p[2] * w;
        }
    }
    [acc[0] / TENT_NORM, acc[1] / TENT_NORM, acc[2] / TENT_NORM]
}

/// Upsamples the coarse `low` level and adds it, scaled by `weight`, onto the
/// finer `high` level, producing a new level at `high`'s resolution.
///
/// For each `high` texel the matching `low` texel is found by halving the
/// coordinate (the pyramid halves resolution per level), then `radius` selects,
/// via [`scatter`], how far to blend from that crisp sample toward the full
/// 3x3 [`tent_filter_9tap`] spread. The blended upsample is multiplied by
/// `weight` (the per-`mip` scatter gain) and added onto the existing `high`
/// pixel, so a larger `weight` can only brighten a pixel, never darken it.
#[must_use]
pub fn upsample_add(low: &MipImage, high: &MipImage, radius: f32, weight: f32) -> MipImage {
    let mut out = high.pixels.clone();
    let spread = scatter(radius);
    let low_w = low.width.saturating_sub(1);
    let low_h = low.height.saturating_sub(1);
    for y in 0..high.height {
        let ly = (y / 2).min(low_h);
        for x in 0..high.width {
            let lx = (x / 2).min(low_w);
            let sharp = low.pixel(lx, ly);
            let wide = tent_filter_9tap(low, lx, ly);
            let up = lerp3(sharp, wide, spread);
            let idx = y * high.width + x;
            out[idx][0] += up[0] * weight;
            out[idx][1] += up[1] * weight;
            out[idx][2] += up[2] * weight;
        }
    }
    MipImage::new(high.width, high.height, out)
}

/// The per-`mip` additive weight chain for the upsample composite.
///
/// Coarser levels represent wider, dimmer blur and contribute less, so the
/// chain is a monotonically non-increasing geometric series. It is generated by
/// repeated multiplication by a *rational* ratio `num / den` (`num <= den`)
/// rather than `powf`, keeping the whole contract free of transcendental
/// functions.
#[derive(Clone, Debug, PartialEq)]
pub struct MipWeights {
    weights: Vec<f32>,
}

impl MipWeights {
    /// Builds a geometric weight chain of `mip_count` entries where entry `0`
    /// is `1.0` and each subsequent entry is the previous one times the
    /// rational ratio `ratio_num / ratio_den`.
    ///
    /// `mip_count` is floored to `1` (a single-level pyramid still needs a
    /// weight) and `ratio_den` is floored to `1` to guard the division. With
    /// `ratio_num <= ratio_den` the series is non-increasing, matching the
    /// physical fall-off of ever-coarser blurs.
    #[must_use]
    pub fn geometric(mip_count: usize, ratio_num: u32, ratio_den: u32) -> Self {
        let count = mip_count.max(1);
        let den = ratio_den.max(1);
        let ratio = ratio_num as f32 / den as f32;
        let mut weights = Vec::with_capacity(count);
        let mut current = 1.0f32;
        for _ in 0..count {
            weights.push(current);
            current *= ratio;
        }
        Self { weights }
    }

    /// The weight for `mip` level `level`, or `None` when out of range.
    #[must_use]
    pub fn weight(&self, level: usize) -> Option<f32> {
        self.weights.get(level).copied()
    }

    /// The weight chain as a slice, finest level first.
    #[must_use]
    pub fn as_slice(&self) -> &[f32] {
        &self.weights
    }

    /// The number of levels in the chain.
    #[must_use]
    pub fn len(&self) -> usize {
        self.weights.len()
    }

    /// Whether the chain has no levels.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.weights.is_empty()
    }

    /// The sum of every weight in the chain; the additive composite's total
    /// gain relative to a single unit-bright input, useful for bounding the
    /// composited energy.
    #[must_use]
    pub fn sum(&self) -> f32 {
        self.weights.iter().copied().sum()
    }
}

/// Progressively composites a `mip` pyramid from coarsest to finest.
///
/// `mips` is ordered finest-first (index `0`) to coarsest-last. Starting from
/// the coarsest level, each step [`upsample_add`]s the running accumulator onto
/// the next-finer level with that level's [`MipWeights`] entry, so wider,
/// dimmer blurs are laid down first and sharper detail is added last. The
/// result is a new level at the finest resolution. Returns `None` for an empty
/// pyramid.
#[must_use]
pub fn composite_chain(mips: &[MipImage], weights: &MipWeights, radius: f32) -> Option<MipImage> {
    let coarsest = mips.last()?;
    let mut acc = coarsest.clone();
    let n = mips.len();
    for level in (0..n - 1).rev() {
        let w = weights.weight(level).unwrap_or(0.0);
        acc = upsample_add(&acc, &mips[level], radius, w);
    }
    Some(acc)
}

/// `std430` parameters for the `bloom` upsample composite pass
/// (design §16-§21).
///
/// `radius` is the glow-width scatter control (blend toward the full `tent`
/// spread), `intensity` is the global gain applied to the composited glow, and
/// `mip_count` is the number of pyramid levels the composite walks.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BloomUpsampleParams {
    /// Glow-width scatter control (blend toward the full 3x3 `tent`).
    pub radius: f32,
    /// Global gain applied to the composited glow.
    pub intensity: f32,
    /// Number of pyramid `mip` levels the composite walks.
    pub mip_count: u32,
}

impl BloomUpsampleParams {
    /// Builds a parameter set, clamping `radius` and `intensity` to be
    /// non-negative and `mip_count` to at least `1` so the pass stays defined.
    #[must_use]
    pub fn new(radius: f32, intensity: f32, mip_count: u32) -> Self {
        Self {
            radius: radius.max(0.0),
            intensity: intensity.max(0.0),
            mip_count: mip_count.max(1),
        }
    }

    /// Byte size of the per-`mip` resolution table a `GPU` upsample kernel
    /// binds: one `vec2<u32>` (width, height) per level.
    #[must_use]
    pub fn mip_resolution_table_bytes(&self) -> usize {
        let count = usize::try_from(self.mip_count).expect("mip_count fits in usize");
        storage_bytes(VEC2_STRIDE, count)
    }

    /// Byte size of the per-`mip` weight table a `GPU` upsample kernel binds:
    /// one scalar (`f32`, a `u32`-stride slot) per level.
    #[must_use]
    pub fn mip_weight_table_bytes(&self) -> usize {
        let count = usize::try_from(self.mip_count).expect("mip_count fits in usize");
        storage_bytes(U32_STRIDE, count)
    }

    /// Packs the parameters into their `std430` uniform-block byte layout.
    ///
    /// `radius` and `intensity` fill the first two scalar slots of a single
    /// `vec4`, `mip_count` fills the third as a little-endian `u32`, and the
    /// one-scalar padding tail stays zero so the block is a whole number of
    /// `vec4` slots.
    #[must_use]
    pub fn to_std430(&self) -> [u8; BLOOM_UPSAMPLE_STD430_SIZE] {
        let mut bytes = [0u8; BLOOM_UPSAMPLE_STD430_SIZE];
        bytes[0..4].copy_from_slice(&self.radius.to_le_bytes());
        bytes[4..8].copy_from_slice(&self.intensity.to_le_bytes());
        bytes[8..12].copy_from_slice(&self.mip_count.to_le_bytes());
        bytes
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn approx(a: f32, b: f32) -> bool {
        (a - b).abs() < CMP_EPS
    }

    fn approx3(a: [f32; 3], b: [f32; 3]) -> bool {
        approx(a[0], b[0]) && approx(a[1], b[1]) && approx(a[2], b[2])
    }

    fn uniform(width: usize, height: usize, v: f32) -> MipImage {
        MipImage::new(width, height, alloc::vec![[v, v, v]; width * height])
    }

    #[test]
    fn tent_kernel_weights_sum_to_one() {
        // A constant image is reproduced exactly only if the kernel weights sum
        // to one; sample well inside the image so no clamping is involved.
        let img = uniform(5, 5, 0.5);
        let out = tent_filter_9tap(&img, 2, 2);
        assert!(approx3(out, [0.5, 0.5, 0.5]));
    }

    #[test]
    fn tent_reproduces_constant_image_everywhere() {
        let img = uniform(4, 3, 1.25);
        for y in 0..img.height {
            for x in 0..img.width {
                assert!(approx3(tent_filter_9tap(&img, x, y), [1.25, 1.25, 1.25]));
            }
        }
    }

    #[test]
    fn tent_clamps_at_a_single_pixel_image() {
        // Every tap clamps to the one texel, so the result equals it and the
        // clamp-to-edge boundary rule never indexes out of range.
        let img = uniform(1, 1, 3.0);
        assert!(approx3(tent_filter_9tap(&img, 0, 0), [3.0, 3.0, 3.0]));
    }

    #[test]
    fn tent_clamps_at_a_corner() {
        // Uniform image: even at the corner, where four taps clamp back onto
        // the grid, a correct clamp keeps the constant value.
        let img = uniform(3, 3, 2.0);
        assert!(approx3(tent_filter_9tap(&img, 0, 0), [2.0, 2.0, 2.0]));
    }

    #[test]
    fn tent_spreads_a_central_impulse_to_its_weights() {
        // A single bright center pixel: the center tap carries weight
        // 2 * 2 / 16 = 0.25 of it back.
        let mut img = MipImage::black(3, 3);
        img.pixels[4] = [1.0, 1.0, 1.0];
        let center = tent_filter_9tap(&img, 1, 1);
        assert!(approx(center[0], 4.0 / 16.0));
        // An edge-centered sample sees the impulse at an off-center tap
        // (weight 2 * 1 / 16 = 0.125) after clamping.
        let edge = tent_filter_9tap(&img, 0, 1);
        assert!(approx(edge[0], 2.0 / 16.0));
    }

    #[test]
    fn tent_of_empty_image_is_black() {
        let img = MipImage::black(0, 0);
        assert!(approx3(tent_filter_9tap(&img, 0, 0), [0.0, 0.0, 0.0]));
    }

    #[test]
    fn upsample_add_is_monotonic_in_weight() {
        let low = uniform(1, 1, 4.0);
        let high = uniform(2, 2, 0.0);
        let a = upsample_add(&low, &high, 1.0, 0.25);
        let b = upsample_add(&low, &high, 1.0, 0.75);
        for (pa, pb) in a.pixels.iter().zip(b.pixels.iter()) {
            assert!(pb[0] >= pa[0] - CMP_EPS);
            assert!(pb[1] >= pa[1] - CMP_EPS);
            assert!(pb[2] >= pa[2] - CMP_EPS);
        }
    }

    #[test]
    fn upsample_add_zero_weight_leaves_high_unchanged() {
        let low = uniform(1, 1, 9.0);
        let high = uniform(2, 2, 0.5);
        let out = upsample_add(&low, &high, 1.0, 0.0);
        assert_eq!(out.width, high.width);
        assert_eq!(out.height, high.height);
        for p in &out.pixels {
            assert!(approx3(*p, [0.5, 0.5, 0.5]));
        }
    }

    #[test]
    fn upsample_add_preserves_high_resolution() {
        let low = uniform(2, 2, 1.0);
        let high = uniform(4, 3, 0.0);
        let out = upsample_add(&low, &high, 0.5, 1.0);
        assert_eq!(out.width, 4);
        assert_eq!(out.height, 3);
        assert_eq!(out.pixels.len(), 12);
    }

    #[test]
    fn upsample_radius_widens_a_hotspot() {
        // A low level with one hot texel: a crisp (radius 0) upsample keeps the
        // energy concentrated, a wide (radius 1) upsample bleeds it outward via
        // the tent, so cold neighbors get strictly more light.
        let mut low = MipImage::black(2, 2);
        low.pixels[0] = [8.0, 8.0, 8.0];
        let high = MipImage::black(4, 4);
        let sharp = upsample_add(&low, &high, 0.0, 1.0);
        let wide = upsample_add(&low, &high, 1.0, 1.0);
        // Texel (2, 0) maps to low (1, 0), which is cold under the sharp path
        // but picks up the hotspot through the tent under the wide path.
        let idx = 2;
        assert!(approx(sharp.pixels[idx][0], 0.0));
        assert!(wide.pixels[idx][0] > sharp.pixels[idx][0] + CMP_EPS);
    }

    #[test]
    fn mip_weights_first_entry_is_one() {
        let w = MipWeights::geometric(4, 1, 2);
        assert!(approx(w.weight(0).unwrap(), 1.0));
    }

    #[test]
    fn mip_weights_follow_the_rational_ratio() {
        // ratio 1/2: 1, 0.5, 0.25, 0.125.
        let w = MipWeights::geometric(4, 1, 2);
        assert!(approx(w.weight(1).unwrap(), 0.5));
        assert!(approx(w.weight(2).unwrap(), 0.25));
        assert!(approx(w.weight(3).unwrap(), 0.125));
    }

    #[test]
    fn mip_weights_are_non_increasing() {
        let w = MipWeights::geometric(6, 2, 3);
        let slice = w.as_slice();
        for pair in slice.windows(2) {
            assert!(pair[1] <= pair[0] + CMP_EPS);
        }
    }

    #[test]
    fn mip_weights_length_and_guards() {
        assert_eq!(MipWeights::geometric(5, 1, 2).len(), 5);
        // mip_count floored to 1, ratio_den floored to 1 (no divide by zero).
        let single = MipWeights::geometric(0, 1, 0);
        assert_eq!(single.len(), 1);
        assert!(!single.is_empty());
        assert!(approx(single.weight(0).unwrap(), 1.0));
    }

    #[test]
    fn mip_weights_sum_matches_manual_total() {
        let w = MipWeights::geometric(3, 1, 2);
        assert!(approx(w.sum(), 1.0 + 0.5 + 0.25));
    }

    #[test]
    fn composite_of_empty_pyramid_is_none() {
        let weights = MipWeights::geometric(1, 1, 2);
        assert!(composite_chain(&[], &weights, 1.0).is_none());
    }

    #[test]
    fn composite_of_single_mip_returns_that_mip() {
        let only = uniform(4, 4, 0.7);
        let weights = MipWeights::geometric(1, 1, 2);
        let out = composite_chain(core::slice::from_ref(&only), &weights, 1.0).unwrap();
        assert_eq!(out.width, 4);
        assert_eq!(out.height, 4);
        for p in &out.pixels {
            assert!(approx3(*p, [0.7, 0.7, 0.7]));
        }
    }

    #[test]
    fn composite_result_has_the_finest_resolution() {
        let fine = MipImage::black(4, 4);
        let coarse = MipImage::black(2, 2);
        let weights = MipWeights::geometric(2, 1, 2);
        let out = composite_chain(&[fine, coarse], &weights, 1.0).unwrap();
        assert_eq!(out.width, 4);
        assert_eq!(out.height, 4);
    }

    #[test]
    fn composite_conserves_energy_on_a_uniform_pyramid() {
        // On a uniform-value pyramid the tent, sharp and blend all return the
        // same constant, so the composite reduces to a closed recurrence we can
        // reproduce exactly: acc = base + weight[level] * acc.
        let base = 1.0f32;
        let fine = uniform(4, 4, base);
        let coarse = uniform(2, 2, base);
        let weights = MipWeights::geometric(2, 1, 2);
        let out = composite_chain(&[fine, coarse], &weights, 1.0).unwrap();
        let expected = base + weights.weight(0).unwrap() * base;
        for p in &out.pixels {
            assert!(approx3(*p, [expected, expected, expected]));
        }
    }

    #[test]
    fn composite_is_bounded_above_and_brightens() {
        // Non-negative uniform pyramid: the additive glow can only brighten the
        // finest level, and every channel stays at or below the closed-form
        // upper bound base * (1 + sum(finer weights)).
        let base = 2.0f32;
        let fine = uniform(4, 4, base);
        let mid = uniform(2, 2, base);
        let coarse = uniform(1, 1, base);
        let weights = MipWeights::geometric(3, 1, 2);
        let out = composite_chain(&[fine, mid, coarse], &weights, 1.0).unwrap();
        let finer_weight_sum = weights.weight(0).unwrap() + weights.weight(1).unwrap();
        let upper = base * (1.0 + finer_weight_sum);
        for p in &out.pixels {
            assert!(p[0] >= base - CMP_EPS);
            assert!(p[0] <= upper + CMP_EPS);
        }
    }

    #[test]
    fn smoothstep_is_clamped_and_monotonic() {
        assert!(approx(smoothstep(0.0, 1.0, -1.0), 0.0));
        assert!(approx(smoothstep(0.0, 1.0, 2.0), 1.0));
        assert!(approx(smoothstep(0.0, 1.0, 0.5), 0.5));
        let mut prev = smoothstep(0.0, 1.0, 0.0);
        for i in 1..=10 {
            let x = i as f32 / 10.0;
            let cur = smoothstep(0.0, 1.0, x);
            assert!(cur >= prev - CMP_EPS);
            prev = cur;
        }
    }

    #[test]
    fn smoothstep_guards_a_degenerate_band() {
        // edge0 == edge1 would divide by zero without the MIN_DENOM guard; the
        // result must stay finite and clamped.
        let v = smoothstep(1.0, 1.0, 1.0);
        assert!(v.is_finite());
        assert!((0.0..=1.0).contains(&v));
    }

    #[test]
    fn std430_size_is_a_whole_vec4_block() {
        assert_eq!(BLOOM_UPSAMPLE_STD430_SIZE, VEC4_STRIDE);
        assert_eq!(BLOOM_UPSAMPLE_STD430_SIZE % VEC4_STRIDE, 0);
        assert_eq!(BLOOM_UPSAMPLE_STD430_SIZE, storage_bytes(VEC4_STRIDE, 1));
    }

    #[test]
    fn std430_round_trips_the_fields() {
        let p = BloomUpsampleParams::new(1.5, 2.25, 6);
        let bytes = p.to_std430();
        assert_eq!(bytes.len(), BLOOM_UPSAMPLE_STD430_SIZE);
        let read_f32 = |i: usize| {
            let mut b = [0u8; 4];
            b.copy_from_slice(&bytes[i * 4..i * 4 + 4]);
            f32::from_le_bytes(b)
        };
        assert!(approx(read_f32(0), 1.5));
        assert!(approx(read_f32(1), 2.25));
        let mut mc = [0u8; 4];
        mc.copy_from_slice(&bytes[8..12]);
        assert_eq!(u32::from_le_bytes(mc), 6);
        // The padding-tail scalar stays zero.
        assert!(approx(read_f32(3), 0.0));
    }

    #[test]
    fn params_new_clamps_into_valid_ranges() {
        let p = BloomUpsampleParams::new(-3.0, -1.0, 0);
        assert!(approx(p.radius, 0.0));
        assert!(approx(p.intensity, 0.0));
        assert_eq!(p.mip_count, 1);
    }

    #[test]
    fn resolution_table_bytes_pack_a_vec2_per_mip() {
        let p = BloomUpsampleParams::new(1.0, 1.0, 5);
        assert_eq!(
            p.mip_resolution_table_bytes(),
            storage_bytes(VEC2_STRIDE, 5)
        );
        assert_eq!(p.mip_resolution_table_bytes(), VEC2_STRIDE * 5);
    }

    #[test]
    fn weight_table_bytes_pack_a_scalar_per_mip() {
        let p = BloomUpsampleParams::new(1.0, 1.0, 5);
        assert_eq!(p.mip_weight_table_bytes(), storage_bytes(U32_STRIDE, 5));
        assert_eq!(p.mip_weight_table_bytes(), U32_STRIDE * 5);
    }
}
