//! Branch-free integer bit-scan and base-2 logarithm via `de Bruijn` sequences.
//!
//! This module is the particle engine's pure-integer answer to "where is the
//! top (or bottom) set bit?" and "what is `floor`/`ceil` of `log2`?". Every
//! routine here is a `const fn` built from shifts, masks, a single integer
//! multiply, and a small lookup table. There is no floating point, no
//! transcendental `log2`, and no `unsafe`: the result is bit-for-bit identical
//! on a scalar `CPU` core, a `GPU` integer pipeline, and inside a `const`
//! context evaluated at compile time.
//!
//! # Why `de Bruijn` instead of `leading_zeros`
//!
//! Rust already exposes `u32::leading_zeros` / `u32::trailing_zeros`, which on
//! most targets lower to a single hardware instruction (`LZCNT` / `TZCNT` /
//! `CLZ`). Those intrinsics are perfect on the host, but a hand-rolled
//! `de Bruijn` scan is the canonical portable fallback for environments with no
//! count-leading-zeros instruction (older shader models, soft-float embedded
//! targets, bignum inner loops). It also documents the exact arithmetic the
//! engine relies on, so the `CPU` reference and a future `GPU` port can be
//! proven equal. We still cross-check against `leading_zeros` in the tests.
//!
//! # The trick
//!
//! A `de Bruijn` sequence `B(2, k)` is a cyclic binary string of length `2^k`
//! in which every length-`k` substring appears exactly once. Encode it as an
//! integer constant; multiplying it by an isolated single bit `1 << p` rotates
//! the sequence by `p` positions, so the top `k` bits become a unique
//! fingerprint of `p`. One lookup table turns that fingerprint back into `p`.
//!
//! For the base-2 logarithm (most-significant set bit, the `MSB`) we first
//! smear the top bit downward with `x |= x >> 1; x |= x >> 2; ...` so the value
//! becomes a clean `2^(k+1) - 1` mask, then multiply by the `de Bruijn`
//! constant. For the trailing-zero scan (least-significant set bit, the `LSB`)
//! we isolate the low bit with `x & x.wrapping_neg()` before multiplying.
//!
//! # Constants
//!
//! * `floor_log2_u32` uses the classic 32-bit `de Bruijn` constant
//!   `0x07C4ACDD` with a 32-entry table (Sean Eron Anderson, "Bit Twiddling
//!   Hacks").
//! * `floor_log2_u64` uses the 64-bit `de Bruijn` constant
//!   `0x03F79D71B4CB0A89` with a 64-entry table.
//! * `trailing_zero_index_u32` uses the 32-bit `de Bruijn` constant
//!   `0x077CB531` with a 32-entry table.
//!
//! Each lookup table was generated by evaluating the shift-and-multiply index
//! formula over every bit position and inverting the resulting permutation; the
//! tests re-derive the answers from the standard library intrinsics.

/// 32-entry decode table for the `MSB` scan driven by `de Bruijn` constant
/// `0x07C4ACDD`. Index `i` holds the bit position whose smeared mask maps to
/// `i` after the multiply-and-shift.
const DE_BRUIJN_LOG2_U32: [u32; 32] = [
    0, 9, 1, 10, 13, 21, 2, 29, 11, 14, 16, 18, 22, 25, 3, 30, 8, 12, 20, 28, 15, 17, 24, 7, 19,
    27, 23, 6, 26, 5, 4, 31,
];

/// 64-entry decode table for the `MSB` scan driven by `de Bruijn` constant
/// `0x03F79D71B4CB0A89`.
const DE_BRUIJN_LOG2_U64: [u64; 64] = [
    0, 47, 1, 56, 48, 27, 2, 60, 57, 49, 41, 37, 28, 16, 3, 61, 54, 58, 35, 52, 50, 42, 21, 44, 38,
    32, 29, 23, 17, 11, 4, 62, 46, 55, 26, 59, 40, 36, 15, 53, 34, 51, 20, 43, 31, 22, 10, 45, 25,
    39, 14, 33, 19, 30, 9, 24, 13, 18, 8, 12, 7, 6, 5, 63,
];

/// 32-entry decode table for the `LSB` scan driven by `de Bruijn` constant
/// `0x077CB531`.
const DE_BRUIJN_TRAILING_U32: [u32; 32] = [
    0, 1, 28, 2, 29, 14, 24, 3, 30, 22, 20, 15, 25, 17, 4, 8, 31, 27, 13, 23, 21, 19, 16, 7, 26,
    12, 18, 6, 11, 5, 10, 9,
];

/// `de Bruijn` multiplier for the 32-bit `MSB` (base-2 logarithm) scan.
const DE_BRUIJN_MUL_LOG2_U32: u32 = 0x07C4_ACDD;

/// `de Bruijn` multiplier for the 64-bit `MSB` (base-2 logarithm) scan.
const DE_BRUIJN_MUL_LOG2_U64: u64 = 0x03F7_9D71_B4CB_0A89;

/// `de Bruijn` multiplier for the 32-bit `LSB` (trailing-zero) scan.
const DE_BRUIJN_MUL_TRAILING_U32: u32 = 0x077C_B531;

/// Returns `floor(log2(x))`, i.e. the index of the most-significant set bit of
/// `x`, computed with a `de Bruijn` multiply-and-lookup over the `u32` domain.
///
/// By convention `floor_log2_u32(0) == 0`: zero has no set bit, so there is no
/// true base-2 logarithm, and `0` is returned as a saturating stand-in. Callers
/// that must distinguish the zero case should test `x == 0` separately.
///
/// The input is first smeared into a `2^(k+1) - 1` mask so the single multiply
/// by `0x07C4ACDD` lands the `MSB` fingerprint in the top five bits.
#[must_use]
pub const fn floor_log2_u32(x: u32) -> u32 {
    if x == 0 {
        return 0;
    }
    let mut v = x;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    DE_BRUIJN_LOG2_U32[(v.wrapping_mul(DE_BRUIJN_MUL_LOG2_U32) >> 27) as usize]
}

/// Returns `floor(log2(x))`, i.e. the index of the most-significant set bit of
/// `x`, computed with a `de Bruijn` multiply-and-lookup over the `u64` domain.
///
/// By convention `floor_log2_u64(0) == 0` for the same reason as the `u32`
/// variant: zero has no set bit and `0` is returned as a saturating stand-in.
///
/// The input is smeared into a `2^(k+1) - 1` mask, then multiplied by the
/// 64-bit `de Bruijn` constant `0x03F79D71B4CB0A89`; the top six bits index the
/// decode table.
#[must_use]
pub const fn floor_log2_u64(x: u64) -> u64 {
    if x == 0 {
        return 0;
    }
    let mut v = x;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    v |= v >> 32;
    DE_BRUIJN_LOG2_U64[(v.wrapping_mul(DE_BRUIJN_MUL_LOG2_U64) >> 58) as usize]
}

/// Returns `ceil(log2(x))`, the smallest `n` with `2^n >= x`, over the `u32`
/// domain.
///
/// Both `0` and `1` return `0`: there is no positive exponent below `1`, and
/// `2^0 == 1` already covers `x == 1`. For `x >= 2` the result is
/// `floor_log2_u32(x - 1) + 1`, which correctly yields `n` on exact powers of
/// two and rounds the rest up.
#[must_use]
pub const fn ceil_log2_u32(x: u32) -> u32 {
    if x <= 1 {
        return 0;
    }
    floor_log2_u32(x - 1) + 1
}

/// Returns `ceil(log2(x))`, the smallest `n` with `2^n >= x`, over the `u64`
/// domain.
///
/// Both `0` and `1` return `0`; for `x >= 2` the result is
/// `floor_log2_u64(x - 1) + 1`.
#[must_use]
pub const fn ceil_log2_u64(x: u64) -> u64 {
    if x <= 1 {
        return 0;
    }
    floor_log2_u64(x - 1) + 1
}

/// Returns `true` when `x` is a power of two (exactly one set bit).
///
/// Zero is not a power of two, so `is_power_of_two_u32(0) == false`. The test
/// `x != 0 && (x & (x - 1)) == 0` clears the lowest set bit and checks that
/// nothing remains.
#[must_use]
pub const fn is_power_of_two_u32(x: u32) -> bool {
    x != 0 && (x & (x - 1)) == 0
}

/// Returns `true` when `x` is a power of two (exactly one set bit), over the
/// `u64` domain. Zero returns `false`.
#[must_use]
pub const fn is_power_of_two_u64(x: u64) -> bool {
    x != 0 && (x & (x - 1)) == 0
}

/// Returns the smallest power of two that is greater than or equal to `x`, over
/// the `u32` domain.
///
/// `next_power_of_two_u32(0) == 1`. The value is rounded up by decrementing,
/// smearing every lower bit beneath the `MSB`, then incrementing. The result is
/// only defined while it fits in `u32`; inputs above `2^31` would overflow and
/// are outside the contract.
#[must_use]
pub const fn next_power_of_two_u32(x: u32) -> u32 {
    if x <= 1 {
        return 1;
    }
    let mut v = x - 1;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    v + 1
}

/// Returns the smallest power of two that is greater than or equal to `x`, over
/// the `u64` domain.
///
/// `next_power_of_two_u64(0) == 1`. Inputs above `2^63` would overflow and are
/// outside the contract.
#[must_use]
pub const fn next_power_of_two_u64(x: u64) -> u64 {
    if x <= 1 {
        return 1;
    }
    let mut v = x - 1;
    v |= v >> 1;
    v |= v >> 2;
    v |= v >> 4;
    v |= v >> 8;
    v |= v >> 16;
    v |= v >> 32;
    v + 1
}

/// Returns the index of the least-significant set bit (`LSB`) of `x`, i.e. the
/// count of trailing zero bits, computed with a `de Bruijn` multiply-and-lookup
/// over the `u32` domain.
///
/// By convention `trailing_zero_index_u32(0) == 32`: zero has no set bit, so
/// every one of its 32 bits is a trailing zero. The low bit is isolated with
/// `x & x.wrapping_neg()` before the multiply by `0x077CB531`.
#[must_use]
pub const fn trailing_zero_index_u32(x: u32) -> u32 {
    if x == 0 {
        return 32;
    }
    let isolated = x & x.wrapping_neg();
    DE_BRUIJN_TRAILING_U32[(isolated.wrapping_mul(DE_BRUIJN_MUL_TRAILING_U32) >> 27) as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn floor_log2_u32_known_small() {
        assert_eq!(floor_log2_u32(1), 0);
        assert_eq!(floor_log2_u32(2), 1);
        assert_eq!(floor_log2_u32(3), 1);
        assert_eq!(floor_log2_u32(4), 2);
        assert_eq!(floor_log2_u32(5), 2);
        assert_eq!(floor_log2_u32(7), 2);
        assert_eq!(floor_log2_u32(8), 3);
    }

    #[test]
    fn floor_log2_u32_byte_boundaries() {
        assert_eq!(floor_log2_u32(255), 7);
        assert_eq!(floor_log2_u32(256), 8);
        assert_eq!(floor_log2_u32(257), 8);
        assert_eq!(floor_log2_u32(511), 8);
        assert_eq!(floor_log2_u32(512), 9);
    }

    #[test]
    fn floor_log2_u32_max_and_zero() {
        assert_eq!(floor_log2_u32(u32::MAX), 31);
        assert_eq!(floor_log2_u32(0), 0);
        assert_eq!(floor_log2_u32(1 << 31), 31);
    }

    #[test]
    fn floor_log2_u32_every_power_of_two() {
        let mut k = 0u32;
        while k < 32 {
            assert_eq!(floor_log2_u32(1u32 << k), k);
            k += 1;
        }
    }

    #[test]
    fn floor_log2_u32_just_below_powers() {
        let mut k = 2u32;
        while k < 32 {
            let p = 1u32 << k;
            assert_eq!(floor_log2_u32(p - 1), k - 1);
            assert_eq!(floor_log2_u32(p + 1), k);
            k += 1;
        }
    }

    #[test]
    fn floor_log2_u32_cross_check_intrinsic_dense() {
        let mut x = 1u32;
        while x <= 100_000 {
            assert_eq!(floor_log2_u32(x), 31 - x.leading_zeros());
            x += 1;
        }
    }

    #[test]
    fn floor_log2_u32_cross_check_lcg() {
        let mut state = 0x1234_5678u32;
        let mut iter = 0u32;
        while iter < 20_000 {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            let x = state | 1;
            assert_eq!(floor_log2_u32(x), 31 - x.leading_zeros());
            iter += 1;
        }
    }

    #[test]
    fn floor_log2_u64_known_small() {
        assert_eq!(floor_log2_u64(1), 0);
        assert_eq!(floor_log2_u64(2), 1);
        assert_eq!(floor_log2_u64(3), 1);
        assert_eq!(floor_log2_u64(4), 2);
        assert_eq!(floor_log2_u64(255), 7);
        assert_eq!(floor_log2_u64(256), 8);
    }

    #[test]
    fn floor_log2_u64_large_values() {
        assert_eq!(floor_log2_u64(u64::MAX), 63);
        assert_eq!(floor_log2_u64(1u64 << 63), 63);
        assert_eq!(floor_log2_u64((1u64 << 40) + 123), 40);
        assert_eq!(floor_log2_u64(0), 0);
    }

    #[test]
    fn floor_log2_u64_every_power_of_two() {
        let mut k = 0u64;
        while k < 64 {
            assert_eq!(floor_log2_u64(1u64 << k), k);
            k += 1;
        }
    }

    #[test]
    fn floor_log2_u64_cross_check_intrinsic_dense() {
        let mut x = 1u64;
        while x <= 200_000 {
            assert_eq!(floor_log2_u64(x), u64::from(63 - x.leading_zeros()));
            x += 1;
        }
    }

    #[test]
    fn floor_log2_u64_cross_check_lcg() {
        let mut state = 0x9E37_79B9_7F4A_7C15u64;
        let mut iter = 0u32;
        while iter < 20_000 {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            let x = state | 1;
            assert_eq!(floor_log2_u64(x), u64::from(63 - x.leading_zeros()));
            iter += 1;
        }
    }

    #[test]
    fn ceil_log2_u32_known() {
        assert_eq!(ceil_log2_u32(0), 0);
        assert_eq!(ceil_log2_u32(1), 0);
        assert_eq!(ceil_log2_u32(2), 1);
        assert_eq!(ceil_log2_u32(3), 2);
        assert_eq!(ceil_log2_u32(4), 2);
        assert_eq!(ceil_log2_u32(5), 3);
        assert_eq!(ceil_log2_u32(8), 3);
        assert_eq!(ceil_log2_u32(9), 4);
    }

    #[test]
    fn ceil_log2_u32_powers_and_cross_check() {
        let mut k = 0u32;
        while k < 31 {
            assert_eq!(ceil_log2_u32(1u32 << k), k);
            k += 1;
        }
        let mut x = 2u32;
        while x <= 50_000 {
            let expected = 32 - (x - 1).leading_zeros();
            assert_eq!(ceil_log2_u32(x), expected);
            x += 1;
        }
    }

    #[test]
    fn ceil_log2_u64_known_and_cross_check() {
        assert_eq!(ceil_log2_u64(0), 0);
        assert_eq!(ceil_log2_u64(1), 0);
        assert_eq!(ceil_log2_u64(5), 3);
        assert_eq!(ceil_log2_u64(8), 3);
        assert_eq!(ceil_log2_u64(9), 4);
        assert_eq!(ceil_log2_u64(1u64 << 63), 63);
        let mut x = 2u64;
        while x <= 50_000 {
            let expected = u64::from(32 - (x as u32 - 1).leading_zeros());
            assert_eq!(ceil_log2_u64(x), expected);
            x += 1;
        }
    }

    #[test]
    fn is_power_of_two_u32_known() {
        assert!(!is_power_of_two_u32(0));
        assert!(is_power_of_two_u32(1));
        assert!(is_power_of_two_u32(2));
        assert!(!is_power_of_two_u32(3));
        assert!(is_power_of_two_u32(4));
        assert!(!is_power_of_two_u32(6));
        assert!(is_power_of_two_u32(1 << 31));
        assert!(!is_power_of_two_u32(u32::MAX));
    }

    #[test]
    fn is_power_of_two_u32_cross_check_intrinsic() {
        let mut x = 0u32;
        while x <= 100_000 {
            assert_eq!(is_power_of_two_u32(x), x.is_power_of_two());
            x += 1;
        }
    }

    #[test]
    fn is_power_of_two_u64_known_and_cross_check() {
        assert!(!is_power_of_two_u64(0));
        assert!(is_power_of_two_u64(1));
        assert!(is_power_of_two_u64(1u64 << 63));
        assert!(!is_power_of_two_u64(u64::MAX));
        let mut x = 0u64;
        while x <= 100_000 {
            assert_eq!(is_power_of_two_u64(x), x.is_power_of_two());
            x += 1;
        }
    }

    #[test]
    fn next_power_of_two_u32_known() {
        assert_eq!(next_power_of_two_u32(0), 1);
        assert_eq!(next_power_of_two_u32(1), 1);
        assert_eq!(next_power_of_two_u32(2), 2);
        assert_eq!(next_power_of_two_u32(3), 4);
        assert_eq!(next_power_of_two_u32(5), 8);
        assert_eq!(next_power_of_two_u32(1023), 1024);
        assert_eq!(next_power_of_two_u32(1024), 1024);
        assert_eq!(next_power_of_two_u32(1u32 << 31), 1u32 << 31);
    }

    #[test]
    fn next_power_of_two_u32_cross_check_intrinsic() {
        let mut x = 0u32;
        while x <= 100_000 {
            assert_eq!(next_power_of_two_u32(x), x.next_power_of_two());
            x += 1;
        }
    }

    #[test]
    fn next_power_of_two_u64_known_and_cross_check() {
        assert_eq!(next_power_of_two_u64(0), 1);
        assert_eq!(next_power_of_two_u64(1), 1);
        assert_eq!(next_power_of_two_u64(3), 4);
        assert_eq!(next_power_of_two_u64(1u64 << 62), 1u64 << 62);
        let mut x = 0u64;
        while x <= 100_000 {
            assert_eq!(next_power_of_two_u64(x), x.next_power_of_two());
            x += 1;
        }
    }

    #[test]
    fn trailing_zero_index_u32_known() {
        assert_eq!(trailing_zero_index_u32(0), 32);
        assert_eq!(trailing_zero_index_u32(1), 0);
        assert_eq!(trailing_zero_index_u32(2), 1);
        assert_eq!(trailing_zero_index_u32(3), 0);
        assert_eq!(trailing_zero_index_u32(4), 2);
        assert_eq!(trailing_zero_index_u32(8), 3);
        assert_eq!(trailing_zero_index_u32(12), 2);
        assert_eq!(trailing_zero_index_u32(1 << 31), 31);
    }

    #[test]
    fn trailing_zero_index_u32_every_single_bit() {
        let mut k = 0u32;
        while k < 32 {
            assert_eq!(trailing_zero_index_u32(1u32 << k), k);
            k += 1;
        }
    }

    #[test]
    fn trailing_zero_index_u32_cross_check_intrinsic() {
        let mut x = 1u32;
        while x <= 100_000 {
            assert_eq!(trailing_zero_index_u32(x), x.trailing_zeros());
            x += 1;
        }
    }

    #[test]
    fn trailing_zero_index_u32_cross_check_lcg() {
        let mut state = 0x0BAD_F00Du32;
        let mut iter = 0u32;
        while iter < 20_000 {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            if state == 0 {
                iter += 1;
                continue;
            }
            assert_eq!(trailing_zero_index_u32(state), state.trailing_zeros());
            iter += 1;
        }
    }

    #[test]
    fn tables_are_bijective_permutations() {
        let mut seen32 = 0u32;
        for &v in &DE_BRUIJN_LOG2_U32 {
            assert!(v < 32);
            seen32 |= 1 << v;
        }
        assert_eq!(seen32, u32::MAX);

        let mut seen_tz = 0u32;
        for &v in &DE_BRUIJN_TRAILING_U32 {
            assert!(v < 32);
            seen_tz |= 1 << v;
        }
        assert_eq!(seen_tz, u32::MAX);

        let mut seen64 = 0u64;
        for &v in &DE_BRUIJN_LOG2_U64 {
            assert!(v < 64);
            seen64 |= 1u64 << v;
        }
        assert_eq!(seen64, u64::MAX);
    }

    #[test]
    fn floor_and_ceil_agree_on_powers_of_two() {
        let mut k = 0u32;
        while k < 31 {
            let p = 1u32 << k;
            assert_eq!(floor_log2_u32(p), ceil_log2_u32(p));
            assert_eq!(floor_log2_u32(p), k);
            k += 1;
        }
    }

    #[test]
    fn const_evaluation_in_const_context() {
        const FLOOR: u32 = floor_log2_u32(1000);
        const CEIL: u32 = ceil_log2_u32(1000);
        const NPOT: u32 = next_power_of_two_u32(1000);
        const TZ: u32 = trailing_zero_index_u32(1000);
        const POW: bool = is_power_of_two_u32(1024);
        const FLOOR64: u64 = floor_log2_u64(1u64 << 50);
        assert_eq!(FLOOR, 9);
        assert_eq!(CEIL, 10);
        assert_eq!(NPOT, 1024);
        assert_eq!(TZ, 3);
        assert!(POW);
        assert_eq!(FLOOR64, 50);
    }
}
