//! Zeckendorf decomposition and Fibonacci universal variable-length coding,
//! implemented with pure integer recurrence on the `CPU`.
//!
//! Zeckendorf's theorem states that every positive integer has a unique
//! representation as a sum of non-consecutive Fibonacci numbers, drawn from the
//! values `F(2)=1`, `F(3)=2`, `F(4)=3`, `F(5)=5`, ... and selected greedily
//! from the largest value downward. The Fibonacci code is a universal
//! prefix-free code: the Zeckendorf bits are written from the smallest value to
//! the largest and a terminating `1` bit is appended, so every codeword ends
//! with the pattern `11`. That pattern cannot appear earlier because the
//! Zeckendorf bits are never adjacent, which makes a stream of codewords
//! self-delimiting.
//!
//! ## Boundaries
//!
//! This module is a deliberately separate topic from `fibonacci_hash`, which
//! performs multiplicative hashing with the golden-ratio constant and is not a
//! code at all. It is likewise distinct from the sibling variable-length code
//! families `elias_gamma_delta`, `golomb_rice_code`, and `varint_leb128`: those
//! encode magnitudes with explicit length prefixes, unary quotients, or
//! fixed-width `byte` groups. The Fibonacci code here is defined purely by the
//! Zeckendorf non-adjacent representation plus the `11` self-delimiting
//! terminator and shares none of their tables or helpers.
//!
//! All Fibonacci values are produced by integer recurrence (rolling `a`, `b`);
//! the `Binet` closed form and every transcendental or floating-point operation
//! are intentionally avoided. The reference is integer only and bit-exact on
//! any target.

use alloc::vec::Vec;

/// Returns the `index`-th Zeckendorf Fibonacci value, where `index` is 1-based:
/// value 1 is `1`, value 2 is `2`, value 3 is `3`, value 4 is `5`, and so on.
///
/// `index` 0 yields `0`. The value is produced by integer recurrence, never by
/// the `Binet` closed form.
pub fn fib_value(index: usize) -> u64 {
    if index == 0 {
        return 0;
    }
    let mut a: u64 = 1;
    let mut b: u64 = 2;
    if index == 1 {
        return a;
    }
    for _ in 3..=index {
        let next = a + b;
        a = b;
        b = next;
    }
    b
}

/// Returns every Zeckendorf Fibonacci value less than or equal to `n`, in
/// increasing order (`1, 2, 3, 5, 8, ...`).
///
/// The values are generated by integer recurrence and the iteration stops
/// before any term would overflow `u64`.
pub fn fib_values_up_to(n: u64) -> Vec<u64> {
    let mut values = Vec::new();
    let mut a: u64 = 1;
    let mut b: u64 = 2;
    while a <= n {
        values.push(a);
        match a.checked_add(b) {
            Some(next) => {
                a = b;
                b = next;
            }
            None => break,
        }
    }
    values
}

/// Decomposes `n` into the 1-based positions of the Zeckendorf Fibonacci values
/// whose sum equals `n`.
///
/// The returned positions are strictly increasing and never adjacent
/// (consecutive positions differ by at least 2). `n` equal to 0 yields an empty
/// vector.
pub fn zeckendorf_decompose(n: u64) -> Vec<usize> {
    let values = fib_values_up_to(n);
    let mut positions = Vec::new();
    let mut remaining = n;
    for (offset, &value) in values.iter().enumerate().rev() {
        if value <= remaining {
            positions.push(offset + 1);
            remaining -= value;
        }
    }
    positions.reverse();
    positions
}

/// Encodes `n` as Fibonacci-code bits: the Zeckendorf bits ordered from the
/// smallest value to the largest, followed by a terminating `1` bit so the
/// codeword ends with the `11` pattern.
///
/// `n` equal to 0 encodes as the single terminator bit.
pub fn fib_encode(n: u64) -> Vec<bool> {
    let positions = zeckendorf_decompose(n);
    let mut bits = Vec::new();
    if let Some(&highest) = positions.last() {
        bits.resize(highest, false);
        for &position in &positions {
            bits[position - 1] = true;
        }
    }
    bits.push(true);
    bits
}

/// Decodes a single Fibonacci codeword back into its integer value.
///
/// The final bit is the terminator and is ignored; every other set bit at
/// 1-based position `p` contributes `fib_value(p)`. An empty slice decodes to 0.
pub fn fib_decode(bits: &[bool]) -> u64 {
    if bits.is_empty() {
        return 0;
    }
    let body = &bits[..bits.len() - 1];
    let mut total: u64 = 0;
    for (offset, &bit) in body.iter().enumerate() {
        if bit {
            total += fib_value(offset + 1);
        }
    }
    total
}

/// Encodes a sequence of values by concatenating their Fibonacci codewords.
///
/// Because each codeword ends with the unique `11` terminator, the resulting
/// bitstream is self-delimiting. Intended for positive values.
pub fn fib_encode_sequence(values: &[u64]) -> Vec<bool> {
    let mut bits = Vec::new();
    for &value in values {
        bits.extend(fib_encode(value));
    }
    bits
}

/// Decodes a self-delimiting bitstream produced by `fib_encode_sequence`.
///
/// Each codeword is terminated by the first `11` pattern encountered after its
/// start, since Zeckendorf bits are never adjacent.
pub fn fib_decode_sequence(bits: &[bool]) -> Vec<u64> {
    let mut values = Vec::new();
    let mut start = 0;
    let mut previous = false;
    for (index, &bit) in bits.iter().enumerate() {
        if bit && previous {
            values.push(fib_decode(&bits[start..=index]));
            start = index + 1;
            previous = false;
        } else {
            previous = bit;
        }
    }
    values
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::string::String;
    use alloc::vec::Vec;

    fn bits_to_string(bits: &[bool]) -> String {
        let mut text = String::new();
        for &bit in bits {
            text.push(if bit { '1' } else { '0' });
        }
        text
    }

    fn bits_from_string(text: &str) -> Vec<bool> {
        text.chars().map(|c| c == '1').collect()
    }

    fn code_string(n: u64) -> String {
        bits_to_string(&fib_encode(n))
    }

    #[test]
    fn fib_value_matches_known_values() {
        let expected = [1u64, 2, 3, 5, 8, 13, 21, 34, 55, 89];
        for (offset, &value) in expected.iter().enumerate() {
            assert_eq!(fib_value(offset + 1), value);
        }
    }

    #[test]
    fn fib_value_zero_is_zero() {
        assert_eq!(fib_value(0), 0);
    }

    #[test]
    fn fib_value_is_strictly_increasing() {
        for index in 1..40 {
            assert!(fib_value(index) < fib_value(index + 1));
        }
    }

    #[test]
    fn fib_values_up_to_seven() {
        assert_eq!(fib_values_up_to(7), [1, 2, 3, 5]);
    }

    #[test]
    fn fib_values_up_to_one() {
        assert_eq!(fib_values_up_to(1), [1]);
    }

    #[test]
    fn fib_values_up_to_zero_is_empty() {
        assert!(fib_values_up_to(0).is_empty());
    }

    #[test]
    fn fib_values_up_to_matches_fib_value() {
        let values = fib_values_up_to(1000);
        for (offset, &value) in values.iter().enumerate() {
            assert_eq!(value, fib_value(offset + 1));
        }
    }

    #[test]
    fn encode_one() {
        assert_eq!(code_string(1), "11");
    }

    #[test]
    fn encode_two() {
        assert_eq!(code_string(2), "011");
    }

    #[test]
    fn encode_three() {
        assert_eq!(code_string(3), "0011");
    }

    #[test]
    fn encode_four() {
        assert_eq!(code_string(4), "1011");
    }

    #[test]
    fn encode_five() {
        assert_eq!(code_string(5), "00011");
    }

    #[test]
    fn encode_six() {
        assert_eq!(code_string(6), "10011");
    }

    #[test]
    fn encode_seven() {
        assert_eq!(code_string(7), "01011");
    }

    #[test]
    fn encode_table_eight_to_twenty() {
        let table = [
            (8u64, "000011"),
            (9, "100011"),
            (10, "010011"),
            (11, "001011"),
            (12, "101011"),
            (13, "0000011"),
            (14, "1000011"),
            (15, "0100011"),
            (16, "0010011"),
            (17, "1010011"),
            (18, "0001011"),
            (19, "1001011"),
            (20, "0101011"),
        ];
        for &(n, expected) in table.iter() {
            assert_eq!(code_string(n), expected);
        }
    }

    #[test]
    fn decode_examples_one_to_seven() {
        let table = [
            (1u64, "11"),
            (2, "011"),
            (3, "0011"),
            (4, "1011"),
            (5, "00011"),
            (6, "10011"),
            (7, "01011"),
        ];
        for &(n, code) in table.iter() {
            assert_eq!(fib_decode(&bits_from_string(code)), n);
        }
    }

    #[test]
    fn decode_table_eight_to_twenty() {
        let table = [
            (8u64, "000011"),
            (9, "100011"),
            (10, "010011"),
            (11, "001011"),
            (12, "101011"),
            (13, "0000011"),
            (14, "1000011"),
            (15, "0100011"),
            (16, "0010011"),
            (17, "1010011"),
            (18, "0001011"),
            (19, "1001011"),
            (20, "0101011"),
        ];
        for &(n, code) in table.iter() {
            assert_eq!(fib_decode(&bits_from_string(code)), n);
        }
    }

    #[test]
    fn roundtrip_encode_decode_small_and_medium() {
        for n in 1..=10_000u64 {
            assert_eq!(fib_decode(&fib_encode(n)), n);
        }
    }

    #[test]
    fn decompose_sum_equals_input() {
        for n in 1..=5_000u64 {
            let positions = zeckendorf_decompose(n);
            let sum: u64 = positions.iter().map(|&p| fib_value(p)).sum();
            assert_eq!(sum, n);
        }
    }

    #[test]
    fn decompose_is_non_adjacent() {
        for n in 1..=5_000u64 {
            let positions = zeckendorf_decompose(n);
            for window in positions.windows(2) {
                assert!(window[1] - window[0] >= 2);
            }
        }
    }

    #[test]
    fn decompose_is_strictly_increasing() {
        for n in 1..=5_000u64 {
            let positions = zeckendorf_decompose(n);
            for window in positions.windows(2) {
                assert!(window[0] < window[1]);
            }
        }
    }

    #[test]
    fn decompose_zero_is_empty() {
        assert!(zeckendorf_decompose(0).is_empty());
    }

    #[test]
    fn decompose_one_is_single_position() {
        assert_eq!(zeckendorf_decompose(1), [1usize]);
    }

    #[test]
    fn terminator_appears_only_at_end() {
        for n in 1..=2_000u64 {
            let bits = fib_encode(n);
            let double_ones = bits.windows(2).filter(|w| w[0] && w[1]).count();
            assert_eq!(double_ones, 1);
            let last = bits
                .windows(2)
                .enumerate()
                .filter(|(_, w)| w[0] && w[1])
                .map(|(i, _)| i)
                .next_back()
                .unwrap();
            assert_eq!(last, bits.len() - 2);
        }
    }

    #[test]
    fn every_code_ends_with_double_one() {
        for n in 1..=2_000u64 {
            let bits = fib_encode(n);
            let len = bits.len();
            assert!(bits[len - 1]);
            assert!(bits[len - 2]);
        }
    }

    #[test]
    fn set_bit_count_is_terms_plus_terminator() {
        for n in 1..=2_000u64 {
            let terms = zeckendorf_decompose(n).len();
            let ones = fib_encode(n).iter().filter(|&&b| b).count();
            assert_eq!(ones, terms + 1);
        }
    }

    #[test]
    fn encode_sequence_sample_bits() {
        let bits = fib_encode_sequence(&[1, 2, 3]);
        assert_eq!(bits_to_string(&bits), "110110011");
    }

    #[test]
    fn decode_sequence_of_sample_bits() {
        let bits = bits_from_string("110110011");
        assert_eq!(fib_decode_sequence(&bits), [1u64, 2, 3]);
    }

    #[test]
    fn sequence_roundtrip_over_range() {
        let values: Vec<u64> = (1..=500u64).collect();
        let bits = fib_encode_sequence(&values);
        assert_eq!(fib_decode_sequence(&bits), values);
    }

    #[test]
    fn sequence_roundtrip_mixed_values() {
        let values = [7u64, 42, 1, 999, 10_000, 13, 2];
        let bits = fib_encode_sequence(&values);
        assert_eq!(fib_decode_sequence(&bits), values);
    }

    #[test]
    fn encode_sequence_empty_is_empty() {
        assert!(fib_encode_sequence(&[]).is_empty());
    }

    #[test]
    fn decode_sequence_empty_is_empty() {
        assert!(fib_decode_sequence(&[]).is_empty());
    }

    #[test]
    fn single_decode_of_empty_is_zero() {
        let empty: [bool; 0] = [];
        assert_eq!(fib_decode(&empty), 0);
    }

    #[test]
    fn encode_zero_is_single_terminator() {
        let bits = fib_encode(0);
        assert_eq!(bits_to_string(&bits), "1");
        assert_eq!(fib_decode(&bits), 0);
    }

    #[test]
    fn large_fibonacci_decomposes_to_single_term() {
        for index in 1..=40 {
            let value = fib_value(index);
            assert_eq!(zeckendorf_decompose(value), [index]);
        }
    }

    #[test]
    fn large_fibonacci_roundtrips() {
        let value = fib_value(40);
        assert_eq!(fib_decode(&fib_encode(value)), value);
    }

    #[test]
    fn value_near_u32_max_roundtrips() {
        let n = u64::from(u32::MAX);
        assert_eq!(fib_decode(&fib_encode(n)), n);
    }

    #[test]
    fn large_sequence_roundtrips() {
        let values = [fib_value(30), fib_value(45), 1, fib_value(10), 123_456];
        let bits = fib_encode_sequence(&values);
        assert_eq!(fib_decode_sequence(&bits), values);
    }
}
