//! Real-device parity for the per-query bounds twin:
//! [`GpuBounds`](prism_volumetric_gpu::bounds::GpuBounds) must reproduce the
//! `CPU` golden [`bounds`](prism_render_architecture::particle::bounds) across
//! the box center, half-extent, surface area, longest-axis code and empty flag,
//! the two-box union, the point-expansion, and the first-pass workgroup /
//! partial counts.
//!
//! The fixtures cover the shapes the golden unit tests call out — a unit cube, a
//! box with a clearly widest axis on each of x, y and z, a union that spans two
//! disjoint boxes, a point-expansion that grows a box, the empty box (reported
//! empty, with the union identity and the degenerate point-box checked), and the
//! sizing cases (one particle, an exact divisor, a remainder that rounds up, a
//! workgroup size clamped low and one clamped high, and zero particles) — plus a
//! large pseudo-random batch. All random fixtures are generated by a host-side
//! `u64` `LCG` and use rejection sampling to stay clear of zero-volume boxes,
//! coincident corners and longest-axis ties, and never call an `f32`
//! transcendental.
//!
//! The tests skip (returning early) when the host has no `wgpu` adapter, so the
//! suite stays green everywhere while still exercising the full
//! dispatch-and-readback on any real device such as an Apple `M`-series `GPU`.
//! The kernel is portable core-`WGSL`, so it needs no optional device feature.
//!
//! # Parity criterion
//!
//! The longest-axis code, the empty flag and the workgroup / partial counts are
//! discrete classifications or integer arithmetic, so `CPU` and `GPU` must agree
//! exactly: the comparison is an exact `==`. The center, half-extent, surface
//! area, union corners and expanded corners thread through adds, multiplies and
//! `min` / `max`, so they are compared under tolerance (`abs_diff <= 1e-4` or
//! `rel_diff <= 1e-3`, `REL_FLOOR = 1e-6`).
//!
//! Provenance: 孪生自本仓 `prism_render_architecture::particle::bounds`；无第三方引擎源码或衍生代码。

use prism_render_architecture::particle::bounds::{Aabb, BoundsReduction};
use prism_volumetric_gpu::bounds::{GpuBounds, GpuBoundsQuery};
use prism_volumetric_gpu::GpuContext;

/// Absolute tolerance for the continuous quantities.
const ABS_EPS: f32 = 1.0e-4;
/// Relative tolerance for the continuous quantities.
const REL_EPS: f32 = 1.0e-3;
/// Floor for the relative-tolerance denominator.
const REL_FLOOR: f32 = 1.0e-6;

/// Mixed absolute / relative tolerance comparison for one `f32` lane.
fn approx(a: f32, b: f32) -> bool {
    let diff = (a - b).abs();
    if diff <= ABS_EPS {
        return true;
    }
    let scale = a.abs().max(b.abs()).max(REL_FLOOR);
    diff / scale <= REL_EPS
}

/// Tolerant comparison of two `vec3` triples.
fn approx3(a: [f32; 3], b: [f32; 3]) -> bool {
    approx(a[0], b[0]) && approx(a[1], b[1]) && approx(a[2], b[2])
}

/// Builds a query from the two boxes, the probe point and the sizing pair.
fn query(
    a_min: [f32; 3],
    a_max: [f32; 3],
    b_min: [f32; 3],
    b_max: [f32; 3],
    point: [f32; 3],
    particle_count: u32,
    workgroup_size: u32,
) -> GpuBoundsQuery {
    GpuBoundsQuery {
        a_min,
        a_max,
        b_min,
        b_max,
        point,
        particle_count,
        workgroup_size,
    }
}

/// Asserts every twinned answer for one query matches the `CPU` golden.
fn assert_parity(gpu: &GpuBounds, ctx: &GpuContext, q: &GpuBoundsQuery) {
    let got = gpu.evaluate(ctx, std::slice::from_ref(q));
    assert_eq!(got.len(), 1, "one result per query");
    let g = got[0];

    let a = Aabb {
        min: q.a_min,
        max: q.a_max,
    };
    let b = Aabb {
        min: q.b_min,
        max: q.b_max,
    };

    // Empty flag: exact classification, always compared.
    assert_eq!(
        g.is_empty,
        a.is_empty(),
        "is_empty mismatch for box {:?}..{:?}",
        q.a_min,
        q.a_max
    );

    // union(a, b): finite even when `a` is empty (empty is the identity).
    let union = a.union(&b);
    assert!(
        approx3(g.union_min, union.min),
        "union_min mismatch: gpu {:?} vs cpu {:?}",
        g.union_min,
        union.min
    );
    assert!(
        approx3(g.union_max, union.max),
        "union_max mismatch: gpu {:?} vs cpu {:?}",
        g.union_max,
        union.max
    );

    // expand_point: finite even when `a` is empty (yields the degenerate box at
    // the probe point).
    let mut expanded = a;
    expanded.expand_point(q.point);
    assert!(
        approx3(g.expanded_min, expanded.min),
        "expanded_min mismatch: gpu {:?} vs cpu {:?}",
        g.expanded_min,
        expanded.min
    );
    assert!(
        approx3(g.expanded_max, expanded.max),
        "expanded_max mismatch: gpu {:?} vs cpu {:?}",
        g.expanded_max,
        expanded.max
    );

    // First-pass sizing: exact integer arithmetic.
    let plan = BoundsReduction::new(q.particle_count, q.workgroup_size);
    assert_eq!(
        g.workgroup_count,
        plan.workgroup_count(),
        "workgroup_count mismatch for ({}, {})",
        q.particle_count,
        q.workgroup_size
    );
    assert_eq!(
        g.partial_count,
        plan.partial_count(),
        "partial_count mismatch for ({}, {})",
        q.particle_count,
        q.workgroup_size
    );

    // Continuous geometry and the longest-axis code of box `a` are only
    // meaningful for a non-empty box; an empty box's corners are sentinels whose
    // differences overflow, so the host guards them.
    if !a.is_empty() {
        assert!(
            approx3(g.center, a.center()),
            "center mismatch: gpu {:?} vs cpu {:?}",
            g.center,
            a.center()
        );
        assert!(
            approx3(g.half_extent, a.half_extent()),
            "half_extent mismatch: gpu {:?} vs cpu {:?}",
            g.half_extent,
            a.half_extent()
        );
        assert!(
            approx(g.surface_area, a.surface_area()),
            "surface_area mismatch: gpu {} vs cpu {}",
            g.surface_area,
            a.surface_area()
        );
        assert_eq!(
            g.longest_axis,
            u32::from(a.longest_axis()),
            "longest_axis mismatch for box {:?}..{:?}",
            q.a_min,
            q.a_max
        );
    }
}

/// A tiny `u64` linear-congruential generator (`SplitMix`-style constants) for
/// deterministic, transcendental-free fixtures.
struct Lcg {
    state: u64,
}

impl Lcg {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u32(&mut self) -> u32 {
        self.state = self
            .state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        (self.state >> 32) as u32
    }

    /// Uniform `f32` in `[0, 1)` built only from integer casts and division.
    fn next_unit(&mut self) -> f32 {
        let bits = self.next_u32() >> 8;
        (bits as f32) / (1u32 << 24) as f32
    }

    /// Uniform `f32` in `[lo, hi)`.
    fn next_range(&mut self, lo: f32, hi: f32) -> f32 {
        lo + (hi - lo) * self.next_unit()
    }
}

/// Draws a non-degenerate box whose longest axis is unambiguous: all three
/// extents are at least `0.2` (positive volume) and the two largest differ by at
/// least `0.25` (no longest-axis tie).
fn sample_box(rng: &mut Lcg) -> ([f32; 3], [f32; 3]) {
    loop {
        let min = [
            rng.next_range(-8.0, 8.0),
            rng.next_range(-8.0, 8.0),
            rng.next_range(-8.0, 8.0),
        ];
        let ext = [
            rng.next_range(0.2, 10.0),
            rng.next_range(0.2, 10.0),
            rng.next_range(0.2, 10.0),
        ];
        let mut sorted = ext;
        sorted.sort_by(|x, y| x.partial_cmp(y).unwrap());
        // sorted[2] is the largest extent, sorted[1] the runner-up.
        if sorted[2] - sorted[1] < 0.25 {
            continue;
        }
        let max = [min[0] + ext[0], min[1] + ext[1], min[2] + ext[2]];
        return (min, max);
    }
}

#[test]
fn structured_boxes_match_golden() {
    let Some(ctx) = GpuContext::try_headless() else {
        return;
    };
    let gpu = GpuBounds::new(&ctx);

    // Unit cube: center 0.5, half-extent 0.5, surface area 6, longest axis ties
    // toward x (0). Union with a disjoint box, expand toward a far point.
    let unit = query(
        [0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0],
        [2.0, 2.0, 2.0],
        [3.0, 4.0, 5.0],
        [-1.0, 2.0, 0.5],
        1,
        256,
    );
    assert_parity(&gpu, &ctx, &unit);

    // Clear longest axis on y.
    let widest_y = query(
        [0.0, 0.0, 0.0],
        [1.0, 5.0, 2.0],
        [-1.0, -1.0, -1.0],
        [0.0, 0.0, 0.0],
        [0.5, 6.0, 1.0],
        1024,
        256,
    );
    assert_parity(&gpu, &ctx, &widest_y);

    // Clear longest axis on z.
    let widest_z = query(
        [-2.0, -2.0, -2.0],
        [-1.0, -1.0, 7.0],
        [1.0, 1.0, 1.0],
        [2.0, 2.0, 2.0],
        [-1.5, -1.5, 10.0],
        1025,
        256,
    );
    assert_parity(&gpu, &ctx, &widest_z);

    // Clear longest axis on x.
    let widest_x = query(
        [0.0, 0.0, 0.0],
        [9.0, 1.0, 2.0],
        [-5.0, -5.0, -5.0],
        [-4.0, -4.0, -4.0],
        [10.0, 0.5, 1.0],
        200,
        256,
    );
    assert_parity(&gpu, &ctx, &widest_x);
}

#[test]
fn empty_box_reports_empty_and_identity() {
    let Some(ctx) = GpuContext::try_headless() else {
        return;
    };
    let gpu = GpuBounds::new(&ctx);
    // An empty box `a` (min at f32::MAX, max at f32::MIN) must report empty; its
    // union with a real box `b` returns `b` (the identity), and expanding it by
    // a point yields the degenerate box at that point.
    let empty = query(
        [f32::MAX, f32::MAX, f32::MAX],
        [f32::MIN, f32::MIN, f32::MIN],
        [-1.0, -2.0, -3.0],
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0],
        0,
        256,
    );
    assert_parity(&gpu, &ctx, &empty);
}

#[test]
fn sizing_cases_match_golden() {
    let Some(ctx) = GpuContext::try_headless() else {
        return;
    };
    let gpu = GpuBounds::new(&ctx);
    // Reuse one real box so the geometry stays valid while the sizing varies.
    let a_min = [0.0, 0.0, 0.0];
    let a_max = [1.0, 2.0, 3.0];
    let b_min = [-1.0, -1.0, -1.0];
    let b_max = [0.5, 0.5, 0.5];
    let p = [0.25, 0.75, 1.5];
    let cases = [
        (1u32, 256u32),  // one particle -> one workgroup.
        (1024, 256),     // exact divisor -> 4 workgroups.
        (1025, 256),     // remainder rounds up -> 5 workgroups.
        (100, 0),        // workgroup size clamps low to 1 -> 100.
        (4096, 100_000), // workgroup size clamps high to 1024 -> 4.
        (0, 256),        // zero particles -> zero workgroups.
    ];
    for (count, ws) in cases {
        let q = query(a_min, a_max, b_min, b_max, p, count, ws);
        assert_parity(&gpu, &ctx, &q);
    }
}

#[test]
fn random_batch_matches_elementwise() {
    let Some(ctx) = GpuContext::try_headless() else {
        return;
    };
    let gpu = GpuBounds::new(&ctx);
    let mut rng = Lcg::new(0x5EED_1234_ABCD_9F01);
    let mut batch: Vec<GpuBoundsQuery> = Vec::with_capacity(256);
    for _ in 0..256 {
        let (a_min, a_max) = sample_box(&mut rng);
        let (b_min, b_max) = sample_box(&mut rng);
        let point = [
            rng.next_range(-10.0, 10.0),
            rng.next_range(-10.0, 10.0),
            rng.next_range(-10.0, 10.0),
        ];
        let particle_count = rng.next_u32() % 200_001;
        let workgroup_size = rng.next_u32() % 2_000;
        batch.push(query(
            a_min,
            a_max,
            b_min,
            b_max,
            point,
            particle_count,
            workgroup_size,
        ));
    }
    let got = gpu.evaluate(&ctx, &batch);
    assert_eq!(got.len(), batch.len());
    for q in &batch {
        assert_parity(&gpu, &ctx, q);
    }
}

#[test]
fn empty_batch_short_circuits() {
    let Some(ctx) = GpuContext::try_headless() else {
        return;
    };
    let gpu = GpuBounds::new(&ctx);
    // No dispatch is issued and the result vector is empty.
    assert!(gpu.evaluate(&ctx, &[]).is_empty());
}
